LPS-140736 Ensure no violations on A11yTool
liferay-frontend/liferay-portal pull request #1583
Opened 2021-10-18 22:40 UTC by susanchen3

https://issues.liferay.com/browse/LPS-140736

2021-10-18 22:40 UTC, liferay-continuous-integration commented
Please only forward necessary changes to Brian Chan during stabilization. Nonurgent changes should wait until the ongoing DXP 7.4 GA1 and Portal 7.4 GA4 release has been completed. For more details on the release timeline and status, see <a href="https://liferay.slack.com/archives/C03BTCQBQ">product-delivery</a>.

2021-10-18 22:40 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2021-10-18 22:40 UTC, susanchen3 commented
ci:test:sf

2021-10-18 22:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/501/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com//userContent/jobs/test-portal-source-format/builds/501/jenkins-report.html">here</a>.</b></p>

2021-10-18 22:42 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0530ed44c1eb186650ef60a006e0e5f571595a52">0530ed44c1eb186650ef60a006e0e5f571595a52</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/susanchen3/liferay-portal/tree/LPS-140736">LPS-140736</a><br/>Branch GIT ID: <a href="https://github.com/susanchen3/liferay-portal/commit/59fae065abd91070f0ae3bad9acb71ffcd006b78">59fae065abd91070f0ae3bad9acb71ffcd006b78</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/501/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/501/jenkins-report.html">here</a>.</h5><pre><code>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./modules/apps/frontend-js/frontend-js-test/src/testFunctional/A11yTool.testcase expected:&lt;...assic Theme Page");
     [java] [
     [java] 		JSONLayout.addWidgetToPublicLayout(
     [java] 			groupName = "Guest",
     [java] 			layoutName = "Classic Theme Page",
     [java] 			widgetName = "JS Clay Sample Web");
     [java] 
     [java] 		Navigator.gotoPage(pageName = "Classic Theme Page");
     [java] 	\}
     [java] 
     [java] 	tearDown \{
     [java] 		var testPortalInstance = PropsUtil.get("test.portal.instance");
     [java] 
     [java] 		if ("\$\{testPortalInstance\}" == "true") \{
     [java] 			PortalInstances.tearDownCP();
     [java] 		\}
     [java] 		else \{
     [java] 			Page.tearDownCP();
     [java] 		\}
     [java] 	\}
     [java] 
     [java] 	@description = "LPS-140736. Ensures there is no accessibility side panel on a page with no violations."
     [java] 	@priority = "5"
     [java] 	test CanDetectNoViolations \{
     [java] 		Navigator.gotoPage(pageName = "Home");
     [java] 
     [java] 		if (IsElementPresent(locator1 = "A11yTool#ACCESSIBILITY_PANEL_HEADING")) \{
     [java] 			Refresh();
     [java] 		\}
     [java] 
     [java] 		AssertElementNotPresent(locator1 = "A11yTool#ACCESSIBILITY_PANEL_HEADING");
     [java] 	\}
     [java] ]
     [java] \}&gt; but was:&lt;...assic Theme Page");
     [java] [		
     [java] 		JSONLayout.addWidgetToPublicLayout(
     [java] 			groupName = "Guest",
     [java] 			layoutName = "Classic Theme Page",
     [java] 			widgetName = "JS Clay Sample Web");
     [java] 		
     [java] 		Navigator.gotoPage(pageName = "Classic Theme Page");
     [java] 	\}
     [java] 
     [java] 	tearDown \{
     [java] 		var testPortalInstance = PropsUtil.get("test.portal.instance");
     [java] 
     [java] 		if ("\$\{testPortalInstance\}" == "true") \{
     [java] 			PortalInstances.tearDownCP();
     [java] 		\}
     [java] 		else \{
     [java] 			Page.tearDownCP();
     [java] 		\}
     [java] 	\}
     [java] 
     [java] 	@description = "LPS-140736. Ensures there is no accessibility side panel on a page with no violations."
     [java] 	@priority = "5"
     [java] 	test CanDetectNoViolations \{
     [java] 		Navigator.gotoPage(pageName = "Home");
     [java] 
     [java] 		if (IsElementPresent(locator1 = "A11yTool#ACCESSIBILITY_PANEL_HEADING")) \{
     [java] 			Refresh();
     [java] 		\}
     [java] 		</code></pre></details></html>

2021-10-18 23:00 UTC, susanchen3 commented
ci:test:sf

2021-10-18 23:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/714/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com//userContent/jobs/test-portal-source-format/builds/714/jenkins-report.html">here</a>.</b></p>

2021-10-18 23:06 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/714/">test-portal-source-format#714</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/714/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/1583">liferay-frontend#1583</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1570050675">[master] ci:test:sf - susanchen3 &gt; liferay-frontend - PR#1583 - 2021-10-18[16:01:03]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/2389/">publish-testray-report#2389</a><br/></div></div>

2021-10-19 00:49 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 10 out of 11 jobs passed</h3><h3>:x: ci:test:relevant - 23 out of 25 jobs passed in 1 hour 53 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/2461">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1107401_5019</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0530ed44c1eb186650ef60a006e0e5f571595a52">0530ed44c1eb186650ef60a006e0e5f571595a52</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/04747799e8b8d494566b2306aaad4ae141d4c5df">04747799e8b8d494566b2306aaad4ae141d4c5df</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2460">Acceptance Upstream DXP (master) #2460</a></p><details><summary><strong>ci:test:stable - 10 out of 11 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11469/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>10 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9380/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9070/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/5254/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/5253/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9066/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/5256/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9382/">test-portal-acceptance-pullrequest-batch(master)/portal-license-smoke-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9068/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11470/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9383/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 23 out of 25 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest(master)/5019/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11469/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>23 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/739/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11642/">test-portal-acceptance-pullrequest-batch(master)/empty-temp-dir-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9069/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9380/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9384/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11640/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9070/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/5254/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/5255/">test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9071/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9072/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/5253/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9067/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9073/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9066/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9381/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/5256/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9382/">test-portal-acceptance-pullrequest-batch(master)/portal-license-smoke-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/9068/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/11641/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a [...]

2021-10-19 00:58 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest(master)/5019/">test-portal-acceptance-pullrequest(master)#5019</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5019/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/1583">liferay-frontend#1583</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1570090789">[master] ci:test:relevant - susanchen3 &gt; liferay-frontend - PR#1583 - 2021-10-18[15:44:21]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-10.liferay.com/job/publish-testray-report/1626/">publish-testray-report#1626</a><br/></div></div>

2021-10-19 18:46 UTC, john-co requested changes

2021-10-19 18:46 UTC, john-co commented on modules/apps/frontend-js/frontend-js-test/src/testFunctional/A11yTool.testcase
> +		property osgi.modules.includes = "frontend-js-clay-sample-web";
move to global property block line 4

2021-10-19 18:46 UTC, john-co commented on modules/apps/frontend-js/frontend-js-test/src/testFunctional/A11yTool.testcase
> +			layoutName = "Classic Theme Page");
Make sure copied artifacts are adjusted to the testcase. This is not a theme testcase.

2021-10-19 18:46 UTC, john-co commented on modules/apps/frontend-js/frontend-js-test/src/testFunctional/A11yTool.testcase
> +		AssertElementNotPresent(locator1 = "A11yTool#ACCESSIBILITY_PANEL_HEADING");
You have the first assertion but remember the other two assertions from the test case.

```
Then side panel will list no violations on the page
And Then there are no highlight elements present on the page
And Then there are no icons present on the page ("!" icon next to potential highlight element)
```

2021-10-19 18:46 UTC, john-co commented on modules/apps/frontend-js/frontend-js-test/src/testFunctional/A11yTool.path
> +	<td>//span[contains(text(),'Accessibility Violations')]</td>
I'd recommend using semantic tags if possible and for the path locator elements/attributes to relate to the target we're interested in. ie: the name of the path is ACCESSIBILITY_PANEL_HEADING so I'd search for key attribute names such as class="sidebar" or "sidenav" or "sidebar-header" to include in path locator.

Some other guidelines I recommend:
https://docs.google.com/spreadsheets/d/1KgMk5CoAB0Kqylg2dufw9X4zGenrWNEv13KdVckrkvg/edit#gid=1536975616

example: Assert ADD_PANEL_HEADER `//*[contains(@class,'lfr-add-panel')]//*[contains(@class,'sidebar-header')]`
![screenshot_7](https://user-images.githubusercontent.com/35235266/137970426-943a9f99-85f8-45fb-80c3-6bed5ced644e.png)

This is nit picky but crafting a robust locator is something I like to invest in.

2021-10-19 18:46 UTC, john-co commented on portal-web/test/functional/com/liferay/portalweb/macros/json/layout/JSONLayoutUtil.macro
> +		}
Nice, I'll add the A11y test artifact to the list and update the testcase.

2021-10-19 18:46 UTC, john-co commented on modules/apps/frontend-js/frontend-js-test/src/testFunctional/A11yTool.testcase
> +		Navigator.gotoPage(pageName = "Home");
Maybe create a blank page instead since Home has the Welcome portlet/fragment.

2021-10-19 18:53 UTC, closed without merging

2021-10-21 00:25 UTC, john-co commented
ci:test:frontend:nocompile