LPS-141235 Add test that verifies remote app type IFrame can display property fields
liferay-frontend/liferay-portal pull request #1669
Opened 2021-11-15 17:25 UTC by sergiojimcos

RemoteApps#IframeTypeCanDisplayProperFields

Test scenario:

Given: **Remote Apps** Add page.
When: Type is **IFrame**.
Then: **HTML Element Name** and **CSS URL** fields are not present.
When: select type **Custom Element**.
Then: **HTML Element Name** and **CSS URL** fields are present.

2021-11-15 17:25 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2021-11-15 17:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest(master)/5058/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="${top.level.user.content.url}/jenkins-report.html">here</a>.</b></p>

2021-11-15 17:27 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-5.liferay.com/job/test-portal-source-format/5186/">test-portal-source-format</a></p><p><b>For more details click <a href="${top.level.user.content.url}/jenkins-report.html">here</a>.</b></p>

2021-11-15 17:29 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/91ada1e18e2f9884f61fb93a6b0da2079549ac69">91ada1e18e2f9884f61fb93a6b0da2079549ac69</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/sergiojimcos/liferay-portal/tree/LPS-141235">LPS-141235</a><br/>Branch GIT ID: <a href="https://github.com/sergiojimcos/liferay-portal/commit/dc28bd81cc5b548e74cc709459cd92d295ca7ab1">dc28bd81cc5b548e74cc709459cd92d295ca7ab1</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-5.liferay.com/job/test-portal-source-format/5186/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-source-format/builds/5186/jenkins-report.html">here</a>.</h5></details></html>

2021-11-15 17:32 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-5.liferay.com/job/test-portal-source-format/5186/">test-portal-source-format#5186</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-source-format/builds/5186/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/1669">liferay-frontend#1669</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1579678228">[master] ci:test:sf - sergiojimcos &gt; liferay-frontend - PR#1669 - 2021-11-15[09:26:09]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-5.liferay.com/job/publish-testray-report/1147/">publish-testray-report#1147</a><br/></div></div>

2021-11-15 17:34 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest(master)/5058/">test-portal-acceptance-pullrequest(master)#5058</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5058/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/1669">liferay-frontend#1669</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1579678799">[master] ci:test:relevant - sergiojimcos &gt; liferay-frontend - PR#1669 - 2021-11-15[09:26:05]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-10.liferay.com/job/publish-testray-report/1803/">publish-testray-report#1803</a><br/></div></div>

2021-11-16 08:10 UTC, sergiojimcos commented
ci:test:frontend:nocompile

2021-11-16 08:11 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2021-11-16 08:11 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>frontend</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest(master)/6412/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="${top.level.user.content.url}/jenkins-report.html">here</a>.</b></p>

2021-11-16 08:51 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:frontend - 4 out of 4 jobs passed in 40 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c68077be0b2ff3f4a95ac6a181c1f5a5d0091b43">c68077be0b2ff3f4a95ac6a181c1f5a5d0091b43</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/db8c896880b6a09d2dc09ba5d793be1b2ae6da2b">db8c896880b6a09d2dc09ba5d793be1b2ae6da2b</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2577">Acceptance Upstream DXP (master) #2577</a></p><details><summary><strong>ci:test:frontend - 4 out of 4 jobs PASSED</strong></summary><details><summary><strong>4 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest(master)/6412/">test-portal-acceptance-pullrequest(master)</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/16249/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/4858/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/4857/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6412/jenkins-report.html">here</a>.</h5></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-13/jobs/test-portal-acceptance-pullrequest(master)/builds/6412/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-13/jobs/test-portal-acceptance-pullrequest(master)/builds/6412/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-13/jobs/test-portal-acceptance-pullrequest(master)/builds/6412/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2021-11-16 08:53 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest(master)/6412/">test-portal-acceptance-pullrequest(master)#6412</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6412/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>frontend<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/1669">liferay-frontend#1669</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1579874065">[master] ci:test:frontend - sergiojimcos &gt; liferay-frontend - PR#1669 - 2021-11-16[00:11:16]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-13.liferay.com/job/publish-testray-report/2267/">publish-testray-report#2267</a><br/></div></div>

2021-11-16 23:31 UTC, john-co requested changes
Looks good overall! Please review the comments and make the requested changes.

2021-11-16 23:31 UTC, john-co commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/remotewebapps/RemoteApps.testcase
> +		AssertNotVisible(locator1 = "RemoteAppsEntry#HTML_ELEMENT_INPUT");
To make the test more robust, you'll probably want to verify that Iframe type is selected and if not then select Iframe type before asserting not visible.

2021-11-16 23:31 UTC, john-co commented on portal-web/test/functional/com/liferay/portalweb/paths/portlet/remoteapps/RemoteAppsEntry.path
> +</tr>
This is usually good xpath, but my preference is to use some common xpaths found in liferay-portal/portal-web/test/functional/com/liferay/portalweb/paths/pathlib such as TextInput#ANY. I'd prefer we don't create more xpaths if we have a common pattern that can fit in well.

Please see as example: https://github.com/liferay/liferay-portal/blob/7eac9cd5daa98add4511fc853a91cd41e8f6eec6/portal-web/test/functional/com/liferay/portalweb/macros/RemoteAppsEntry.macro#L4-L18

2021-11-17 11:48 UTC, sergiojimcos commented
ci:test:frontend:nocompile

2021-11-17 11:48 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2021-11-17 11:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>frontend</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest(master)/6848/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-1.liferay.com/userContent/jobs/null/builds/null/jenkins-report.html">here</a>.</b></p>

2021-11-17 12:21 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:frontend - 4 out of 4 jobs passed in 32 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a9b82f532ece990d142ac00bde36d06729b2e72e">a9b82f532ece990d142ac00bde36d06729b2e72e</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/17613dd2b8b51913bf9cf71b3d02dc856c8384a6">17613dd2b8b51913bf9cf71b3d02dc856c8384a6</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2584">Acceptance Upstream DXP (master) #2584</a></p><details><summary><strong>ci:test:frontend - 4 out of 4 jobs PASSED</strong></summary><details><summary><strong>4 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest(master)/6848/">test-portal-acceptance-pullrequest(master)</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/16778/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/5128/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/16777/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6848/jenkins-report.html">here</a>.</h5></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-1/jobs/test-portal-acceptance-pullrequest(master)/builds/6848/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-1/jobs/test-portal-acceptance-pullrequest(master)/builds/6848/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-1/jobs/test-portal-acceptance-pullrequest(master)/builds/6848/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2021-11-17 14:12 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest(master)/6848/">test-portal-acceptance-pullrequest(master)#6848</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6848/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>frontend<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/1669">liferay-frontend#1669</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1580395510">[master] ci:test:frontend - sergiojimcos &gt; liferay-frontend - PR#1669 - 2021-11-17[03:48:34]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-1.liferay.com/job/publish-testray-report/7295/">publish-testray-report#7295</a><br/></div></div>

2021-11-18 17:42 UTC, john-co approved these changes
Looks good to me! :)

2021-11-18 17:43 UTC, john-co commented
ci:forward

2021-11-18 17:43 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-11-18 17:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-3.liferay.com/job/test-portal-source-format/6188/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/6188/jenkins-report.html">here</a>.</b></p>

2021-11-18 17:51 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bb6d5d94bc1616a63f9980a4ad1c254d040d7893">bb6d5d94bc1616a63f9980a4ad1c254d040d7893</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/sergiojimcos/liferay-portal/tree/LPS-141235">LPS-141235</a><br/>Branch GIT ID: <a href="https://github.com/sergiojimcos/liferay-portal/commit/4d7410b0e7d0e7d96610071f9de15a9f4b17f697">4d7410b0e7d0e7d96610071f9de15a9f4b17f697</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-source-format/6188/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/6188/jenkins-report.html">here</a>.</h5></details></html>

2021-11-18 17:51 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-3.liferay.com/job/test-portal-source-format/6188//consoleFull)

2021-11-18 17:52 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/110114
[Console](https://test-1-3.liferay.com/job/test-portal-source-format/6188//consoleFull)

2021-11-18 17:52 UTC, closed without merging

2021-11-18 17:54 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-3.liferay.com/job/test-portal-source-format/6188/">test-portal-source-format#6188</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/6188/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/1669">liferay-frontend#1669</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1581118245">[master] ci:test:sf - sergiojimcos &gt; liferay-frontend - PR#1669 - 2021-11-18[09:48:25]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-3.liferay.com/job/publish-testray-report/1918/">publish-testray-report#1918</a><br/></div></div>

2021-11-18 17:56 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest(master)/5169/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5169/jenkins-report.html">here</a>.</b></p>

2021-11-18 17:58 UTC, liferay-continuous-integration commented
This pull request already has open forwarded pull request(s):
https://github.com/brianchandotcom/liferay-portal/pull/110114

Pull request will not be forwarded to `brianchandotcom`.
[Console](https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest(master)/5169//consoleFull)

2021-11-18 18:01 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest(master)/5169/">test-portal-acceptance-pullrequest(master)#5169</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/5169/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/1669">liferay-frontend#1669</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1581124303">[master] ci:test:relevant - sergiojimcos &gt; liferay-frontend - PR#1669 - 2021-11-18[09:56:22]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-9.liferay.com/job/publish-testray-report/2266/">publish-testray-report#2266</a><br/></div></div>