LPS 142380
liferay-frontend/liferay-portal pull request #1672
Opened 2021-11-16 08:11 UTC by cleydyr

- LRQA-37826 Add a new test for the WCM template
- LRQA-37826 Make title more descriptive
- LRQA-37826 Assert no runtime vars return
- LRQA-39706 Add a test for the WCM template
- LRQA-37826 Need the @ to ensure it's returning
- LPS-142368 Modify macro to make it reusable
- LPS-142368 Add case to customize Text Align in each viewport
- COMMERCE-7813 Make commerce-shipping-engine-fixed-service MVCC enabled
- COMMERCE-7813 Build Service
- COMMERCE-7813 Versioning
- COMMERCE-7631 Adjust ftl to only show signin if they're not on signin page
- LPS-142431 Fix Content Dashboards Configurations Properties
- COMMERCE-7812 Make commerce-product-type-virtual-service MVCC enabled
- COMMERCE-7812 Build Service
- COMMERCE-7812 Versioning
- COMMERCE-7811 Make commerce-product-type-virtual-order-service MVCC enabled
- COMMERCE-7811 Build Service
- COMMERCE-7811 Versioning
- COMMERCE-7811 Fix squashed updates
- LPS-142346 LPS-141242 Fix value override on language change
- LPS-142346 Typo
- LPS-142346 Set predefinedValue as editor contents on change
- LPS-137489 be notified when the test is complete.
- LPS-137489 SF
- LPS-130593 Dispose delegated event when portlet is destroyed to avoid event firing more than once
- LPS-140031 Add test that validates basic ckeditor toolbar is present on DM
- LPS-140031 SF and some tags added to complete the test
- COMMERCE-7682 SBD js tests
- COMMERCE-7743 commerce-shop-by-diagram-web added account id to SBD props
- COMMERCE-7637 products urls on delivery catalog APIs
- COMMERCE-7637 gw buildRest
- COMMERCE-7637 price on storefront tooltip (SBD)
- COMMERCE-7637 useless spritemaps props removed from commerce components
- COMMERCE-7637 sf
- COMMERCE-7637 bug fixing on SBD
- COMMERCE-7847 Bug fixing on organization chart
- COMMERCE-7637 spritemap removed from commmerce react components
- COMMERCE-7637 bug fixing on SBD
- COMMERCE-7637 gw baseLine
- COMMERCE-7637 gw buildRest
- COMMERCE-7637 Hugo SF, sort. Hugo can you use hashMapBuilder for this? I believe we can with functions and a putAll with 2 maps
- COMMERCE-7637 Hugo SF, same here
- LPS-140308 Move JSP into its own folder
- LPS-140308 Add skeleton input tag
- LPS-140308 Fill in friendly URL input tag details
- LPS-140308 Remove custom logic from layout web admin
- LPS-140308 Special case for Layout
- LPS-140308 Baseline
- LPS-142461 Add draft symbol
- LPS-142461 Migrate case
- LPS-142461 Use existing macro
- LPS-141939 Remove unneeded pause and put variable inside function scope
- LPS-141939 Add conditional to avoid steps if the test is already in pages admin
- LPS-141939 Add task message in setUp
- LPS-141939 Refactor cases in WidgetPagesUI.testcase
- LPS-141939 Modify description
- LPS-141939 SF
- LPS-142462 Update path for entry thumbnail
- LPS-142458 Add site page first
- LPS-142463 Add document file by JSON
- LPS-142467 Update macro to use a suitable path
- LPS-142457 Update macro for translating fragment field
- LPS-127157 Add PortletConfigurationExtender to load resource actions and publish portlet configuration, it does not need to depend on release schema version like service configuration.
- LPS-127157 No need to do null check as it has been done before creating ServiceConfigurationInitializer
- LPS-127157 SF, inline
- LPS-127157 No need to use list to store configuration service registration
- LPS-141792 Add integration test to expose the issue
- LPS-141792 Simplify, petra and portal-kernel jars are in the same directory now, only need one of them to build the class path
- LPS-141792 Replace class name. The previous name causes duplicate items of jars in shielded-container-lib to appear in the class path, while the jars in WEB-INF/lib are missing.
- LPS-141792 SF, inline
- LPS-141792 SF, rename
- LPS-141792 Only contains petra jars for bootstrap class path, others should be the runtime class path
- LPS-141792 Add integration test to make sure bootstrap class path only contains petra
- LPS-141792 SF
- LPS-121379 Make component immediate to force early mapping loading
- LPS-141133 Remove 'ddmStructureKey' from the URL when removing a structure from the filter
- LPS-142225 search-experiences-rest-impl: Add endpoints for copying SXPElements and SXPBlueprints
- LPS-142225: gw buildRest
- LPS-142225 search-experiences-rest-impl: Copyutil
- LPS-142225 search-experiences-rest-impl: Implement methods for copying SXPElements and SXPBlueprints
- LPS-142225 Rename because it makes it more obvious what it does
- LPS-142147 Check all tags in asset publisher's groups instead of just the layout group
- LPS-142147 Baseline
- LPS-142147 as used
- LPS-142340 Support target platform verson end with u1
- LPS-142340 Use latest gradle-plugins-workspace
- LPS-142340 prep next
- LPS-142340 prep next
- LPS-142350 search-experiences-rest-api: Test: Rename within test matching files renamed
- LPS-142350 search-experiences-rest-api: FIX "java.lang.ClassNotFoundException: com.fasterxml.jackson.core.JsonProcessingException" with "gw test"
- LPS-141893 Add test to make sure FragmentEntryLinks which will become unused in live are deleted, which allows the FragmentEntry to be deleted, which allows us to avoid the DuplicateFragmentEntryKeyException.
- LPS-142411 Remove segment translations when segment deleted
- LPS-142400 Look for title in info item, use asset renderer as fallback
- COMMERCE-7826 commerce-warehouse-web Added screen navigations to warehouses
- COMMERCE-7826 commerce-warehouse-web added missing dependencies
- COMMERCE-7826 commerce-warehouse-web fixed jsp folder name
- COMMERCE-7826 commerce-warehouse-web added jsp for qualifiers
- LPS-142415 Remove extra spaces inside a string
- LPS-141854 Dropdown fixes for content page editor
- COMMERCE-7807 Make commerce-order-rule-service MVCC enabled
- COMMERCE-7807 Build Service
- COMMERCE-7807 Versioning
- COMMERCE-7807 SF
- LPS-141966 search-experiences-rest-impl: Add fieldMappings property to rest-openapi.yaml
- LPS-141966 buildREST
- LPS-141966 search-experiences-service: Add boost_all_keywords_match.json
- LPS-139479 Show the correct message if the form is not available
- LPS-142221 Allows multiple types in the layout page template entries finder
- LPS-142221 Implements new finders which accept multiple types
- LPS-142221 buildService
- LPS-142221 Allows multiple types in the layout page template entry selector criteria
- LPS-142221 Baseline
- LPS-142221 SF Removes redundant parameter, by default is status any.
- LPS-142221 Sets layout page template entry's subtitle with the collection name by default.
- LPS-142221 Handles multiple layout page template entry types in item selector.
- LPS-142221 Handles multiple layout page template entry types in stylebook preview.
- LPS-142464 Avoid NPE when processing Freemarker HTML to obtain default editable values by setting blank fragmentElementId
- LPS-136785 Add path and macro to view rate disabled
- LPS-136785 Add test to check that a guest cannot rate an entry without permissions
- LPS-136813 Add test to check that a Blog entry can be resubmitted after it is rejected
- LPS-136813 Use the fast navigation
- LPS-136813 Add entry by JSON
- LPS-136813 Update test to use correct workflow macros
- LPS-136785 Rename the macro
- LPS-136785 Remove the unnecessary step
- LPS-136785 Use fast navigation
- LPS-136785 Wordsmith
- LPS-136785 Make assertions more flexible
- LRCI-2632 Allow the base property to have brackets
- LRCI-2615 Retry when invalid json is returned from it.liferay.com for cmis vm
- LRCI-2557 Add Oracle Linux 8 functional batch
- LRCI-2557 Add Oracle Linux 8 PQL and to environments test batch list
- LRCI-2595 Update build database distribution to work for upstream tester
- LRCI-2625 Setup the portal bundle for testray imports
- LRCI-2625 prep next
- LRQA-71030 Add new macro to get the path of dependencies dir
- LRQA-71030 Rename and update macro
- LRQA-71030 Update macros and tests that use dependency files
- LRQA-71030 Move dependency files
- LRQA-71030 Update affected tests and macros
- LRQA- [...]

2021-11-16 08:11 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2021-11-16 08:12 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest(master)/8728/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="${top.level.user.content.url}/jenkins-report.html">here</a>.</b></p>

2021-11-16 08:13 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-9.liferay.com/job/test-portal-source-format/3412/">test-portal-source-format</a></p><p><b>For more details click <a href="${top.level.user.content.url}/jenkins-report.html">here</a>.</b></p>

2021-11-16 08:15 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9c08097e8ee388b26da023e243b2784369e56df9">9c08097e8ee388b26da023e243b2784369e56df9</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/cleydyr/liferay-portal/tree/LPS-142380">LPS-142380</a><br/>Branch GIT ID: <a href="https://github.com/cleydyr/liferay-portal/commit/233abbd037bf9cdf60d688fd996c72608b04d570">233abbd037bf9cdf60d688fd996c72608b04d570</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-9.liferay.com/job/test-portal-source-format/3412/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/3412/jenkins-report.html">here</a>.</h5></details></html>

2021-11-16 08:21 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-9.liferay.com/job/test-portal-source-format/3412/">test-portal-source-format#3412</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-source-format/builds/3412/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/1672">liferay-frontend#1672</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1579868951">[master] ci:test:sf - cleydyr &gt; liferay-frontend - PR#1672 - 2021-11-16[00:12:25]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-9.liferay.com/job/publish-testray-report/2167/">publish-testray-report#2167</a><br/></div></div>

2021-11-16 09:55 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 10 out of 10 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 23 out of 25 jobs passed in 1 hour 42 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9c08097e8ee388b26da023e243b2784369e56df9">9c08097e8ee388b26da023e243b2784369e56df9</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/db8c896880b6a09d2dc09ba5d793be1b2ae6da2b">db8c896880b6a09d2dc09ba5d793be1b2ae6da2b</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//2577">Acceptance Upstream DXP (master) #2577</a></p><details><summary><strong>ci:test:stable - 10 out of 10 jobs PASSED</strong></summary><details><summary><strong>10 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/15119/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/15122/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/16250/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/8822/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/4863/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/15124/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/15121/">test-portal-acceptance-pullrequest-batch(master)/portal-license-smoke-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/13241/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/4862/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/13909/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 22 out of 25 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest(master)/8728/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/15123/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</strong></strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/3951/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/lpkg-base-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>22 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/15117/">test-portal-acceptance-pullrequest-batch(master)/empty-osgi-core-dir-jdk8/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/4867/">test-portal-acceptance-pullrequest-batch(master)/empty-temp-dir-jdk8/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/4865/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/15119/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/13243/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/15122/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/13242/">test-portal-acceptance-pullrequest-batch(master)/lpkg-controller-jdk8/0</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/16250/">test-portal-acceptance-pullrequest-batch(master)/modules-compile-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/16327/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/8822/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/4864/">test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/13910/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/4863/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8_stable/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/15120/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-project-templates-jdk8/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/4866/">test-portal-acceptance-pullrequest-batch(master)/patching-tool-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/15124/">test-portal-acceptance-pullrequest-batch(master)/pmd-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/15121/">test-portal-acceptance-pullrequest-batch(master)/portal-license-smoke-jdk8/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/13241/">test-portal-acceptance-pullrequest-batch(master)/rest-builder-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/13911/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/4862/">test-portal-acceptance-pullrequest-batch(master)/service-builder-jdk8/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/15118/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/13909/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1- [...]

2021-11-16 20:23 UTC, diegonvs commented
Hey @cleydyr, could you provide a more descriptive PR title and some instructions in how to test your changes in the PR description? 💔

2021-11-17 13:42 UTC, cleydyr commented
Hey, @diegonvs .

I'm sorry that I've broken your heart by not providing enough details on the description and title :stuck_out_tongue_closed_eyes: .

The related JIRA issue is [LPS-142380](https://issues.liferay.com/browse/LPS-142380) which contains the steps to reproduce. I'll translate them to this PR description.

Regards

2021-11-17 22:03 UTC, diegonvs approved these changes
Looks good! Thanks Cley :)

2021-11-19 08:35 UTC, victorg1991 requested changes
Hey @cleydyr 

I think this fix is not valid, the default language of the field should be tied to the default language of the instance, not the user language. You can see similar behaviour in web content, when you visit the page in spanish, the default language of the field is still english.

In this case, I think the main problem is that we are not saving a value for the default language when creating the custom field. We may try to solve the problem there, showing a warning to the user, asking them to do that, or maybe an error if the default language is not provided. 

Let me know what do you think :) 

Btw, I believe expando belongs to the core infra team, I think them are the ones that have to review this in the end

2021-11-22 13:54 UTC, carloslancha commented
As @victorg1991 commented this is not a frontend infra component issue. Default language should always be the same defined in the site/instance. Please, be sure that we keep consistency about this on the implementations.

Closing this pr, if you have any question don't hesitate to contact us. Thx guys!

2021-11-22 13:54 UTC, closed without merging