LPS-141230 Test that verifies a Custom Element can be displayed in a portlet
liferay-frontend/liferay-portal pull request #1707
Opened 2021-11-29 17:58 UTC by sergiojimcos

JIRA Ticket: https://issues.liferay.com/browse/LPS-141230

**Test Scenario**:

1. Create a Custom Element Widget referencing vanilla counter custom element
2. Custom Element Widget on content page
3.  Navigate to content page
4. See the Vanilla Counter is displayed

2021-11-29 17:58 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2021-11-29 17:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/1101/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1101/jenkins-report.html">here</a>.</b></p>

2021-11-29 18:00 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ecc27fec7b8127768f87e469a4069835fb6fcb5e">ecc27fec7b8127768f87e469a4069835fb6fcb5e</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/1101/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1101/jenkins-report.html">here</a>.</h5><hr/><h4>Failures (upstream comparison is not available):</h4><ol><li><div><h5><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/1101/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre><code>A CI failure has occurred. QA Engineering has been notified. Please try again later or contact QA Engineering for an update.</code></pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-28/jobs/test-portal-acceptance-pullrequest(master)/builds/1101/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-28/jobs/test-portal-acceptance-pullrequest(master)/builds/1101/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-28/jobs/test-portal-acceptance-pullrequest(master)/builds/1101/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2021-11-30 22:22 UTC, john-co commented
ci:test:sf

2021-11-30 22:22 UTC, john-co commented
ci:test:frontend:nocompile

2021-11-30 22:22 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2021-11-30 22:23 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>frontend</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/1309/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1309/jenkins-report.html">here</a>.</b></p>

2021-11-30 22:24 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:frontend - 0 out of 1 jobs passed in 1 minute</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f4c2369db680926981b7616a89042b3ff410456c">f4c2369db680926981b7616a89042b3ff410456c</a></p><details><summary><strong>ci:test:frontend - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/1309/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1309/jenkins-report.html">here</a>.</h5><hr/><h4>Failures (upstream comparison is not available):</h4><ol><li><div><h5><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/1309/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre><code>A CI failure has occurred. QA Engineering has been notified. Please try again later or contact QA Engineering for an update.</code></pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-32/jobs/test-portal-acceptance-pullrequest(master)/builds/1309/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-32/jobs/test-portal-acceptance-pullrequest(master)/builds/1309/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-32/jobs/test-portal-acceptance-pullrequest(master)/builds/1309/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2021-11-30 22:54 UTC, john-co commented
Just started reviewing :)

2021-12-01 16:52 UTC, john-co requested changes

2021-12-01 16:52 UTC, john-co commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/remotewebapps/RemoteApps.testcase
> +    test CustomElementCanBeDisplayedByPortlet {
Make sure to use tab spacing.

2021-12-01 16:52 UTC, john-co commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/remotewebapps/RemoteApps.testcase
> +							entryURL = "${customElementURL}");
spacing is off

2021-12-01 16:52 UTC, john-co commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/remotewebapps/RemoteApps.testcase
> +							siteName = "Guest");
spacing is off

2021-12-01 16:52 UTC, john-co commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/remotewebapps/RemoteApps.testcase
> +			Click(locator1 = "//body");
this is not needed

2021-12-01 16:52 UTC, john-co commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/remotewebapps/RemoteApps.testcase
> +			AssertElementPresent(locator1 = "//${customElementHTMLName}");
Make an xpath in RemoteApps.path instead.

2021-12-01 16:52 UTC, john-co commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/remotewebapps/RemoteApps.testcase
> +				value1 = "remote-apps/body.png");
Remove for now since ocular still not working for us.

2021-12-01 16:52 UTC, john-co commented on portal-web/test/functional/com/liferay/portalweb/functions/AssertElementImage.function
> +}
Remove for now since ocular isn't working for us. :(

2021-12-01 16:53 UTC, john-co commented
Notified Calum about ocular not working, he will reach out to Kenji to discuss possible solution. Let's remove the ocular method for now. We can add that assertion back in when solution is provided.

2021-12-02 15:49 UTC, magjed4289 commented
Just started reviewing :)

2021-12-02 19:16 UTC, magjed4289 commented
Looks okay to me!

2021-12-02 22:17 UTC, john-co approved these changes

2021-12-02 22:18 UTC, john-co commented
ci:forward

2021-12-02 22:18 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-12-02 22:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/1149/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1149/jenkins-report.html">here</a>.</b></p>

2021-12-02 22:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-source-format/992/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/992/jenkins-report.html">here</a>.</b></p>

2021-12-02 22:22 UTC, john-co commented
The changes within the commit messages are a bit messy. ie: the new testcase isn't in the first commit. Please remember to organize the commit messages in future pulls. Reach out to someone if need help with it.

2021-12-02 22:23 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b7534286b84c9791bda8bc619e0d631d07f44379">b7534286b84c9791bda8bc619e0d631d07f44379</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/sergiojimcos/liferay-portal/tree/LPS-141230">LPS-141230</a><br/>Branch GIT ID: <a href="https://github.com/sergiojimcos/liferay-portal/commit/97a0323f47947b4d1f95145326e7864696ec0d48">97a0323f47947b4d1f95145326e7864696ec0d48</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-source-format/992/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/992/jenkins-report.html">here</a>.</h5></details></html>

2021-12-02 22:24 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-28.liferay.com/job/test-portal-source-format/992//consoleFull)

2021-12-02 22:24 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/110696
[Console](https://test-1-28.liferay.com/job/test-portal-source-format/992//consoleFull)

2021-12-02 22:24 UTC, closed without merging

2021-12-02 22:28 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/1149/">test-portal-acceptance-pullrequest(master)#1149</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1149/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/1707">liferay-frontend#1707</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1586804948">[master] ci:test:relevant - sergiojimcos &gt; liferay-frontend - PR#1707 - 2021-12-02[14:18:24]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/3421/">publish-testray-report#3421</a><br/></div></div>

2021-12-02 22:29 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-source-format/992/">test-portal-source-format#992</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-source-format/builds/992/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/1707">liferay-frontend#1707</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1586804957">[master] ci:test:sf - sergiojimcos &gt; liferay-frontend - PR#1707 - 2021-12-02[14:18:24]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/3422/">publish-testray-report#3422</a><br/></div></div>