LPS-143552 | Verify the Vanilla Counter remote app can be viewed in a portal instance
liferay-frontend/liferay-portal pull request #1760
Opened 2021-12-16 17:47 UTC by susanchen3

**Background**
Add test coverage for [LPS-143439](https://issues.liferay.com/browse/LPS-143439)

**Test Plan**
- Create a virtual instance
- Assert there are no console errors
- Navigate to virtual instance
- Assert Vanilla Counter is present in remote apps portlet
- Navigate back to default instance 

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-143552

2021-12-16 17:47 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2021-12-16 17:48 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/1462/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1462/jenkins-report.html">here</a>.</b></p>

2021-12-16 17:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/1269/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/1269/jenkins-report.html">here</a>.</b></p>

2021-12-16 17:52 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e9255c529cbb97d494f8331ec4527b271bc412ae">e9255c529cbb97d494f8331ec4527b271bc412ae</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/susanchen3/liferay-portal/tree/LPS-143552">LPS-143552</a><br/>Branch GIT ID: <a href="https://github.com/susanchen3/liferay-portal/commit/4cfb88b4b3ad86b694d4c43a9422614b34e75471">4cfb88b4b3ad86b694d4c43a9422614b34e75471</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/1269/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/1269/jenkins-report.html">here</a>.</h5></details></html>

2021-12-16 17:52 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/1462/">test-portal-acceptance-pullrequest(master)#1462</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1462/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/1760">liferay-frontend#1760</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1591482967">[master] ci:test:relevant - susanchen3 &gt; liferay-frontend - PR#1760 - 2021-12-16[09:48:04]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/4447/">publish-testray-report#4447</a><br/></div></div>

2021-12-16 17:53 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/1269/">test-portal-source-format#1269</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/1269/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/1760">liferay-frontend#1760</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1591482976">[master] ci:test:sf - susanchen3 &gt; liferay-frontend - PR#1760 - 2021-12-16[09:48:03]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/4170/">publish-testray-report#4170</a><br/></div></div>

2021-12-29 23:08 UTC, john-co requested changes

2021-12-29 23:08 UTC, john-co commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/remotewebapps/RemoteApps.testcase
> +			SAML.addVirtualInstances(virtualHosts = "www.able.com");
Use JSON instead for setup phase, there's HeadlessPortalInstanceAPI.addPortalInstance()

2021-12-29 23:08 UTC, john-co commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/remotewebapps/RemoteApps.testcase
> +			User.firstLoginPG();
Use Navigator.openURL(); instead, skip the sign in process and just navigate to the baseURL.

2021-12-30 18:38 UTC, susanchen3 commented
ci:test:sf

2021-12-30 18:40 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-25.liferay.com/job/test-portal-source-format/1006/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1006/jenkins-report.html">here</a>.</b></p>

2021-12-30 18:41 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5bcb0f3d3c251d608d00890d91fa0c215dc8fa28">5bcb0f3d3c251d608d00890d91fa0c215dc8fa28</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/susanchen3/liferay-portal/tree/LPS-143552">LPS-143552</a><br/>Branch GIT ID: <a href="https://github.com/susanchen3/liferay-portal/commit/aa5f865ded8522249021b0470d399e69f31b2402">aa5f865ded8522249021b0470d399e69f31b2402</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1006/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1006/jenkins-report.html">here</a>.</h5><pre><code>     [java]   at com.liferay.source.formatter.BaseSourceProcessor._performTask(BaseSourceProcessor.java:704)
     [java]   ... 7 more
     [java] Caused by: java.lang.ClassNotFoundException: org.reflections.Reflections
     [java]   at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
     [java]   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [java]   at sun.misc.Launcher\$AppClassLoader.loadClass(Launcher.java:331)
     [java]   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [java]   ... 14 more
[stopwatch] [run.batch.test.action: 1:06.347 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:555: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:695: Java returned: 1
      [get] Getting: http://test-1-25/job/test-portal-source-format/1006//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20211230104129946.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20211230104129946.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null432935838.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1782004797
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 155ms
[junitreport] Deleting: /tmp/null1782004797
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 12-30-2021 10:41:31:757 PST
[stopwatch] [run.batch.test.tear.down: 0.000 sec]</code></pre></details></html>

2021-12-30 18:43 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-25.liferay.com/job/test-portal-source-format/1006/">test-portal-source-format#1006</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/1006/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/1760">liferay-frontend#1760</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1595239499">[master] ci:test:sf - susanchen3 &gt; liferay-frontend - PR#1760 - 2021-12-30[10:39:17]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-25.liferay.com/job/publish-testray-report/3425/">publish-testray-report#3425</a><br/></div></div>

2021-12-30 18:49 UTC, susanchen3 commented
sf fixed in [#111660](https://github.com/brianchandotcom/liferay-portal/pull/111660), isnt synced yet

2021-12-30 19:44 UTC, john-co approved these changes
Looks good!

2021-12-30 20:48 UTC, susanchen3 commented
ci:test:sf

2021-12-30 20:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/1352/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/1352/jenkins-report.html">here</a>.</b></p>

2021-12-30 20:52 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1cd19229a554d86e4679b56f054d9a6bd0d408bf">1cd19229a554d86e4679b56f054d9a6bd0d408bf</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/susanchen3/liferay-portal/tree/LPS-143552">LPS-143552</a><br/>Branch GIT ID: <a href="https://github.com/susanchen3/liferay-portal/commit/aa5f865ded8522249021b0470d399e69f31b2402">aa5f865ded8522249021b0470d399e69f31b2402</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/1352/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/1352/jenkins-report.html">here</a>.</h5></details></html>

2021-12-30 20:53 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/1352/">test-portal-source-format#1352</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/1352/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/1760">liferay-frontend#1760</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1595275305">[master] ci:test:sf - susanchen3 &gt; liferay-frontend - PR#1760 - 2021-12-30[12:48:12]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/4523/">publish-testray-report#4523</a><br/></div></div>

2021-12-30 22:06 UTC, susanchen3 commented
ci:forward

2021-12-30 22:06 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2021-12-30 22:06 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2021-12-30 22:09 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-11.liferay.com/job/forward-pullrequest/283//consoleFull)

2021-12-30 22:09 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/111672
[Console](https://test-1-11.liferay.com/job/forward-pullrequest/283//consoleFull)

2021-12-30 22:10 UTC, closed without merging