LPS-148962 | Add baseline images for Clay Sample Portlet
liferay-frontend/liferay-portal pull request #1994
Opened 2022-03-09 23:31 UTC by susanchen3

**Background**
Add baseline images for ocular testing. Also had to remove buttons check because setting the window size made the portlet larger than the window size.

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-148962

2022-03-09 23:31 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2022-03-09 23:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-34.liferay.com/job/test-portal-source-format/894/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/894/jenkins-report.html">here</a>.</b></p>

2022-03-09 23:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/1316/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1316/jenkins-report.html">here</a>.</b></p>

2022-03-09 23:37 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-34.liferay.com/job/test-portal-source-format/894/">test-portal-source-format#894</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-34.liferay.com/userContent/jobs/test-portal-source-format/builds/894/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/1994">liferay-frontend#1994</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1630673017">[master] ci:test:sf - susanchen3 &gt; liferay-frontend - PR#1994 - 2022-03-09[15:32:08]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-34.liferay.com/job/publish-testray-report/3387/">publish-testray-report#3387</a><br/></div></div>

2022-03-09 23:45 UTC, susanchen3 commented
ci:test:frontend:nocompile

2022-03-09 23:45 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2022-03-09 23:46 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>frontend</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/2869/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2869/jenkins-report.html">here</a>.</b></p>

2022-03-10 00:36 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/2869/">test-portal-acceptance-pullrequest(master)#2869</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2869/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>frontend<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/1994">liferay-frontend#1994</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1630734692">[master] ci:test:frontend - susanchen3 &gt; liferay-frontend - PR#1994 - 2022-03-09[15:45:58]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/8643/">publish-testray-report#8643</a><br/></div></div>

2022-03-10 00:40 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 7 out of 7 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 8 out of 8 jobs passed in 1 hour 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/02bec99471ed706b691c92be479a34335a56614d">02bec99471ed706b691c92be479a34335a56614d</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/02bec99471ed706b691c92be479a34335a56614d">02bec99471ed706b691c92be479a34335a56614d</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3011">Acceptance Upstream DXP (master) #3011</a></p><details><summary><strong>ci:test:stable - 7 out of 7 jobs PASSED</strong></summary><details><summary><strong>7 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/38593/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/38592/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/36939/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-wildfly180-mariadb104-jdk8/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/26717/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/36053/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/36940/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/401494/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 8 out of 8 jobs PASSED</strong></summary><details><summary><strong>8 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/1316/">test-portal-acceptance-pullrequest(master)</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/38593/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/38592/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/36939/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-wildfly180-mariadb104-jdk8/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/26717/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/36053/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/36940/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/401494/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1316/jenkins-report.html">here</a>.</h5></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-33/jobs/test-portal-acceptance-pullrequest(master)/builds/1316/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-33/jobs/test-portal-acceptance-pullrequest(master)/builds/1316/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-33/jobs/test-portal-acceptance-pullrequest(master)/builds/1316/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2022-03-10 00:46 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/1316/">test-portal-acceptance-pullrequest(master)#1316</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1316/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/1994">liferay-frontend#1994</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1630734760">[master] ci:test:relevant - susanchen3 &gt; liferay-frontend - PR#1994 - 2022-03-09[15:33:02]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/3681/">publish-testray-report#3681</a><br/></div></div>

2022-03-10 01:05 UTC, susanchen3 commented
Is there a way to check on the image it produces from ci? :thinking:

2022-03-10 01:15 UTC, john-co commented
talk to CI/poshi team about this.

2022-03-22 21:37 UTC, john-co commented
Hi @susanchen3 , now that QA test writer can adjust the diff sensitivity per call from [latest poshi release](https://liferay.slack.com/archives/CD7939WBE/p1647984343758739), please do some testing to see if reducing the sensitivity to something like 80% or even 70% will work better

References to slack threads from @sergiojimcos ' analysis:
- https://liferay.slack.com/archives/C02B49LBALA/p1639746813000200?thread_ts=1639655900.003800&cid=C02B49LBALA
- https://liferay.slack.com/archives/C02B49LBALA/p1642692382011100?thread_ts=1642692373.011000&cid=C02B49LBALA

2022-03-22 21:40 UTC, john-co commented
I let poshi team know that we need the baseline and comparison image on testray. https://issues.liferay.com/browse/POSHI-316 This prob won't be ready until ~2 months from now but we can keep building out our automation and check in on the progress of that.

2022-03-24 17:35 UTC, susanchen3 commented
ci:test:sf

2022-03-24 17:37 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-3.liferay.com/job/test-portal-source-format/6369/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/6369/jenkins-report.html">here</a>.</b></p>

2022-03-24 17:39 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b21e884771de9d964e73ae4e237e9c78cbf2a7d8">b21e884771de9d964e73ae4e237e9c78cbf2a7d8</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/susanchen3/liferay-portal/tree/LPS-148962">LPS-148962</a><br/>Branch GIT ID: <a href="https://github.com/susanchen3/liferay-portal/commit/c54f6ac8fce39d43479c444586f1249a26923697">c54f6ac8fce39d43479c444586f1249a26923697</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-source-format/6369/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/6369/jenkins-report.html">here</a>.</h5></details></html>

2022-03-24 17:40 UTC, susanchen3 commented
ci:test:frontend:nocompile

2022-03-24 17:40 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2022-03-24 17:42 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-3.liferay.com/job/test-portal-source-format/6369/">test-portal-source-format#6369</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-source-format/builds/6369/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/1994">liferay-frontend#1994</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1645895957">[master] ci:test:sf - susanchen3 &gt; liferay-frontend - PR#1994 - 2022-03-24[10:35:33]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-3.liferay.com/job/publish-testray-report/2203/">publish-testray-report#2203</a><br/></div></div>

2022-03-24 18:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>frontend</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/2529/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2529/jenkins-report.html">here</a>.</b></p>

2022-03-24 19:12 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:frontend - 5 out of 5 jobs passed in 1 hour 9 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b21e884771de9d964e73ae4e237e9c78cbf2a7d8">b21e884771de9d964e73ae4e237e9c78cbf2a7d8</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/b21e884771de9d964e73ae4e237e9c78cbf2a7d8">b21e884771de9d964e73ae4e237e9c78cbf2a7d8</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3060">Acceptance Upstream DXP (master) #3060</a></p><details><summary><strong>ci:test:frontend - 5 out of 5 jobs PASSED</strong></summary><details><summary><strong>5 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/2529/">test-portal-acceptance-pullrequest(master)</a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/40936/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/36943/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/489660/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/36942/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2529/jenkins-report.html">here</a>.</h5></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-28/jobs/test-portal-acceptance-pullrequest(master)/builds/2529/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-28/jobs/test-portal-acceptance-pullrequest(master)/builds/2529/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-28/jobs/test-portal-acceptance-pullrequest(master)/builds/2529/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2022-03-24 19:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/2529/">test-portal-acceptance-pullrequest(master)#2529</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2529/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>frontend<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/1994">liferay-frontend#1994</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1645938012">[master] ci:test:frontend - susanchen3 &gt; liferay-frontend - PR#1994 - 2022-03-24[11:03:33]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/7048/">publish-testray-report#7048</a><br/></div></div>

2022-03-25 21:35 UTC, susanchen3 commented
Oh just got word from Calum that the snap folder will be renamed to baseline soon. So probably have to wait for that change to be merged before forwarding this. I can update the folder and images when that change happens.

2022-04-08 19:47 UTC, susanchen3 commented
ci:test:sf

2022-04-08 19:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/2073/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/2073/jenkins-report.html">here</a>.</b></p>

2022-04-08 19:51 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2ed14658ad928de7e6d30d2bc445fc1467e6da5c">2ed14658ad928de7e6d30d2bc445fc1467e6da5c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/susanchen3/liferay-portal/tree/LPS-148962">LPS-148962</a><br/>Branch GIT ID: <a href="https://github.com/susanchen3/liferay-portal/commit/a0d77473112276722084e135018f5a78e2aa434b">a0d77473112276722084e135018f5a78e2aa434b</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/2073/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/2073/jenkins-report.html">here</a>.</h5></details></html>

2022-04-08 19:54 UTC, susanchen3 commented
ci:test:frontend:nocompile

2022-04-08 19:54 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2022-04-08 19:54 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/2073/">test-portal-source-format#2073</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/2073/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/1994">liferay-frontend#1994</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1659255493">[master] ci:test:sf - susanchen3 &gt; liferay-frontend - PR#1994 - 2022-04-08[12:48:12]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/7411/">publish-testray-report#7411</a><br/></div></div>

2022-04-08 20:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>frontend</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/2982/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2982/jenkins-report.html">here</a>.</b></p>

2022-04-08 21:19 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:frontend - 3 out of 5 jobs passed in 1 hour 18 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0174797d13ffb46cd965cea2c2ed879a2dfe0dfa">0174797d13ffb46cd965cea2c2ed879a2dfe0dfa</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0174797d13ffb46cd965cea2c2ed879a2dfe0dfa">0174797d13ffb46cd965cea2c2ed879a2dfe0dfa</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3121">Acceptance Upstream DXP (master) #3121</a></p><details><summary><strong>ci:test:frontend - 3 out of 5 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/2982/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/44081/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li></ul></div><details><summary><strong>3 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/476061/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/476060/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/476059/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2982/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/44081/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></h5><div><h6>Job Results:</h6><p>93 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2/44081//consoleText">AXIS_VARIABLE=2 #44081</a><ol><li><div><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2/44081//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FrontendDataSet_ActionsCanBeCustomized_">LocalFile.FrontendDataSet#ActionsCanBeCustomized</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-04/test-1-31/test-portal-acceptance-pullrequest(master)/2982/functional-tomcat90-mysql57-jdk8/1/2/LocalFile.FrontendDataSet_ActionsCanBeCustomized/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-04/test-1-31/test-portal-acceptance-pullrequest(master)/2982/functional-tomcat90-mysql57-jdk8/1/2/LocalFile.FrontendDataSet_ActionsCanBeCustomized/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-04/test-1-31/test-portal-acceptance-pullrequest(master)/2982/functional-tomcat90-mysql57-jdk8/1/2/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-31/jobs/test-portal-acceptance-pullrequest(master)/builds/2982/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-31/jobs/test-portal-acceptance-pullrequest(master)/builds/2982/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-31/jobs/test-portal-acceptance-pullrequest(master)/builds/2982/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2022-04-08 21:23 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/2982/">test-portal-acceptance-pullrequest(master)#2982</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2982/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>frontend<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/1994">liferay-frontend#1994</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1659336596">[master] ci:test:frontend - susanchen3 &gt; liferay-frontend - PR#1994 - 2022-04-08[13:00:46]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/8526/">publish-testray-report#8526</a><br/></div></div>

2022-04-09 00:01 UTC, john-co commented
Just started reviewing :)

2022-04-09 00:13 UTC, john-co requested changes
Along with the macro edit, would you be able to exclude the portlet's nav tabs from the ocular baseline images? We only want to target the actual clay component contained in the tab. If we depend on extraneous elements such as the nav tab then future events such as adding more nav tabs could cause this test to unnecessarily fail.

2022-04-09 00:13 UTC, john-co commented on portal-web/test/functional/com/liferay/portalweb/macros/clay/ClaySamplePortlet.macro
> +		}
You can probably just use [StrintUtil.replace](https://github.com/liferay/liferay-qa-ee/blob/liferay-qa-docs/poshi-docs/references/pages/Methods.markdown#stringutil) to replace spaces with underscore so you can remove the if else statements. Please see link for other references to poshi methods, I know these aren't very public or easy to find...and the docs aren't maintained.

Implementation of more current methods can be found at: https://github.com/liferay/liferay-portal/blob/master/modules/test/poshi/poshi-core/src/main/java/com/liferay/poshi/core/util/StringUtil.java#L681-L701

2022-04-11 23:22 UTC, susanchen3 commented
ci:test:sf

2022-04-11 23:24 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-source-format/1877/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/1877/jenkins-report.html">here</a>.</b></p>

2022-04-11 23:25 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fed89c58466807c61ca66cb2892b546fc1a7c79d">fed89c58466807c61ca66cb2892b546fc1a7c79d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/susanchen3/liferay-portal/tree/LPS-148962">LPS-148962</a><br/>Branch GIT ID: <a href="https://github.com/susanchen3/liferay-portal/commit/a01a013cf63b1c41b20eaf49713deec1f2a55db6">a01a013cf63b1c41b20eaf49713deec1f2a55db6</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-source-format/1877/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/1877/jenkins-report.html">here</a>.</h5></details></html>

2022-04-11 23:27 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-source-format/1877/">test-portal-source-format#1877</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-source-format/builds/1877/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/1994">liferay-frontend#1994</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1661183363">[master] ci:test:sf - susanchen3 &gt; liferay-frontend - PR#1994 - 2022-04-11[16:22:55]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/6894/">publish-testray-report#6894</a><br/></div></div>

2022-04-11 23:29 UTC, susanchen3 commented
ci:test:frontend:nocompile

2022-04-11 23:29 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2022-04-11 23:30 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>frontend</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/2452/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2452/jenkins-report.html">here</a>.</b></p>

2022-04-11 23:38 UTC, susanchen3 commented
ci:stop

2022-04-11 23:40 UTC, susanchen3 commented
ci:test:frontend:nocompile

2022-04-11 23:40 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2022-04-11 23:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>frontend</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/2962/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2962/jenkins-report.html">here</a>.</b></p>

2022-04-11 23:53 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:frontend - 0 out of 1 jobs passed in 9 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fed89c58466807c61ca66cb2892b546fc1a7c79d">fed89c58466807c61ca66cb2892b546fc1a7c79d</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fed89c58466807c61ca66cb2892b546fc1a7c79d">fed89c58466807c61ca66cb2892b546fc1a7c79d</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3128">Acceptance Upstream DXP (master) #3128</a></p><details><summary><strong>ci:test:frontend - 0 out of 1 jobs PASSED</strong></summary></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2452/jenkins-report.html">here</a>.</h5></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-29/jobs/test-portal-acceptance-pullrequest(master)/builds/2452/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-29/jobs/test-portal-acceptance-pullrequest(master)/builds/2452/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-29/jobs/test-portal-acceptance-pullrequest(master)/builds/2452/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2022-04-12 00:21 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:frontend - 2 out of 5 jobs passed in 40 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fed89c58466807c61ca66cb2892b546fc1a7c79d">fed89c58466807c61ca66cb2892b546fc1a7c79d</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fed89c58466807c61ca66cb2892b546fc1a7c79d">fed89c58466807c61ca66cb2892b546fc1a7c79d</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3128">Acceptance Upstream DXP (master) #3128</a></p><details><summary><strong>ci:test:frontend - 2 out of 5 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/2962/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/41039/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/19138/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li></ul></div><details><summary><strong>2 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/41038/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/41037/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2962/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/41039/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>24 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=22/41039//consoleText">AXIS_VARIABLE=22 #41039</a><pre><code>     [exec] &gt; Task :apps:static:osgi:osgi-util:compileJava FAILED
     [exec] 
     [exec] &gt; Task :apps:static:portal-lpkg-deployer:portal-lpkg-deployer-api:autoUpdateXml SKIPPED
     [exec] &gt; Task :apps:static:portal-osgi-web:portal-osgi-web-wab-generator-api:autoUpdateXml SKIPPED
     [exec] &gt; Task :apps:portal-url-builder:portal-url-builder-api:autoUpdateXml SKIPPED
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/static/osgi/osgi-util/src/main/java/com/liferay/osgi/util/bundle/BundleStartLevelUtil.java:18: error: package com.liferay.petra.string does not exist
     [exec] import com.liferay.petra.string.StringPool;
     [exec]                                ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/static/osgi/osgi-util/src/main/java/com/liferay/osgi/util/ComponentUtil.java:17: error: package com.liferay.petra.string does not exist
     [exec] import com.liferay.petra.string.StringBundler;
     [exec]                                ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/static/osgi/osgi-util/src/main/java/com/liferay/osgi/util/ComponentUtil.java:18: error: package com.liferay.petra.string does not exist
     [exec] import com.liferay.petra.string.StringPool;
     [exec]                                ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/static/osgi/osgi-util/src/main/java/com/liferay/osgi/util/BundleUtil.java:19: error: package com.liferay.petra.string does not exist
     [exec] import com.liferay.petra.string.CharPool;
     [exec]                                ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/static/osgi/osgi-util/src/main/java/com/liferay/osgi/util/BundleUtil.java:20: error: package com.liferay.petra.string does not exist
     [exec] import com.liferay.petra.string.StringPool;
     [exec]                                ^
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/static/osgi/osgi-util/src/main/java/com/liferay/osgi/util/bundle/BundleStartLevelUtil.java:65: error: cannot find symbol
     [exec]       StringPool.BLANK);
     [exec]       ^
     [exec]   symbol:   variable StringPool
     [exec]   location: class BundleStartLevelUtil
     [exec] /opt/dev/projects/github/liferay-portal/modules/apps/static/osgi/osgi-util/src/main/java/com/liferay/osgi/util/ComponentUtil.java:52: error: cannot find symbol
     [exec]           StringPool.CLOSE_PARENTHESIS, filterString,
     [exec]           ^</code></pre></div></li></ol></div></li><li><div><h5><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/19138/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></h5><div><h6>Job Results:</h6><p>92 Tests Passed.<br/>2 Tests Failed.</p></div><ol><li><div><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1/19138//consoleText">AXIS_VARIABLE=1 #19138</a><ol><li><div><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1/19138//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ClaySmoke_CanRenderUI_">LocalFile.ClaySmoke#CanRenderUI</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-04/test-1-30/test-portal-acceptance-pullrequest(master)/2962/functional-tomcat90-mysql57-jdk8/1/1/LocalFile.ClaySmoke_CanRenderUI/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-04/test-1-30/test-portal-acceptance-pullrequest(master)/2962/functional-tomcat90-mysql57-jdk8/1/1/LocalFile.ClaySmoke_CanRenderUI/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-04/test-1-30/test-portal-acceptance-pullrequest(master)/2962/functional-tomcat90-mysql57-jdk8/1/1/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2/19138//consoleText">AXIS_VARIABLE=2 #19138</a><ol><li><div><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2/19138//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FrontendDataSet_ActionsCanBeCustomized_">LocalFile.FrontendDataSet#ActionsCanBeCustomized</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-04/test-1-30/test-portal-acceptance-pullrequest(master)/2962/functional-tomcat90-mysql57-jdk8/1/2/LocalFile.FrontendDataSet_ActionsCanBeCustomized/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-04/test-1-30/test-portal-acceptance-pullrequest(master)/2962/functional-tomcat90-mysql57-jdk8/1/2/LocalFile.FrontendDataSet_ActionsCanBeCustomized/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-04/test-1-30/test-portal-acceptance-pullrequest(master)/2962/functional-tomcat90-mysql57-jdk8/1/2/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html><h5>Test bundle downloads:</h5><ul><li><a href="h [...]

2022-04-12 00:24 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/2962/">test-portal-acceptance-pullrequest(master)#2962</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2962/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>frontend<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/1994">liferay-frontend#1994</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1661252652">[master] ci:test:frontend - susanchen3 &gt; liferay-frontend - PR#1994 - 2022-04-11[16:40:49]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/8435/">publish-testray-report#8435</a><br/></div></div>

2022-04-12 22:17 UTC, susanchen3 commented
seems to work without Navigation Bars according to my testing [here](https://github.com/susanchen3/liferay-portal/pull/28#issuecomment-1097196360).. could you try uploading your version of that image? :sweat_smile: @john-co

2022-04-22 15:44 UTC, john-co commented
Sorry I couldn't get this working on my side, I'm having issues with SetWindowSize locally. Please check with @mateusralv or other QA to try if uploading their version would work.

2022-04-23 00:06 UTC, mateusralv commented
I updated the base images and tested in this [PR](https://github.com/mateusralv/liferay-portal/pull/10) and the test passed 🟢

2022-04-25 16:24 UTC, susanchen3 commented
ci:test:frontend:nocompile

2022-04-25 16:36 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>frontend</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/2772/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2772/jenkins-report.html">here</a>.</b></p>

2022-04-25 18:19 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:frontend - 4 out of 6 jobs passed in 1 hour 43 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/3185">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1267401_2772</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/bdcb90f66b794af972dd4c635ce812b98236fbd2">bdcb90f66b794af972dd4c635ce812b98236fbd2</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f71017f9b43407a157834ee31edc16bd2b587b62">f71017f9b43407a157834ee31edc16bd2b587b62</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3184">Acceptance Upstream DXP (master) #3184</a></p><details><summary><strong>ci:test:frontend - 4 out of 6 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/2772/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/515326/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</strong></strike></a></li></ul></div><details><summary><strong>4 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/432522/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/51229/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/2</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/51230/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/51228/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2772/jenkins-report.html">here</a>.</h5><hr/><h4>This pull contains no unique failures.</h4><hr/><details><summary><strong>Failures in common with <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">acceptance upstream results</a> at f71017f9b43407a157834ee31edc16bd2b587b62:</strong></summary><ol><li><div><h5><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/515326/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></h5><div><h6>Job Results:</h6><p>94 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2/515326//consoleText">AXIS_VARIABLE=2 #515326</a><ol><li><div><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=2/515326//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FrontendDataSet_ActionsCanBeCustomized_">LocalFile.FrontendDataSet#ActionsCanBeCustomized</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2772/functional-tomcat90-mysql57-jdk8/1/2/LocalFile.FrontendDataSet_ActionsCanBeCustomized/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2772/functional-tomcat90-mysql57-jdk8/1/2/LocalFile.FrontendDataSet_ActionsCanBeCustomized/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2022-04/test-1-26/test-portal-acceptance-pullrequest(master)/2772/functional-tomcat90-mysql57-jdk8/1/2/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li></ol></details></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-26/jobs/test-portal-acceptance-pullrequest(master)/builds/2772/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-26/jobs/test-portal-acceptance-pullrequest(master)/builds/2772/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-26/jobs/test-portal-acceptance-pullrequest(master)/builds/2772/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2022-04-25 18:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/2772/">test-portal-acceptance-pullrequest(master)#2772</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2772/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>frontend<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/1994">liferay-frontend#1994</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1702857405">[master] ci:test:frontend - susanchen3 &gt; liferay-frontend - PR#1994 - 2022-04-25[09:36:14]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/7591/">publish-testray-report#7591</a><br/></div></div>

2022-04-25 18:54 UTC, susanchen3 commented
woo hoo it passed :tada: 

Thanks for the images cc: @mateusralv :) I had to replace the stickers one because [your images](https://github.com/liferay-frontend/liferay-portal/pull/1994/commits/8591da114faabf40a0ba9b7247f419216c0c5773) aren't loaded in

cc: @john-co

2022-04-25 19:32 UTC, john-co commented
Looks good to me! :sunglasses:

2022-04-25 19:32 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-04-25 19:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/130/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/130/jenkins-report.html">here</a>.</b></p>

2022-04-25 19:33 UTC, john-co commented
> I had to replace the stickers one because [your images](https://github.com/liferay-frontend/liferay-portal/pull/1994/commits/8591da114faabf40a0ba9b7247f419216c0c5773) aren't loaded in

I was going to mention too, good job catching it!

2022-04-25 19:33 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/2433/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/2433/jenkins-report.html">here</a>.</b></p>

2022-04-25 19:34 UTC, john-co approved these changes

2022-04-25 19:36 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0caed9a96d092a8244e0357f3bd42573edcb56d8">0caed9a96d092a8244e0357f3bd42573edcb56d8</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/susanchen3/liferay-portal/tree/LPS-148962">LPS-148962</a><br/>Branch GIT ID: <a href="https://github.com/susanchen3/liferay-portal/commit/8591da114faabf40a0ba9b7247f419216c0c5773">8591da114faabf40a0ba9b7247f419216c0c5773</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/2433/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/2433/jenkins-report.html">here</a>.</h5></details></html>

2022-04-25 19:37 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/2433/">test-portal-source-format#2433</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/2433/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/1994">liferay-frontend#1994</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1702950009">[master] ci:test:sf - susanchen3 &gt; liferay-frontend - PR#1994 - 2022-04-25[12:32:28]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/8761/">publish-testray-report#8761</a><br/></div></div>

2022-04-25 20:50 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 7 out of 7 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 8 out of 8 jobs passed in 1 hour 17 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0caed9a96d092a8244e0357f3bd42573edcb56d8">0caed9a96d092a8244e0357f3bd42573edcb56d8</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c7e27142b36977519972d86b966ab60c4b8dfa9a">c7e27142b36977519972d86b966ab60c4b8dfa9a</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3186">Acceptance Upstream DXP (master) #3186</a></p><details><summary><strong>ci:test:stable - 7 out of 7 jobs PASSED</strong></summary><details><summary><strong>7 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/43892/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/44570/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/44569/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-wildfly180-mariadb104-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/49677/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/488007/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/44571/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/35213/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 8 out of 8 jobs PASSED</strong></summary><details><summary><strong>8 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/130/">test-portal-acceptance-pullrequest(master)</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/43892/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/44570/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/44569/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-wildfly180-mariadb104-jdk8/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/49677/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/488007/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/1</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/44571/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/35213/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/130/jenkins-report.html">here</a>.</h5></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-38/jobs/test-portal-acceptance-pullrequest(master)/builds/130/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-38/jobs/test-portal-acceptance-pullrequest(master)/builds/130/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-38/jobs/test-portal-acceptance-pullrequest(master)/builds/130/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2022-04-25 20:50 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/130//consoleFull)

2022-04-25 20:51 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/116548
[Console](https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/130//consoleFull)

2022-04-25 20:51 UTC, closed without merging

2022-04-25 20:52 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/130/">test-portal-acceptance-pullrequest(master)#130</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/130/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/1994">liferay-frontend#1994</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1703256857">[master] ci:test:relevant - susanchen3 &gt; liferay-frontend - PR#1994 - 2022-04-25[12:32:25]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/280/">publish-testray-report#280</a><br/></div></div>