LPS-153224 | StructuredContent can be filtered with default priority
liferay-frontend/liferay-portal pull request #2232
Opened 2022-05-12 08:17 UTC by Hijky

**Background**
StructuredContent can be filtered with default priority

**Test Plan**
Given three web content is created with default priority
When with GET request I filter web content by the field priority with "/v1.0/sites/{siteId}/structured-contents"
Then you can see the web content filtered by the default in the body response

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-153224

2022-05-12 08:17 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2022-05-12 08:20 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/1240/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/1240/jenkins-report.html">here</a>.</b></p>

2022-05-12 08:21 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d5d3a9d5e7a6275cf170dfcc43ef68d63fb7009b">d5d3a9d5e7a6275cf170dfcc43ef68d63fb7009b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Hijky/liferay-portal/tree/master-LPS-153224">master-LPS-153224</a><br/>Branch GIT ID: <a href="https://github.com/Hijky/liferay-portal/commit/27d339e35a8daa21a5e48b202692d2beb95bc763">27d339e35a8daa21a5e48b202692d2beb95bc763</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/1240/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/1240/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 2 formatting issues:
     [java] 1: ./portal-web/test/functional/com/liferay/portalweb/macros/headless/journal/HeadlessWebcontentAPI.macro expected:&lt;...ntentWithPriority \{
     [java] [
     [java]     //Variables.assertDefined(parameterList = "\$\{vaule\}");
     [java] 
     [java]     var portalURL = JSONCompany.getDefaultPortalURL();
     [java] 
     [java]     var siteId = JSONGroupAPI._getGroupIdByName(
     [java]       groupName = "Guest",
     [java]       site = "true");
     [java] 
     [java]     var curl = '''
     [java]       \$\{portalURL\}/o/headless-admin-content/v1.0/sites/\$\{siteId\}/structured-contents?filter=priority%20eq%20\$\{filtervaule\} \
     [java]       -u [REDACTED]:test \
     [java]       -H accept: application/json \
     [java]       -H x-csrf-token: ECj52vq2 \
     [java]       -H Content-Type: application/json
     [java]     ''';]
     [java]     var curl = JSONCu...&gt; but was:&lt;...ntentWithPriority \{
     [java] [    // Variables.assertDefined(parameterList = "\$\{vaule\}");
     [java] 
     [java]     var portalURL = JSONCompany.getDefaultPortalURL();
     [java] 
     [java]     var siteId = JSONGroupAPI._getGroupIdByName(
     [java]       groupName = "Guest",
     [java]       site = "true");
     [java] 
     [java]     var curl = '''
     [java]       \$\{portalURL\}/o/headless-admin-content/v1.0/sites/\$\{siteId\}/structured-contents?filter=priority%20eq%20\$\{filtervaule\} \
     [java]       -u [REDACTED]:test \
     [java]       -H accept: application/json \
     [java]       -H x-csrf-token: ECj52vq2 \
     [java]       -H Content-Type: application/json
     [java]     ''';
     [java] ]
     [java]     var curl = JSONCu...&gt;
     [java] 2: ./portal-web/test/functional/com/liferay/portalweb/tests/enduser/headless/HeadlessDeliveryAPI/HeadlessDeliveryStructuredContent.testcase expected:&lt;...arDownCP();
     [java]     \}
     [java]   \}
     [java] 
     [java] [  @description = "StructuredContent can be filtered with default priority"
     [java]   @priority = "5"
     [java]   test StructuredContentContainsPriorityField \{
     [java]     property portal.acceptance = "true";
     [java] 
     [java]     task ("Given a web content are created with default priority") \{
     [java]       var ddmStructureId = WebContentStructures.getDdmStructureId(structureName = "content-structure");
     [java] 
     [java]       var responseToParse = HeadlessWebcontentAPI.createStructuredContentDraft(
     [java]         data = "&lt;p&gt;My content&lt;/p&gt;",</pre></details></html>

2022-05-12 08:23 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/1240/">test-portal-source-format#1240</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/1240/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/2232">liferay-frontend#2232</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1812380710">[master] ci:test:sf - Hijky &gt; liferay-frontend - PR#2232 - 2022-05-12[01:18:32]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/4719/">publish-testray-report#4719</a><br/></div></div>

2022-05-12 08:26 UTC, Hijky commented
ci:test:relevant

2022-05-12 08:26 UTC, Hijky commented
ci:test:sf

2022-05-12 08:31 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d5d3a9d5e7a6275cf170dfcc43ef68d63fb7009b">d5d3a9d5e7a6275cf170dfcc43ef68d63fb7009b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Hijky/liferay-portal/tree/master-LPS-153224">master-LPS-153224</a><br/>Branch GIT ID: <a href="https://github.com/Hijky/liferay-portal/commit/d70a14727b99aa7f39ee54c5b82dbc2f92199bc5">d70a14727b99aa7f39ee54c5b82dbc2f92199bc5</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-22.liferay.com/job/test-portal-source-format/6923/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-22.liferay.com/userContent/jobs/test-portal-source-format/builds/6923/jenkins-report.html">here</a>.</h5></details></html>

2022-05-12 08:34 UTC, Hijky commented
ci:test:sf

2022-05-12 08:34 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-22.liferay.com/job/test-portal-source-format/6923/">test-portal-source-format#6923</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-22.liferay.com/userContent/jobs/test-portal-source-format/builds/6923/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/2232">liferay-frontend#2232</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1812380786">[master] ci:test:sf - Hijky &gt; liferay-frontend - PR#2232 - 2022-05-12[01:27:09]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-22.liferay.com/job/publish-testray-report/1881/">publish-testray-report#1881</a><br/></div></div>

2022-05-12 08:36 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/2970/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/2970/jenkins-report.html">here</a>.</b></p>

2022-05-12 08:38 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/d5d3a9d5e7a6275cf170dfcc43ef68d63fb7009b">d5d3a9d5e7a6275cf170dfcc43ef68d63fb7009b</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Hijky/liferay-portal/tree/master-LPS-153224">master-LPS-153224</a><br/>Branch GIT ID: <a href="https://github.com/Hijky/liferay-portal/commit/da5f80e33bca3f059c5ed2c4e1e41a54ea691982">da5f80e33bca3f059c5ed2c4e1e41a54ea691982</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/2970/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/2970/jenkins-report.html">here</a>.</h5></details></html>

2022-05-12 08:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/2970/">test-portal-source-format#2970</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/2970/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/2232">liferay-frontend#2232</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1812389401">[master] ci:test:sf - Hijky &gt; liferay-frontend - PR#2232 - 2022-05-12[01:35:12]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/11010/">publish-testray-report#11010</a><br/></div></div>

2022-05-12 09:07 UTC, Hijky commented
ci:test:relevant

2022-05-12 09:21 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/3118/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3118/jenkins-report.html">here</a>.</b></p>

2022-05-12 09:28 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest(master)/3118/">test-portal-acceptance-pullrequest(master)#3118</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-28.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3118/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/2232">liferay-frontend#2232</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1812393315">[master] ci:test:relevant - Hijky &gt; liferay-frontend - PR#2232 - 2022-05-12[02:21:08]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-28.liferay.com/job/publish-testray-report/8268/">publish-testray-report#8268</a><br/></div></div>

2022-05-12 15:10 UTC, magjed4289 requested changes

2022-05-12 17:51 UTC, john-co commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/headless/HeadlessDeliveryAPI/HeadlessDeliveryStructuredContent.testcase
> +			var responseToParse = HeadlessWebcontentAPI.filterStructuredContentWithPriority(filtervaule = "0.0");
typo, change to `filtervalue`

2022-05-12 17:51 UTC, john-co commented on portal-web/test/functional/com/liferay/portalweb/macros/headless/journal/HeadlessWebcontentAPI.macro
> +		var response = HeadlessWebcontentAPI._filterStructuredContentWithPriority(filtervaule = "${filtervaule}");
typo, change to `filtervalue`

2022-05-12 17:51 UTC, john-co commented on portal-web/test/functional/com/liferay/portalweb/macros/headless/journal/HeadlessWebcontentAPI.macro
> +			${portalURL}/o/headless-admin-content/v1.0/sites/${siteId}/structured-contents?filter=priority%20eq%20${filtervaule} \
typo, change to `filtervalue`

2022-05-13 09:30 UTC, Hijky commented
ci:test:sf

2022-05-13 09:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-14.liferay.com/job/test-portal-source-format/5642/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/5642/jenkins-report.html">here</a>.</b></p>

2022-05-13 09:35 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/93720ccdbebdeb15eaa62d4d0241ab6909147ede">93720ccdbebdeb15eaa62d4d0241ab6909147ede</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Hijky/liferay-portal/tree/master-LPS-153224">master-LPS-153224</a><br/>Branch GIT ID: <a href="https://github.com/Hijky/liferay-portal/commit/a12107b71522a5fea2cb46a8c4e81c4dacf5b9e6">a12107b71522a5fea2cb46a8c4e81c4dacf5b9e6</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-14.liferay.com/job/test-portal-source-format/5642/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/5642/jenkins-report.html">here</a>.</h5></details></html>

2022-05-13 09:38 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-14.liferay.com/job/test-portal-source-format/5642/">test-portal-source-format#5642</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/5642/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/2232">liferay-frontend#2232</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1828016571">[master] ci:test:sf - Hijky &gt; liferay-frontend - PR#2232 - 2022-05-13[02:30:56]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-14.liferay.com/job/publish-testray-report/2401/">publish-testray-report#2401</a><br/></div></div>

2022-05-17 07:20 UTC, magjed4289 commented
@magjed4289 test

2022-05-17 12:37 UTC, magjed4289 requested changes

2022-05-18 14:19 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/526/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/526/jenkins-report.html">here</a>.</b></p>

2022-05-18 14:20 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-source-format/3026/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/3026/jenkins-report.html">here</a>.</b></p>

2022-05-18 14:21 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e1103d93d0d5257512c7224c06ab5c78bb4774b4">e1103d93d0d5257512c7224c06ab5c78bb4774b4</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Hijky/liferay-portal/tree/master-LPS-153224">master-LPS-153224</a><br/>Branch GIT ID: <a href="https://github.com/Hijky/liferay-portal/commit/8d623f4e72390cf75f91a105a10778400203fec6">8d623f4e72390cf75f91a105a10778400203fec6</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-source-format/3026/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/3026/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 1 formatting issues:
     [java] 1: ./portal-web/test/functional/com/liferay/portalweb/macros/headless/journal/HeadlessWebcontentAPI.macro expected:&lt;...DefaultPortalURL();
     [java] [    var siteId = JSONGroupAPI._getGroupIdByName(
     [java]       groupName = "Guest",
     [java]       site = "true");
     [java] 
     [java]     var curl = '''
     [java]       \$\{portalURL\}/o/headless-admin-content/v1.0/sites/\$\{siteId\}/structured-contents?filter=\$\{filtervalue\} \
     [java]       -u [REDACTED]:test \
     [java]       -H accept: application/json \
     [java]       -H x-csrf-token: ECj52vq2 \
     [java]       -H Content-Type: application/json
     [java]     ''';
     [java] ]
     [java]     var curl = JSONCu...&gt; but was:&lt;...DefaultPortalURL();
     [java] [
     [java]     var siteId = JSONGroupAPI._getGroupIdByName(
     [java]       groupName = "Guest",
     [java]       site = "true");
     [java] 
     [java]     var curl = '''
     [java]       \$\{portalURL\}/o/headless-admin-content/v1.0/sites/\$\{siteId\}/structured-contents?filter=\$\{filtervalue\} \
     [java]       -u [REDACTED]:test \
     [java]       -H accept: application/json \
     [java]       -H x-csrf-token: ECj52vq2 \
     [java]       -H Content-Type: application/json
     [java]     ''';]
     [java]     var curl = JSONCu...&gt;
     [java] 
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:437)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:282)
[stopwatch] [run.batch.test.action: 1:07.455 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:450: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:593: Java returned: 1
      [get] Getting: http://test-1-32/job/test-portal-source-format/3026//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20220518072140206.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20220518072140206.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null141187879.properties

merge-test-results:</pre></details></html>

2022-05-18 14:24 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-source-format/3026/">test-portal-source-format#3026</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-source-format/builds/3026/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/2232">liferay-frontend#2232</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1853011997">[master] ci:test:sf - Hijky &gt; liferay-frontend - PR#2232 - 2022-05-18[07:19:01]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/11214/">publish-testray-report#11214</a><br/></div></div>

2022-05-18 14:34 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/526/">test-portal-acceptance-pullrequest(master)#526</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/526/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/2232">liferay-frontend#2232</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1853018625">[master] ci:test:relevant - Hijky &gt; liferay-frontend - PR#2232 - 2022-05-18[07:18:58]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/1244/">publish-testray-report#1244</a><br/></div></div>

2022-05-19 01:23 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-source-format/1408/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/1408/jenkins-report.html">here</a>.</b></p>

2022-05-19 01:26 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-source-format/1408/">test-portal-source-format#1408</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-source-format/builds/1408/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/2232">liferay-frontend#2232</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1854405226">[master] ci:test:sf - Hijky &gt; liferay-frontend - PR#2232 - 2022-05-18[18:22:10]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/5520/">publish-testray-report#5520</a><br/></div></div>

2022-05-19 01:43 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/2627/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/2627/jenkins-report.html">here</a>.</b></p>

2022-05-19 01:48 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/2627/">test-portal-source-format#2627</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/2627/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/2232">liferay-frontend#2232</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1854406204">[master] ci:test:sf - Hijky &gt; liferay-frontend - PR#2232 - 2022-05-18[18:42:25]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/9751/">publish-testray-report#9751</a><br/></div></div>

2022-05-19 02:11 UTC, Hijky commented
ci:test:sf

2022-05-19 02:13 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-source-format/374/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-source-format/builds/374/jenkins-report.html">here</a>.</b></p>

2022-05-19 06:10 UTC, magjed4289 approved these changes

2022-05-19 06:11 UTC, magjed4289 commented
ci:forward

2022-05-19 06:11 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-05-19 06:11 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
`ci:test:relevant`
`ci:test:sf`

2022-05-19 06:12 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-38.liferay.com/job/forward-pullrequest/77//consoleFull)

2022-05-19 06:12 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/117683
[Console](https://test-1-38.liferay.com/job/forward-pullrequest/77//consoleFull)

2022-05-19 06:12 UTC, closed without merging