LPS-153239 | StructuredContent can be modified priority value
liferay-frontend/liferay-portal pull request #2283
Opened 2022-05-30 06:05 UTC by Hijky

**Background**
StructuredContent can be modified priority value

**Test Plan**
Given a web content is created with default priority
when edit priority value is modified to 3.0
Then the response body includes the modified priority value

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-153239

2022-05-30 06:05 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2022-05-30 06:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/875/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/875/jenkins-report.html">here</a>.</b></p>

2022-05-30 06:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-portal-source-format/4340/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/4340/jenkins-report.html">here</a>.</b></p>

2022-05-30 06:10 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/39a09a4346ea519c076c1828a5a0dda4a67c4ecb">39a09a4346ea519c076c1828a5a0dda4a67c4ecb</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Hijky/liferay-portal/tree/master-LPS-153239">master-LPS-153239</a><br/>Branch GIT ID: <a href="https://github.com/Hijky/liferay-portal/commit/b1f597ad3e6dc179aeb739f6022443d668b27153">b1f597ad3e6dc179aeb739f6022443d668b27153</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-source-format/4340/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/4340/jenkins-report.html">here</a>.</h5></details></html>

2022-05-30 06:12 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/875/">test-portal-acceptance-pullrequest(master)#875</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/875/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/2283">liferay-frontend#2283</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1864281988">[master] ci:test:relevant - Hijky &gt; liferay-frontend - PR#2283 - 2022-05-29[23:05:48]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/2057/">publish-testray-report#2057</a><br/></div></div>

2022-05-30 06:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-12.liferay.com/job/test-portal-source-format/4340/">test-portal-source-format#4340</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/4340/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/2283">liferay-frontend#2283</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1864281998">[master] ci:test:sf - Hijky &gt; liferay-frontend - PR#2283 - 2022-05-29[23:05:49]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-12.liferay.com/job/publish-testray-report/2427/">publish-testray-report#2427</a><br/></div></div>

2022-05-30 08:04 UTC, magjed4289 requested changes

2022-05-30 08:04 UTC, magjed4289 commented on portal-web/test/functional/com/liferay/portalweb/macros/headless/journal/HeadlessWebcontentAPI.macro
> +		var actualPriorityDefaultValue = JSONUtil.getWithJSONPath("${responseToParse}", "$.priority");
`assertPriorityFieldWithCorrectValue` and `assertPriorityFieldWithDefaultValue` do the same thing.
`assertPriorityFieldIsFilteredWithCorrectValue` and `assertPriorityFieldIsSortedWithCorrectValue` do the same thing. 

Let's think about how could we unify these methods

2022-05-30 12:35 UTC, magjed4289 requested changes

2022-05-30 12:35 UTC, magjed4289 commented on portal-web/test/functional/com/liferay/portalweb/macros/headless/journal/HeadlessWebcontentAPI.macro
> +		var actualPriorityDefaultValue = JSONUtil.getWithJSONPath("${responseToParse}", "$..priority");
please change to `actualPriorityValue`

2022-05-30 12:35 UTC, magjed4289 commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/headless/HeadlessAdminContentAPI/SupportContentVersioning/StructuredContentAssetPriority.testcase
>  				expectedPriorityDefaultValue = "0.0",
please change to `expectedPriorityValue` in all ocurrences

2022-05-31 06:34 UTC, magjed4289 approved these changes

2022-05-31 06:39 UTC, Hijky commented
ci:forward

2022-05-31 06:39 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-05-31 06:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/131/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/131/jenkins-report.html">here</a>.</b></p>

2022-05-31 06:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/2515/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2515/jenkins-report.html">here</a>.</b></p>

2022-05-31 06:42 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9524594e69c82009cc3876bbb2aa3b2cae474780">9524594e69c82009cc3876bbb2aa3b2cae474780</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Hijky/liferay-portal/tree/master-LPS-153239">master-LPS-153239</a><br/>Branch GIT ID: <a href="https://github.com/Hijky/liferay-portal/commit/2ed270352dfbef68900447cb8a20d79cda30a82d">2ed270352dfbef68900447cb8a20d79cda30a82d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/131/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/131/jenkins-report.html">here</a>.</h5></details></html>

2022-05-31 06:43 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-39.liferay.com/job/test-portal-source-format/131//consoleFull)

2022-05-31 06:43 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/118178
[Console](https://test-1-39.liferay.com/job/test-portal-source-format/131//consoleFull)

2022-05-31 06:43 UTC, closed without merging

2022-05-31 06:44 UTC, liferay-continuous-integration commented
This pull request already has open forwarded pull request(s):
https://github.com/brianchandotcom/liferay-portal/pull/118178

Pull request will not be forwarded to `brianchandotcom`.
[Console](https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/2515//consoleFull)

2022-05-31 06:51 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/2515/">test-portal-acceptance-pullrequest(master)#2515</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2515/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/2283">liferay-frontend#2283</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1865219204">[master] ci:test:relevant - Hijky &gt; liferay-frontend - PR#2283 - 2022-05-30[23:41:27]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/6020/">publish-testray-report#6020</a><br/></div></div>