LPS-157269 | Can get multiple ManyToMany relationship details as nested fields
liferay-frontend/liferay-portal pull request #2474
Opened 2022-07-05 02:15 UTC by Hijky

**Background**
Add a test to assert can get multiple ManyToMany relationship details as nested fields

**Test Plan**
Given university created
And Given subject created
And Given student
And Given manyToMany relationship universitySubjects created
And Given manyToMany relationship universityStudents created
And Given university entry created
And Given subject entry created
And Given student entry created
And Given in c/subjects I use PUT /{subjectId}/universitiesSubjects/{universityId}
And Given in c/students I use PUT /{studentId}/universitiesStudents/{universityId}
When I call /o/c/universities?nestedFields=universitiesSubjects,universitiesStudents
Then I receive correct information about the related objects

**JIRA Ticket**
https://issues.liferay.com/browse/LPS-157269

2022-07-05 02:15 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2022-07-05 02:15 UTC, Hijky commented
ci:test:headless-frontend-functional:nocompile

2022-07-05 02:15 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2022-07-05 02:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/3894/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3894/jenkins-report.html">here</a>.</b></p>

2022-07-05 02:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>headless-frontend-functional</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/1930/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1930/jenkins-report.html">here</a>.</b></p>

2022-07-05 02:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-source-format/2989/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/2989/jenkins-report.html">here</a>.</b></p>

2022-07-05 02:18 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5f16a4cd2b2f1fe7611530635ab79f69c9f8ac60">5f16a4cd2b2f1fe7611530635ab79f69c9f8ac60</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Hijky/liferay-portal/tree/master-LPS-157269">master-LPS-157269</a><br/>Branch GIT ID: <a href="https://github.com/Hijky/liferay-portal/commit/f10aebbadd8f76ba70f351130c270053e7519fbe">f10aebbadd8f76ba70f351130c270053e7519fbe</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-31.liferay.com/job/test-portal-source-format/2989/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/2989/jenkins-report.html">here</a>.</h5></details></html>

2022-07-05 02:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-source-format/2989/">test-portal-source-format#2989</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-source-format/builds/2989/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/2474">liferay-frontend#2474</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1896521618">[master] ci:test:sf - Hijky &gt; liferay-frontend - PR#2474 - 2022-07-04[19:15:23]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/11053/">publish-testray-report#11053</a><br/></div></div>

2022-07-05 02:24 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/3894/">test-portal-acceptance-pullrequest(master)#3894</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3894/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/2474">liferay-frontend#2474</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1896521730">[master] ci:test:relevant - Hijky &gt; liferay-frontend - PR#2474 - 2022-07-04[19:15:21]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/9968/">publish-testray-report#9968</a><br/></div></div>

2022-07-05 02:44 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:headless-frontend-functional - 6 out of 6 jobs passed in 29 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/5f16a4cd2b2f1fe7611530635ab79f69c9f8ac60">5f16a4cd2b2f1fe7611530635ab79f69c9f8ac60</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6730f3ce0bcfbbd99c4e8d1aef9f3a16cbca7019">6730f3ce0bcfbbd99c4e8d1aef9f3a16cbca7019</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3497">Acceptance Upstream DXP (master) #3497</a></p><details><summary><strong>ci:test:headless-frontend-functional - 6 out of 6 jobs PASSED</strong></summary><details><summary><strong>6 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/1930/">test-portal-acceptance-pullrequest(master)</a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/94838/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/94837/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/94836/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/94839/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/92762/">functional-tomcat90-mysql57-jdk8/0/4</a></li></ul></li></ul></details></details><h5>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1930/jenkins-report.html">here</a>.</h5></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-35/jobs/test-portal-acceptance-pullrequest(master)/builds/1930/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-35/jobs/test-portal-acceptance-pullrequest(master)/builds/1930/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-35/jobs/test-portal-acceptance-pullrequest(master)/builds/1930/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2022-07-05 02:47 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/1930/">test-portal-acceptance-pullrequest(master)#1930</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1930/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>headless-frontend-functional<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/2474">liferay-frontend#2474</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1896537518">[master] ci:test:headless-frontend-functional - Hijky &gt; liferay-frontend - PR#2474 - 2022-07-04[19:15:41]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/4772/">publish-testray-report#4772</a><br/></div></div>

2022-07-05 07:19 UTC, magjed4289 requested changes

2022-07-05 07:19 UTC, magjed4289 commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/headless/AdvancedObjectAPI/SupportManyToManyRelationships.testcase
> +			var objectDefinitionId1 = JSONObject.getObjectId(objectName = "University");
I believe declaring the University here is redundant, the line 571 should be enough.

2022-07-05 07:19 UTC, magjed4289 commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/headless/AdvancedObjectAPI/SupportManyToManyRelationships.testcase
> +
I don't see some test steps declared in the test. Are you sure you're automating the correct one?


```
Test Plan
Given university created
And Given subject created
And Given student
And Given manyToMany relationship universitySubjects created
And Given manyToMany relationship universityStudents created
And Given university entry created
And Given subject entry created
And Given student entry created
And Given in c/subjects I use PUT /{subjectId}/universitiesSubjects/{universityId}
And Given in c/students I use PUT /{studentId}/universitiesStudents/{universityId}
When I call /o/c/universities?nestedFields=universitiesSubjects,universitiesStudents
Then I receive correct information about the related objects
```

2022-07-05 07:52 UTC, magjed4289 requested changes

2022-07-05 07:52 UTC, magjed4289 commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/headless/AdvancedObjectAPI/SupportManyToManyRelationships.testcase
> +			var getObjectsWithNestedFieldReponse1 = ObjectDefinitionAPI.getObjectsWithNestedField(
this should be one call, not two. 
```
ObjectDefinitionAPI.getObjectsWithNestedField(
				nestedField = "universitiesStudents,universitiesSubjects",
				objects = "universities");
```

2022-07-06 06:59 UTC, magjed4289 approved these changes

2022-07-06 07:02 UTC, Hijky commented
ci:forward

2022-07-06 07:02 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

The pull request will automatically be forwarded to the user `brianchandotcom` if the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2022-07-06 07:03 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/1947/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1947/jenkins-report.html">here</a>.</b></p>

2022-07-06 07:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/861/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/861/jenkins-report.html">here</a>.</b></p>

2022-07-06 07:07 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/7b5a18d63e6f1f339b1f6d19b8d142060c9535d2">7b5a18d63e6f1f339b1f6d19b8d142060c9535d2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Hijky/liferay-portal/tree/master-LPS-157269">master-LPS-157269</a><br/>Branch GIT ID: <a href="https://github.com/Hijky/liferay-portal/commit/7d1ad9d891c951d0db7a6eac064578daaa1e547f">7d1ad9d891c951d0db7a6eac064578daaa1e547f</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/861/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/861/jenkins-report.html">here</a>.</h5></details></html>

2022-07-06 07:07 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-36.liferay.com/job/test-portal-source-format/861//consoleFull)

2022-07-06 07:07 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to https://github.com/brianchandotcom/liferay-portal/pull/119932
[Console](https://test-1-36.liferay.com/job/test-portal-source-format/861//consoleFull)

2022-07-06 07:07 UTC, closed without merging

2022-07-06 07:09 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/861/">test-portal-source-format#861</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/861/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/2474">liferay-frontend#2474</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1897673714">[master] ci:test:sf - Hijky &gt; liferay-frontend - PR#2474 - 2022-07-06[00:02:53]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/3488/">publish-testray-report#3488</a><br/></div></div>

2022-07-06 07:11 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest(master)/1947/">test-portal-acceptance-pullrequest(master)#1947</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-35.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1947/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/2474">liferay-frontend#2474</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1897677860">[master] ci:test:relevant - Hijky &gt; liferay-frontend - PR#2474 - 2022-07-06[00:02:49]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-35.liferay.com/job/publish-testray-report/4812/">publish-testray-report#4812</a><br/></div></div>