LPS-154730: Expose ERC in DocumentsFolder
liferay-frontend/liferay-portal pull request #2536
Opened 2022-07-18 10:06 UTC by sergiojimcos

**What is new?**
- Expose **External Reference Code** in `DocumentsFolder`.
- Endpoint implementation of `GET`,  `UPSERT ` and `DELETE` by **External Reference Code**.
- Including some tests in API part.
- Implement new exception: `DuplicateFolderExternalReferenceCode`.

## SERVICE

This PR supports some changes in DLAppService and DLFolderService to expose ERC. As well as, if two DocumentFolders has got the same ERC, `DuplicateFolderExternalReferenceCode` exception will be thrown.

## API
In the API section, this PR contains the new endpoints to operate using the ERC:

![image](https://user-images.githubusercontent.com/44723449/179489313-47772205-8b78-4070-b987-262953279214.png)

To see this new endpoint you have to follow these steps:

1. Deploy `headless-delivery-api` and `headless-delivery-impl` in this order. As well as, deploy `document-library-repository-cmis-imp`
2. Go to `/o/api`
3. Go to `DocumentsFolder`

**JIRA Ticket:**
https://issues.liferay.com/browse/LPS-154730

2022-07-18 10:06 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2022-07-18 10:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-13.liferay.com/job/test-portal-source-format/5169/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/5169/jenkins-report.html">here</a>.</b></p>

2022-07-18 10:09 UTC, sergiojimcos commented
ci:test:lima

2022-07-18 10:10 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0d82204ad29375df9fa8d20e877f1a558d2afc5a">0d82204ad29375df9fa8d20e877f1a558d2afc5a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/sergiojimcos/liferay-portal/tree/LPS-154730">LPS-154730</a><br/>Branch GIT ID: <a href="https://github.com/sergiojimcos/liferay-portal/commit/12735b10bbba9281f0d572242c77d985137729b1">12735b10bbba9281f0d572242c77d985137729b1</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-13.liferay.com/job/test-portal-source-format/5169/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/5169/jenkins-report.html">here</a>.</h5><pre>     [java] java.lang.Exception: Found 4 formatting issues:
     [java] 1: Missing copyright, see https://github.com/liferay/liferay-portal/blob/master/modules/util/source-formatter/src/main/resources/documentation/check/copyright_check.markdown: ./portal-impl/src/com/liferay/portal/upgrade/v7_4_x/UpgradeDLFolder.java (SourceCheck:CopyrightCheck)
     [java] 2: Truncated message :
     [java] ./portal-impl/src/com/liferay/portlet/documentlibrary/service/impl/DLFolderLocalServiceImpl.java expected:&lt;...Folder addFolder(
     [java]     [  long userId, long groupId, long repositoryId, boolean mountPoint,
     [java]       long parentFolderId, String name, String description,
     [java]       boolean hidden, ServiceContext serviceContext)
     [java]     throws PortalException \{
     [java] 
     [java]     return dlFolderLocalService.addFolder(
     [java]       null, userId, groupId, repositoryId, mountPoint, parentFolderId,
     [java]       name, description, hidden, serviceContext);
     [java]   \}
     [java] 
     [java]   @Override
     [java]   public DLFolder addFolder(
     [java]       String externalReferenceCode, long userId, long groupId,
     [java]       long repositoryId, boolean mountPoint, long parentFolderId,
     [java]       String name, String description, boolean hidden,
     [java]       ServiceContext serviceContext)
     [java]     throws PortalException \{
     [java] 
     [java]     // Folder
     [java] 
     [java]     User user = _userPersistence.findByPrimaryKey(userId);
     [java]     parentFolderId = getParentFolderId(
     [java]       groupId, repositoryId, parentFolderId);
     [java]     Date date = new Date();
     [java] 
     [java]     validateFolder(groupId, parentFolderId, name);
     [java] 
     [java]     long folderId = counterLocalService.increment();
     [java] 
     [java]     _validateExternalReferenceCode(externalReferenceCode, groupId);
     [java] 
     [java]     DLFolder dlFolder = dlFolderPersistence.create(folderId);
     [java] 
     [java]     dlFolder.setUuid(serviceContext.getUuid());
     [java]     dlFolder.setGroupId(groupId);
     [java]     dlFolder.setCompanyId(user.getCompanyId());
     [java]     dlFolder.setExternalReferenceCode(externalReferenceCode);
     [java]     dlFolder.setUserId(user.getUserId());
     [java]     dlFolder.setUserName(user.getFullName());
     [java]     dlFolder.setRepositoryId(repositoryId);
     [java]     dlFolder.setMountPoint(mountPoint);
     [java]     dlFolder.setParentFolderId(parentFolderId);</pre></details></html>

2022-07-18 10:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/3726/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3726/jenkins-report.html">here</a>.</b></p>

2022-07-18 10:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-13.liferay.com/job/test-portal-source-format/5169/">test-portal-source-format#5169</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/5169/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/2536">liferay-frontend#2536</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1909830723">[master] ci:test:sf - sergiojimcos &gt; liferay-frontend - PR#2536 - 2022-07-18[03:06:47]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-13.liferay.com/job/publish-testray-report/3003/">publish-testray-report#3003</a><br/></div></div>

2022-07-18 10:43 UTC, sergiojimcos commented
ci:test:sf

2022-07-18 10:43 UTC, sergiojimcos commented
ci:test:relevant

2022-07-18 10:44 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/4221/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4221/jenkins-report.html">here</a>.</b></p>

2022-07-18 10:47 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0d82204ad29375df9fa8d20e877f1a558d2afc5a">0d82204ad29375df9fa8d20e877f1a558d2afc5a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/sergiojimcos/liferay-portal/tree/LPS-154730">LPS-154730</a><br/>Branch GIT ID: <a href="https://github.com/sergiojimcos/liferay-portal/commit/2c1d4c14c07affa7d4edc39e142382458a111b23">2c1d4c14c07affa7d4edc39e142382458a111b23</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-source-format/2623/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-source-format/builds/2623/jenkins-report.html">here</a>.</h5></details></html>

2022-07-18 10:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>lima</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/1615/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1615/jenkins-report.html">here</a>.</b></p>

2022-07-18 12:31 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:lima - 622 out of 725 jobs passed in 2 hours 19 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0d82204ad29375df9fa8d20e877f1a558d2afc5a">0d82204ad29375df9fa8d20e877f1a558d2afc5a</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0d82204ad29375df9fa8d20e877f1a558d2afc5a">0d82204ad29375df9fa8d20e877f1a558d2afc5a</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3562">Acceptance Upstream DXP (master) #3562</a></p><details><summary><strong>ci:test:lima - 622 out of 725 jobs PASSED</strong></summary><div><h4>103 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/3707/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/106706/"><strike>central-requirements-jdk8/0/0</strike></a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/54481/"><strike>functional-tomcat90-mysql57-jdk8/5/4</strike></a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/48940/"><strike>functional-tomcat90-mysql57-jdk8/5/5</strike></a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/55464/"><strike>functional-tomcat90-mysql57-jdk8/5/6</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/122859/"><strike>functional-tomcat90-mysql57-jdk8/5/7</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/122992/"><strike>functional-tomcat90-mysql57-jdk8/5/22</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/106714/"><strike>functional-tomcat90-mysql57-jdk8/5/23</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/123754/"><strike>functional-tomcat90-mysql57-jdk8/7/2</strike></a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/56175/"><strike>functional-tomcat90-mysql57-jdk8/7/13</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/119926/"><strike>functional-tomcat90-mysql57-jdk8/7/14</strike></a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/43770/"><strike>functional-tomcat90-mysql57-jdk8/8/9</strike></a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/54046/"><strike>functional-tomcat90-mysql57-jdk8/8/10</strike></a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/54746/"><strike>functional-tomcat90-mysql57-jdk8/8/11</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/66842/"><strike>functional-tomcat90-mysql57-jdk8/8/12</strike></a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/46563/"><strike>functional-tomcat90-mysql57-jdk8/8/16</strike></a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53934/"><strike>functional-tomcat90-mysql57-jdk8/9/9</strike></a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/54750/"><strike>functional-tomcat90-mysql57-jdk8/9/10</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/102737/"><strike>functional-tomcat90-mysql57-jdk8/9/11</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/102738/"><strike>functional-tomcat90-mysql57-jdk8/9/12</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/106710/"><strike>functional-tomcat90-mysql57-jdk8/9/20</strike></a></li><li><a href="https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/43768/"><strike>functional-tomcat90-mysql57-jdk8/9/21</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/102736/"><strike>functional-tomcat90-mysql57-jdk8/9/22</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/90548/"><strike>functional-tomcat90-mysql57-jdk8/9/23</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/122987/"><strike>functional-tomcat90-mysql57-jdk8/9/24</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/125205/"><strike>functional-tomcat90-mysql57-jdk8/10/0</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/123730/"><strike>functional-tomcat90-mysql57-jdk8/10/1</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/129910/"><strike>functional-tomcat90-mysql57-jdk8/10/2</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/102726/"><strike>functional-tomcat90-mysql57-jdk8/10/3</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/123725/"><strike>functional-tomcat90-mysql57-jdk8/10/4</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/129905/"><strike>functional-tomcat90-mysql57-jdk8/10/5</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/123726/"><strike>functional-tomcat90-mysql57-jdk8/10/6</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/129906/"><strike>functional-tomcat90-mysql57-jdk8/10/7</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/123727/"><strike>functional-tomcat90-mysql57-jdk8/10/8</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/119221/"><strike>functional-tomcat90-mysql57-jdk8/10/9</strike></a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/51122/"><strike>functional-tomcat90-mysql57-jdk8/10/10</strike></a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/54381/"><strike>functional-tomcat90-mysql57-jdk8/10/11</strike></a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53923/"><strike>functional-tomcat90-mysql57-jdk8/10/12</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/122854/"><strike>functional-tomcat90-mysql57-jdk8/10/13</strike></a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/55460/"><strike>functional-tomcat90-mysql57-jdk8/10/14</strike></a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53924/"><strike>functional-tomcat90-mysql57-j [...]

2022-07-18 13:03 UTC, javierdearcos commented on portal-kernel/src/com/liferay/portal/kernel/repository/BaseRepositoryImpl.java
> +		return addFolder(
I think here we are calling to the same method causing and infinite loop (stack overflow)

2022-07-18 13:04 UTC, javierdearcos commented on portal-impl/src/com/liferay/portlet/documentlibrary/service/http/DLAppServiceHttp.java
> +	public static com.liferay.portal.kernel.repository.model.Folder addFolder(
Is this generated code? In that case we should put it in a commit with generated code

2022-07-18 13:04 UTC, javierdearcos commented on portal-impl/src/com/liferay/portlet/documentlibrary/service/http/DLFolderServiceHttp.java
> +	public static com.liferay.document.library.kernel.model.DLFolder addFolder(
Is this generated code? In that case we should put it in a commit with generated code

2022-07-18 13:05 UTC, javierdearcos commented on portal-kernel/src/com/liferay/document/library/kernel/service/packageinfo
> +version 6.3.0
We need to avoid mixing different things in the same commits to make the review easier. I would put this in a baseline commit

2022-07-18 13:05 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:stable - 24 out of 27 jobs passed</h3><h3>:x: ci:test:relevant - 851 out of 907 jobs passed in 2 hours 53 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0d82204ad29375df9fa8d20e877f1a558d2afc5a">0d82204ad29375df9fa8d20e877f1a558d2afc5a</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0d82204ad29375df9fa8d20e877f1a558d2afc5a">0d82204ad29375df9fa8d20e877f1a558d2afc5a</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3562">Acceptance Upstream DXP (master) #3562</a></p><details><summary><strong>ci:test:stable - 24 out of 27 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li>functional-upgrade-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/55018/"><strike>functional-upgrade-tomcat90-mysql57-jdk8_stable/0/0</strike></a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/54058/"><strike>functional-upgrade-tomcat90-mysql57-jdk8_stable/0/1</strike></a></li></ul></li><li>modules-unit-jdk8_stable<ul><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/56193/"><strike>modules-unit-jdk8_stable/0/0</strike></a></li></ul></li></ul></div><details><summary><strong>24 Successful Jobs:</strong></summary><ul><li>functional-smoke-tomcat90-mysql57-jdk8_stable<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/106734/">functional-smoke-tomcat90-mysql57-jdk8_stable/0/0</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/52356/">js-unit-jdk8/0/0</a></li></ul></li><li>modules-compile-jdk8<ul><li><a href="https://test-1-8.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/52348/">modules-compile-jdk8/0/0</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/55485/">modules-compile-jdk8/0/1</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/57711/">modules-compile-jdk8/0/2</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/123029/">modules-compile-jdk8/0/3</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/54507/">modules-compile-jdk8/0/4</a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/46082/">modules-compile-jdk8/0/5</a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/48964/">modules-compile-jdk8/0/6</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/50483/">modules-compile-jdk8/0/7</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/56195/">modules-compile-jdk8/0/8</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/48800/">modules-compile-jdk8/0/9</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/129957/">modules-compile-jdk8/0/10</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/129958/">modules-compile-jdk8/0/11</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/106726/">modules-compile-jdk8/0/12</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/123016/">modules-compile-jdk8/0/13</a></li></ul></li><li>modules-integration-mysql57-jdk8_stable<ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/102764/">modules-integration-mysql57-jdk8_stable/0/0</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/107912/">modules-integration-mysql57-jdk8_stable/0/1</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/122903/">modules-integration-mysql57-jdk8_stable/0/2</a></li></ul></li><li>pmd-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/66876/">pmd-jdk8/0/0</a></li></ul></li><li>portal-license-smoke-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/106751/">portal-license-smoke-jdk8/0/0</a></li></ul></li><li>rest-builder-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/125277/">rest-builder-jdk8/0/0</a></li></ul></li><li>service-builder-jdk8<ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/119960/">service-builder-jdk8/0/0</a></li></ul></li><li>unit-jdk8_stable<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/119275/">unit-jdk8_stable/0/0</a></li></ul></li></ul></details></details><details><summary><strong>ci:test:relevant - 851 out of 907 jobs PASSED</strong></summary><div><h4>56 Failed Jobs:</h4><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/3726/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/50487/"><strike>central-requirements-jdk8/0/0</strike></a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/122917/"><strike>functional-tomcat90-mysql57-jdk8/2/0</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/115639/"><strike>functional-tomcat90-mysql57-jdk8/2/1</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/107925/"><strike>functional-tomcat90-mysql57-jdk8/2/2</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/129983/"><strike>functional-tomcat90-mysql57-jdk8/2/3</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/123801/"><strike>functional-tomcat90-mysql57-jdk8/2/4</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/119981/"><strike>functional-tomcat90-mysql57-jdk8/2/5</strike></a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/55022/"><strike>functional-tomcat90-mysql57-jdk8/3/5</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/106748/"><strike>functional-tomcat90-mysql57-jdk8/4/9</strike></a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/54506/"><strike>functional-tomcat90-mysql57-jdk8/4/14</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/106745/"><strike>functional-tomcat90-mysql57-jdk8/13/10</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/107922/"><strike>functional-tomcat90-mysql57-jdk8/13/11</strike></a></li><li><a href="https://test-1-37.lifera [...]

2022-07-18 13:06 UTC, javierdearcos commented on portal-impl/src/com/liferay/portlet/documentlibrary/service/impl/DLAppLocalServiceImpl.java
> +		return addFolder(
Mixing addFolder changes with getFolderByExternalReferenceCode

2022-07-18 13:08 UTC, javierdearcos commented on portal-kernel/src/com/liferay/portal/kernel/repository/model/packageinfo
> +version 11.1.0
Baseilne commit

2022-07-18 13:10 UTC, javierdearcos commented on portal-impl/src/com/liferay/portal/upgrade/v7_4_x/UpgradeDLFolder.java
> +public class UpgradeDLFolder extends UpgradeProcess {
👏 👏 👏 👏 👏

2022-07-18 13:13 UTC, javierdearcos commented on modules/apps/document-library/document-library-test/src/testIntegration/java/com/liferay/document/library/service/test/DLFolderServiceTest.java
> +	@Test
I would move this commit near the services changes

2022-07-18 13:16 UTC, javierdearcos requested changes
The feature is well implemented.

I would make some changes to reorganize the commits and code included in each one. Changes in baseline, buildService, and different method implementation are mixed in some commits. Please reorder so each commit focus on one thing to make the review easier.

Also, I would move the commit where to test the services next to the services commits so this way the first commits are related with the services and the last commits are related with the API

2022-07-18 13:48 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest(master)/4221/">test-portal-acceptance-pullrequest(master)#4221</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-31.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4221/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/2536">liferay-frontend#2536</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=1909987910">[master] ci:test:relevant - sergiojimcos &gt; liferay-frontend - PR#2536 - 2022-07-18[03:44:11]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-31.liferay.com/job/publish-testray-report/11453/">publish-testray-report#11453</a><br/></div></div>

2022-07-18 13:57 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:lima - 624 out of 725 jobs passed in 3 hours 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0d82204ad29375df9fa8d20e877f1a558d2afc5a">0d82204ad29375df9fa8d20e877f1a558d2afc5a</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/0d82204ad29375df9fa8d20e877f1a558d2afc5a">0d82204ad29375df9fa8d20e877f1a558d2afc5a</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//3562">Acceptance Upstream DXP (master) #3562</a></p><details><summary><strong>ci:test:lima - 624 out of 725 jobs PASSED</strong></summary><div><h4>101 Failed Jobs:</h4><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest(master)/1615/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>central-requirements-jdk8<ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/66910/"><strike>central-requirements-jdk8/0/0</strike></a></li></ul></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/123878/"><strike>functional-tomcat90-mysql57-jdk8/5/4</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/125339/"><strike>functional-tomcat90-mysql57-jdk8/5/5</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/125340/"><strike>functional-tomcat90-mysql57-jdk8/5/6</strike></a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/54550/"><strike>functional-tomcat90-mysql57-jdk8/5/7</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/119361/"><strike>functional-tomcat90-mysql57-jdk8/5/22</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/115704/"><strike>functional-tomcat90-mysql57-jdk8/5/23</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/123887/"><strike>functional-tomcat90-mysql57-jdk8/7/2</strike></a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/109339/"><strike>functional-tomcat90-mysql57-jdk8/7/13</strike></a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/48840/"><strike>functional-tomcat90-mysql57-jdk8/7/14</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/130067/"><strike>functional-tomcat90-mysql57-jdk8/8/9</strike></a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/106806/"><strike>functional-tomcat90-mysql57-jdk8/8/10</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/115695/"><strike>functional-tomcat90-mysql57-jdk8/8/11</strike></a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/51192/"><strike>functional-tomcat90-mysql57-jdk8/8/12</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/122994/"><strike>functional-tomcat90-mysql57-jdk8/9/9</strike></a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/122986/"><strike>functional-tomcat90-mysql57-jdk8/9/10</strike></a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/54112/"><strike>functional-tomcat90-mysql57-jdk8/9/11</strike></a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/55534/"><strike>functional-tomcat90-mysql57-jdk8/9/12</strike></a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/50520/"><strike>functional-tomcat90-mysql57-jdk8/9/20</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/115699/"><strike>functional-tomcat90-mysql57-jdk8/9/21</strike></a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/50238/"><strike>functional-tomcat90-mysql57-jdk8/9/22</strike></a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/49007/"><strike>functional-tomcat90-mysql57-jdk8/9/23</strike></a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/123109/"><strike>functional-tomcat90-mysql57-jdk8/9/24</strike></a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/54105/"><strike>functional-tomcat90-mysql57-jdk8/10/0</strike></a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/56233/"><strike>functional-tomcat90-mysql57-jdk8/10/1</strike></a></li><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/49001/"><strike>functional-tomcat90-mysql57-jdk8/10/2</strike></a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/48835/"><strike>functional-tomcat90-mysql57-jdk8/10/3</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/130045/"><strike>functional-tomcat90-mysql57-jdk8/10/4</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/102822/"><strike>functional-tomcat90-mysql57-jdk8/10/5</strike></a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/53989/"><strike>functional-tomcat90-mysql57-jdk8/10/6</strike></a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/54806/"><strike>functional-tomcat90-mysql57-jdk8/10/7</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/130046/"><strike>functional-tomcat90-mysql57-jdk8/10/8</strike></a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/55525/"><strike>functional-tomcat90-mysql57-jdk8/10/9</strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/48940/"><strike>functional-tomcat90-mysql57-jdk8/10/10</strike></a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/55529/"><strike>functional-tomcat90-mysql57-jdk8/10/11</strike></a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/51009/"><strike>functional-tomcat90-mysql57-jdk8/10/12</strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/48941/"><strike>functional-tomcat90-mysql57-jdk8/10/13</strike></a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/51190/"><strike>functional-tomcat90-mysql57-jdk8/10/14</strike></a></li><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/46111/"><strike>functional-tomcat90-mysql57-jdk8/10/15</strike></a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/46618/"><strike>functional-tomcat90-mysql57-jdk8/10/16< [...]

2022-07-19 13:36 UTC, sergiojimcos commented
Closing PR because I have changed all commits to be more clearly

2022-07-19 13:36 UTC, closed without merging