LPS-183521
liferay-frontend/liferay-portal pull request #3302
Opened 2023-05-04 13:21 UTC by abhnerramos

2023-05-04 13:21 UTC, abhnerramos commented
ci:stop

2023-05-04 13:23 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/1110/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/1110/jenkins-report.html">here</a>.</b></p>

2023-05-04 13:23 UTC, abhnerramos commented
ci:test:frontend-data-set

2023-05-04 13:25 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f04033504b3aa2aec739cf7f87401b8c4ded6c0a">f04033504b3aa2aec739cf7f87401b8c4ded6c0a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/abhnerramos/liferay-portal/tree/LPS-183521">LPS-183521</a><br/>Branch GIT ID: <a href="https://github.com/abhnerramos/liferay-portal/commit/2df678018fc7edaecb07ff07a5d8d4d4fc6d76e2">2df678018fc7edaecb07ff07a5d8d4d4fc6d76e2</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/1110/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/1110/jenkins-report.html">here</a>.</h5></details></html>

2023-05-04 13:28 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/1110/">test-portal-source-format#1110</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/1110/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/3302">liferay-frontend#3302</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2290278804">[master] ci:test:sf - abhnerramos &gt; liferay-frontend - PR#3302 - 2023-05-04[06:21:45]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/3638/">publish-testray-report#3638</a><br/></div></div>

2023-05-04 14:08 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/4568/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4568/jenkins-report.html">here</a>.</b></p>

2023-05-04 14:14 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/4568/">test-portal-acceptance-pullrequest(master)#4568</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4568/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/3302">liferay-frontend#3302</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2290285387">[master] ci:test:relevant - abhnerramos &gt; liferay-frontend - PR#3302 - 2023-05-04[07:07:56]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/9987/">publish-testray-report#9987</a><br/></div></div>

2023-05-04 15:29 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:frontend-data-set - 8 out of 11 jobs passed in 1 hour 21 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f04033504b3aa2aec739cf7f87401b8c4ded6c0a">f04033504b3aa2aec739cf7f87401b8c4ded6c0a</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2ee351d367ee9d8daa74b02dd67b37f0a31eedf1">2ee351d367ee9d8daa74b02dd67b37f0a31eedf1</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2289724550">EE Development Acceptance (master) - 4503 - 2023-05-04[00:34:47]</a></p><details><summary><strong>ci:test:frontend-data-set - 8 out of 11 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest(master)/8993/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/583507/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/583506/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/583505/"><strike>functional-tomcat90-mysql57-jdk8/0/2</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/583508/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/608378/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/475935/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/521232/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/521233/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/520107/">functional-tomcat90-mysql57-jdk8/0/8</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/469395/">js-unit-jdk8/0/0</a></li></ul></li></ul></div><details><summary><strong>8 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8993/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/583506//consoleText">functional-tomcat90-mysql57-jdk8/0/1</a><ol><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/583506//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FDSEntry_WithSpecialCharacters_">LocalFile.FDSEntry#WithSpecialCharacters</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-26/test-portal-acceptance-pullrequest(master)/8993/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.FDSEntry_WithSpecialCharacters/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-26/test-portal-acceptance-pullrequest(master)/8993/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.FDSEntry_WithSpecialCharacters/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-26/test-portal-acceptance-pullrequest(master)/8993/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/583505//consoleText">functional-tomcat90-mysql57-jdk8/0/2</a><ol><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/583505//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FDSEntry_CanDeleteDataSet_">LocalFile.FDSEntry#CanDeleteDataSet</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-26/test-portal-acceptance-pullrequest(master)/8993/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.FDSEntry_CanDeleteDataSet/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-26/test-portal-acceptance-pullrequest(master)/8993/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.FDSEntry_CanDeleteDataSet/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-26/test-portal-acceptance-pullrequest(master)/8993/functional-tomcat90-mysql57-jdk8/0/2/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-26/jobs/test-portal-acceptance-pullrequest(master)/builds/8993/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-26/jobs/test-portal-acceptance-pullrequest(master)/builds/8993/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-26/jobs/test-portal-acceptance-pullrequest(master)/builds/8993/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2023-05-04 16:34 UTC, abhnerramos commented
ci:test:frontend-data-set

2023-05-04 18:39 UTC, mateusralv requested changes

2023-05-04 18:39 UTC, mateusralv commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/frontenddataset/datamanagment/FDSViews.testcase
>  		task ("Given creating a Data Set via API") {
```suggestion
		task ("Given the list of dataset entries is empty ") {
                        if (IsElementPresent(key_itemName = "", locator1 = "FrontendDataSetAdmin#TABLE_CELL")) {
				FrontendDataSetAdmin.deleteAllDatasetEntries();
			}
		}
	task ("Given creating a Data Set via API") {
	...
```

2023-05-04 19:08 UTC, abhnerramos commented
ci:test:sf

2023-05-04 19:10 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-26.liferay.com/job/test-portal-source-format/5471/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/5471/jenkins-report.html">here</a>.</b></p>

2023-05-04 19:12 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:frontend-data-set - 6 out of 11 jobs passed in 1 hour 33 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/eeb9108fccc9f76ee9d39e2b1c844978587acad2">eeb9108fccc9f76ee9d39e2b1c844978587acad2</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/2ee351d367ee9d8daa74b02dd67b37f0a31eedf1">2ee351d367ee9d8daa74b02dd67b37f0a31eedf1</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2289724550">EE Development Acceptance (master) - 4503 - 2023-05-04[00:34:47]</a></p><details><summary><strong>ci:test:frontend-data-set - 6 out of 11 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/8014/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/584132/"><strike>functional-tomcat90-mysql57-jdk8/0/0</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/559560/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/559559/"><strike>functional-tomcat90-mysql57-jdk8/0/2</strike></a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/509988/"><strike>functional-tomcat90-mysql57-jdk8/0/3</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/521820/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/559561/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/609030/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/559562/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/584133/">functional-tomcat90-mysql57-jdk8/0/8</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/609031/">js-unit-jdk8/0/0</a></li></ul></li></ul></div><details><summary><strong>6 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8014/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/584132//consoleText">functional-tomcat90-mysql57-jdk8/0/0</a><ol><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/584132//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FDSViews_CanDeleteView_">LocalFile.FDSViews#CanDeleteView</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8014/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.FDSViews_CanDeleteView/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8014/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.FDSViews_CanDeleteView/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8014/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/584132//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FDSViews_CanEditOrDeleteView_">LocalFile.FDSViews#CanEditOrDeleteView</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8014/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.FDSViews_CanEditOrDeleteView/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8014/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.FDSViews_CanEditOrDeleteView/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8014/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/584132//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FDSViews_CanEditView_">LocalFile.FDSViews#CanEditView</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8014/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.FDSViews_CanEditView/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8014/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.FDSViews_CanEditView/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8014/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li>...</li></ol></div></li><li><div><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/559560//consoleText">functional-tomcat90-mysql57-jdk8/0/1</a><ol><li><div><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/559560//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FDSEntry_WithSpecialCharacters_">LocalFile.FDSEntry#WithSpecialCharacters</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8014/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.FDSEntry_WithSpecialCharacters/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8014/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.FDSEntry_WithSpecialCharacters/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8014/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/559560//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FDSViews_CanAssertPaginationOnFDSViewsPage_">LocalFile.FDSViews#CanAssertPaginationOnFDSViewsPage</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8014/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.FDSViews_CanAssertPaginationOnFDSViewsPage/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-27/test-portal-acceptance-pullrequest(master)/8014/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.FDSViews_CanAssertPaginationOnFDSViewsPage/summary.html.gz">Poshi Summary</a> - <a href="https:// [...]

2023-05-04 19:12 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/eeb9108fccc9f76ee9d39e2b1c844978587acad2">eeb9108fccc9f76ee9d39e2b1c844978587acad2</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/abhnerramos/liferay-portal/tree/LPS-183521">LPS-183521</a><br/>Branch GIT ID: <a href="https://github.com/abhnerramos/liferay-portal/commit/0997f984e6b7d3d7538dd6bac7ed403870b62c95">0997f984e6b7d3d7538dd6bac7ed403870b62c95</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-26.liferay.com/job/test-portal-source-format/5471/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/5471/jenkins-report.html">here</a>.</h5></details></html>

2023-05-04 19:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-26.liferay.com/job/test-portal-source-format/5471/">test-portal-source-format#5471</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-26.liferay.com/userContent/jobs/test-portal-source-format/builds/5471/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/3302">liferay-frontend#3302</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2290513170">[master] ci:test:sf - abhnerramos &gt; liferay-frontend - PR#3302 - 2023-05-04[12:08:20]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-26.liferay.com/job/publish-testray-report/20910/">publish-testray-report#20910</a><br/></div></div>

2023-05-04 19:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/8014/">test-portal-acceptance-pullrequest(master)#8014</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8014/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>frontend-data-set<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/3302">liferay-frontend#3302</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2290513180">[master] ci:test:frontend-data-set - abhnerramos &gt; liferay-frontend - PR#3302 - 2023-05-04[10:38:59]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/18149/">publish-testray-report#18149</a><br/></div></div>

2023-05-04 20:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>frontend-data-set</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/11183/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11183/jenkins-report.html">here</a>.</b></p>

2023-05-04 22:31 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:frontend-data-set - 6 out of 11 jobs passed in 1 hour 50 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/4505">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1377401_11183</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/eeb9108fccc9f76ee9d39e2b1c844978587acad2">eeb9108fccc9f76ee9d39e2b1c844978587acad2</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a646f22e82da6d49ebc0b46fa9a20cb89d438cf0">a646f22e82da6d49ebc0b46fa9a20cb89d438cf0</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2290535986">EE Development Acceptance (master) - 4504 - 2023-05-04[08:43:13]</a></p><details><summary><strong>ci:test:frontend-data-set - 6 out of 11 jobs PASSED</strong></summary><div><h4>5 Failed Jobs:</h4><ul><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/11183/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/207673/"><strike>functional-tomcat90-mysql57-jdk8/0/0</strike></a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/207672/"><strike>functional-tomcat90-mysql57-jdk8/0/1</strike></a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/207671/"><strike>functional-tomcat90-mysql57-jdk8/0/2</strike></a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/207675/"><strike>functional-tomcat90-mysql57-jdk8/0/3</strike></a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/206288/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/207674/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/206287/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/207676/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/196355/">functional-tomcat90-mysql57-jdk8/0/8</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/176033/">js-unit-jdk8/0/0</a></li></ul></li></ul></div><details><summary><strong>6 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11183/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/207673//consoleText">functional-tomcat90-mysql57-jdk8/0/0</a><ol><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/207673//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FDSViews_CanDeleteView_">LocalFile.FDSViews#CanDeleteView</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-37/test-portal-acceptance-pullrequest(master)/11183/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.FDSViews_CanDeleteView/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-37/test-portal-acceptance-pullrequest(master)/11183/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.FDSViews_CanDeleteView/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-37/test-portal-acceptance-pullrequest(master)/11183/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/207673//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FDSViews_CanEditOrDeleteView_">LocalFile.FDSViews#CanEditOrDeleteView</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-37/test-portal-acceptance-pullrequest(master)/11183/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.FDSViews_CanEditOrDeleteView/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-37/test-portal-acceptance-pullrequest(master)/11183/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.FDSViews_CanEditOrDeleteView/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-37/test-portal-acceptance-pullrequest(master)/11183/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/207673//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FDSViews_CanEditView_">LocalFile.FDSViews#CanEditView</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-37/test-portal-acceptance-pullrequest(master)/11183/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.FDSViews_CanEditView/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-37/test-portal-acceptance-pullrequest(master)/11183/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.FDSViews_CanEditView/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-37/test-portal-acceptance-pullrequest(master)/11183/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li><li>...</li></ol></div></li><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/207672//consoleText">functional-tomcat90-mysql57-jdk8/0/1</a><ol><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/207672//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FDSEntry_WithSpecialCharacters_">LocalFile.FDSEntry#WithSpecialCharacters</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-37/test-portal-acceptance-pullrequest(master)/11183/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.FDSEntry_WithSpecialCharacters/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-37/test-portal-acceptance-pullrequest(master)/11183/functional-tomcat90-mysql57-jdk8/0/1/LocalFile.FDSEntry_WithSpecialCharacters/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-37/test-portal-acceptance-pullrequest(master)/11183/functional-tomcat90-mysql57-jdk8/0/1/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/207672//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_FDSViews_CanAssertPaginationOnFDSViewsPage_">LocalFile.FDSViews#CanAssertPaginationOnFDSViewsPage</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-05/test-1-37 [...]

2023-05-04 22:35 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest(master)/11183/">test-portal-acceptance-pullrequest(master)#11183</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-37.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/11183/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>frontend-data-set<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/3302">liferay-frontend#3302</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2290734977">[master] ci:test:frontend-data-set - abhnerramos &gt; liferay-frontend - PR#3302 - 2023-05-04[13:41:55]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-37.liferay.com/job/publish-testray-report/24741/">publish-testray-report#24741</a><br/></div></div>

2023-05-05 15:37 UTC, abhnerramos commented
These pushes are just to fix some accidental pushes that I did to this branch.

2023-05-09 17:14 UTC, abhnerramos commented
ci:test:frontend-data-set

2023-05-09 17:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/1171/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/1171/jenkins-report.html">here</a>.</b></p>

2023-05-09 17:18 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/56ea09f602ee231f3292ead33b58caf70c02a67d">56ea09f602ee231f3292ead33b58caf70c02a67d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/abhnerramos/liferay-portal/tree/LPS-183521">LPS-183521</a><br/>Branch GIT ID: <a href="https://github.com/abhnerramos/liferay-portal/commit/2ed21996c508d233723e103bf30eedb6575d6403">2ed21996c508d233723e103bf30eedb6575d6403</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/1171/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/1171/jenkins-report.html">here</a>.</h5></details></html>

2023-05-09 17:21 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/1171/">test-portal-source-format#1171</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/1171/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/3302">liferay-frontend#3302</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2298908377">[master] ci:test:sf - abhnerramos &gt; liferay-frontend - PR#3302 - 2023-05-09[10:14:56]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/3866/">publish-testray-report#3866</a><br/></div></div>

2023-05-09 17:58 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>frontend-data-set</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/9423/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9423/jenkins-report.html">here</a>.</b></p>

2023-05-09 19:18 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:frontend-data-set - 11 out of 11 jobs passed in 1 hour 21 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/56ea09f602ee231f3292ead33b58caf70c02a67d">56ea09f602ee231f3292ead33b58caf70c02a67d</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f2b00f52befafc0efb374cdedec9efc39b9405b7">f2b00f52befafc0efb374cdedec9efc39b9405b7</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2298836351">EE Development Acceptance (master) - 4521 - 2023-05-09[04:35:39]</a></p><details><summary><strong>ci:test:frontend-data-set - 11 out of 11 jobs PASSED</strong></summary><details><summary><strong>11 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/9423/">test-portal-acceptance-pullrequest(master)</a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/561335/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/192518/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/561334/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/369720/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/561337/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/482660/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/561336/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/214164/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/194351/">functional-tomcat90-mysql57-jdk8/0/8</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/482661/">js-unit-jdk8/0/0</a></li></ul></li></ul></details></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/9423/jenkins-report.html">here</a>.</h5></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-32/jobs/test-portal-acceptance-pullrequest(master)/builds/9423/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-32/jobs/test-portal-acceptance-pullrequest(master)/builds/9423/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-32/jobs/test-portal-acceptance-pullrequest(master)/builds/9423/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2023-05-09 19:40 UTC, abhnerramos commented
ci:test:sf

2023-05-09 19:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-36.liferay.com/job/test-portal-source-format/1880/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/1880/jenkins-report.html">here</a>.</b></p>

2023-05-09 19:44 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/56ea09f602ee231f3292ead33b58caf70c02a67d">56ea09f602ee231f3292ead33b58caf70c02a67d</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/abhnerramos/liferay-portal/tree/LPS-183521">LPS-183521</a><br/>Branch GIT ID: <a href="https://github.com/abhnerramos/liferay-portal/commit/2ed21996c508d233723e103bf30eedb6575d6403">2ed21996c508d233723e103bf30eedb6575d6403</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-36.liferay.com/job/test-portal-source-format/1880/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/1880/jenkins-report.html">here</a>.</h5></details></html>

2023-05-09 19:48 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-36.liferay.com/job/test-portal-source-format/1880/">test-portal-source-format#1880</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-36.liferay.com/userContent/jobs/test-portal-source-format/builds/1880/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/3302">liferay-frontend#3302</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2299125235">[master] ci:test:sf - abhnerramos &gt; liferay-frontend - PR#3302 - 2023-05-09[12:40:59]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-36.liferay.com/job/publish-testray-report/7652/">publish-testray-report#7652</a><br/></div></div>

2023-05-09 19:50 UTC, abhnerramos commented
@mateusralv , can you check this, please? Are there any changes to be made, or can we forward it?

2023-05-10 17:42 UTC, mateusralv approved these changes
GREAT!!!!! 🔝 🚀

2023-05-10 17:42 UTC, mateusralv commented
ci:forward

2023-05-10 17:42 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-05-10 17:42 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:relevant`
- `ci:test:sf`
- `ci:test:stable`

2023-05-10 17:43 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-39.liferay.com/job/forward-pullrequest/512//consoleFull)

2023-05-10 17:44 UTC, closed without merging

2023-05-10 17:44 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/134627
[Console](https://test-1-39.liferay.com/job/forward-pullrequest/512//consoleFull)