LPS-170286 | Refactor method to get fragment resource title properly
liferay-frontend/liferay-portal pull request #3590
Opened 2023-08-10 09:03 UTC by jaimelr10

**Descripción**: Modify method `getTitle()` from `HorizontalCardTag.java` to make same as the one in `VerticalCardTag.java` and avoid escaping lowercase **a** to **%A**
![image](https://github.com/liferay/liferay-portal/assets/40394495/d6a1ac16-06fe-4999-b67e-a329f9f2b57b)

Lima Review: https://github.com/liferay-lima/liferay-portal/pull/4573
**Jira Ticket**: https://liferay.atlassian.net/browse/LPS-170286

2023-08-10 09:03 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-08-10 09:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-portal-source-format/4592/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/4592/jenkins-report.html">here</a>.</b></p>

2023-08-10 09:27 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 3 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9b9c8fb8ca1d46ef6dab8c306728ac782a8c962f">9b9c8fb8ca1d46ef6dab8c306728ac782a8c962f</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/jaimelr10/liferay-portal/tree/LPS-170286">LPS-170286</a><br/>Branch GIT ID: <a href="https://github.com/jaimelr10/liferay-portal/commit/bbdf4773f0b6710c24bbaa241ce55d42b8a55469">bbdf4773f0b6710c24bbaa241ce55d42b8a55469</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-source-format/4592/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/4592/jenkins-report.html">here</a>.</h5></details></html>

2023-08-10 09:44 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-10.liferay.com/job/test-portal-source-format/4592/">test-portal-source-format#4592</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/4592/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/3590">liferay-frontend#3590</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2403995256">[master] ci:test:sf - jaimelr10 &gt; liferay-frontend - PR#3590 - 2023-08-10[02:24:27]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-10.liferay.com/job/publish-testray-report/4284/">publish-testray-report#4284</a><br/></div></div>

2023-08-10 10:20 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/8549/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8549/jenkins-report.html">here</a>.</b></p>

2023-08-10 11:25 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 1 hour 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/9b9c8fb8ca1d46ef6dab8c306728ac782a8c962f">9b9c8fb8ca1d46ef6dab8c306728ac782a8c962f</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ffa3ce6483f058300d4476a5580521483e51f411">ffa3ce6483f058300d4476a5580521483e51f411</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2401875504">EE Development Acceptance (master) - 4733 - 2023-08-08[12:43:32]</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/8549/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8549/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/8549/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>[beanshell]   at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
[beanshell]   at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1569)
[beanshell]   at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
[beanshell]   at com.liferay.jenkins.results.parser.JenkinsResultsParserUtil.toInputStream(JenkinsResultsParserUtil.java:4422)
[beanshell]   at com.liferay.jenkins.results.parser.JenkinsResultsParserUtil.toBufferedReader(JenkinsResultsParserUtil.java:4021)
[beanshell]   at com.liferay.jenkins.results.parser.JenkinsResultsParserUtil.toString(JenkinsResultsParserUtil.java:4761)
[beanshell]   at com.liferay.jenkins.results.parser.JenkinsResultsParserUtil.toJSONObject(JenkinsResultsParserUtil.java:4567)
[beanshell]   at com.liferay.jenkins.results.parser.JenkinsResultsParserUtil.toJSONObject(JenkinsResultsParserUtil.java:4517)
[beanshell]   at com.liferay.jenkins.results.parser.BaseBuild\$7.execute(BaseBuild.java:2910)
[beanshell]   ... 11 more
   [delete] Deleting: /opt/dev/projects/github/liferay-jenkins-ee/start.properties
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee
[stopwatch] [wait.for.invoked.jobs: 27:04.595 sec]
[beanshell] Jenkins reported generated in 202 ms
     [echo] Rsyncing Jenkins report.
[beanshell] Remote execution starting with 1 threads.
[beanshell] Executing commands: ssh -o NumberOfPasswordPrompts=0 test-1-38 'mkdir -p /opt/java/jenkins/userContent/jobs/test-portal-acceptance-pullrequest\(master\)/builds/8549/'
[beanshell] Created cache file in /tmp/jenkins-cached-files/-511866920.txt
[beanshell] Average thread duration: 226ms
[beanshell] Busy slaves:0
[beanshell] Finished slaves:1
[beanshell] Target slaves:1
[beanshell] Total duration: 227
[beanshell] Remote execution completed in 228ms.
   [delete] Deleting: /opt/dev/projects/github/liferay-jenkins-ee/commands/20230810042430078

BUILD FAILED
/opt/dev/projects/github/liferay-jenkins-ee/commands/build-common.xml:15037: Sourced file: inline evaluation of: ``                            import com.liferay.jenkins.results.parser.AutoCloseUtil;               i . . . '' : TargetError : at Line: 478 : in file: inline evaluation of: ``                            import com.liferay.jenkins.results.parser.AutoCloseUtil;               i . . . '' : throw e ; 

Target exception: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.net.SocketException: Unexpected end of file from server</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-38/jobs/test-portal-acceptance-pullrequest(master)/builds/8549/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-38/jobs/test-portal-acceptance-pullrequest(master)/builds/8549/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-38/jobs/test-portal-acceptance-pullrequest(master)/builds/8549/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2023-08-10 11:31 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest(master)/8549/">test-portal-acceptance-pullrequest(master)#8549</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-38.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8549/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/3590">liferay-frontend#3590</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2404032220">[master] ci:test:relevant - jaimelr10 &gt; liferay-frontend - PR#3590 - 2023-08-10[03:19:40]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-38.liferay.com/job/publish-testray-report/17694/">publish-testray-report#17694</a><br/></div></div>

2023-08-22 12:02 UTC, markocikos requested changes
@jaimelr10 I don't think this is the right solution. In the PR, we would be reverting API that we intentionally introduced in https://liferay.atlassian.net/browse/LPS-170287. To disable translation in the specific case of the fragment, you can disable it in the same way we are [disabling it for folder names](https://github.com/liferay/liferay-portal/blob/master/modules/apps/document-library/document-library-web/src/main/java/com/liferay/document/library/web/internal/servlet/taglib/clay/FolderHorizontalCard.java#L119-L122) in Documents and Media.

2023-09-06 06:54 UTC, jaimelr10 commented
Thank you so much @markocikos! I'll open the PR on the lima repo https://github.com/liferay-lima/liferay-portal/pull/4663 :smile:

2023-09-06 06:54 UTC, closed without merging