LPS-191371
liferay-frontend/liferay-portal pull request #3617
Opened 2023-08-24 23:33 UTC by JerryAdrianoo

2023-08-24 23:35 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/4878/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/4878/jenkins-report.html">here</a>.</b></p>

2023-08-24 23:38 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/61fba6c63943dc063d92c58d29506bffcb160d82">61fba6c63943dc063d92c58d29506bffcb160d82</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JerryAdrianoo/liferay-portal/tree/LPS-191371">LPS-191371</a><br/>Branch GIT ID: <a href="https://github.com/JerryAdrianoo/liferay-portal/commit/5c77d131f5db5e958653fa5e01ce2b3eba60ca80">5c77d131f5db5e958653fa5e01ce2b3eba60ca80</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-source-format/4878/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/4878/jenkins-report.html">here</a>.</h5></details></html>

2023-08-24 23:40 UTC, JerryAdrianoo commented
ci:test:frontend-data-set

2023-08-24 23:42 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/4878/">test-portal-source-format#4878</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/4878/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/3617">liferay-frontend#3617</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2412403528">[master] ci:test:sf - JerryAdrianoo &gt; liferay-frontend - PR#3617 - 2023-08-24[16:34:29]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/18526/">publish-testray-report#18526</a><br/></div></div>

2023-08-25 01:18 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/6943/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6943/jenkins-report.html">here</a>.</b></p>

2023-08-25 01:30 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/6943/">test-portal-acceptance-pullrequest(master)#6943</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6943/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/3617">liferay-frontend#3617</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2412465558">[master] ci:test:relevant - JerryAdrianoo &gt; liferay-frontend - PR#3617 - 2023-08-24[18:17:46]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/14174/">publish-testray-report#14174</a><br/></div></div>

2023-08-25 01:55 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>frontend-data-set</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/4289/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4289/jenkins-report.html">here</a>.</b></p>

2023-08-25 06:49 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:frontend-data-set - 26 out of 33 jobs passed in 4 hours 54 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/61fba6c63943dc063d92c58d29506bffcb160d82">61fba6c63943dc063d92c58d29506bffcb160d82</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/61fba6c63943dc063d92c58d29506bffcb160d82">61fba6c63943dc063d92c58d29506bffcb160d82</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2412503098">EE Development Acceptance (master) - 4769 - 2023-08-24[16:40:56]</a></p><details><summary><strong>ci:test:frontend-data-set - 26 out of 33 jobs PASSED</strong></summary><div><h4>7 Failed Jobs:</h4><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/4289/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/777709/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/304515/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/731773/"><strike>functional-tomcat90-mysql57-jdk8/0/2</strike></a></li><li><a href="https://test-1-28.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/622185/"><strike>functional-tomcat90-mysql57-jdk8/0/3</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/684370/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/288370/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/557668/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/288371/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/706579/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/557669/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/288366/"><strike>functional-tomcat90-mysql57-jdk8/0/10</strike></a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/731771/"><strike>functional-tomcat90-mysql57-jdk8/0/11</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/684367/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/288367/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/731772/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/304514/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/684368/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/288368/">functional-tomcat90-mysql57-jdk8/0/17</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/777609/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/557667/"><strike>functional-tomcat90-mysql57-jdk8/0/19</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/806025/">functional-tomcat90-mysql57-jdk8/0/20</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/684371/">functional-tomcat90-mysql57-jdk8/0/21</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/304517/">functional-tomcat90-mysql57-jdk8/0/22</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/731775/">functional-tomcat90-mysql57-jdk8/0/23</a></li><li><a href="https://test-1-38.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/688298/">functional-tomcat90-mysql57-jdk8/0/24</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/288369/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/684369/"><strike>functional-tomcat90-mysql57-jdk8/1/1</strike></a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/777611/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/731774/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/304516/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/706578/">functional-tomcat90-mysql57-jdk8/1/5</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/777612/">js-unit-jdk8/0/0</a></li></ul></li></ul></div><details><summary><strong>26 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4289/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/731773//consoleText">functional-tomcat90-mysql57-jdk8/0/2</a><ol><li><div><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/731773//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_DataSetViewFields_CanSelectDropdownOptions_">LocalFile.DataSetViewFields#CanSelectDropdownOptions</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-08/test-1-33/test-portal-acceptance-pullrequest(master)/4289/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.DataSetViewFields_CanSelectDropdownOptions/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-08/test-1-33/test-portal-acceptance-pullrequest(master)/4289/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.DataSetViewFields_CanSelectDropdownOptions/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-08/test-1-33/test-portal-acceptance-pullrequest(master)/4289/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.DataSetViewFields_CanSelectDropdownOptions/console.txt.gz">Poshi Console</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-08/test-1-33/test-portal-acceptance-pullrequest(master)/4289/functional-tomcat90-mysql57-jdk8/0/2/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><di [...]

2023-08-25 06:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest(master)/4289/">test-portal-acceptance-pullrequest(master)#4289</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4289/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>frontend-data-set<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/3617">liferay-frontend#3617</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2412553600">[master] ci:test:frontend-data-set - JerryAdrianoo &gt; liferay-frontend - PR#3617 - 2023-08-24[18:55:03]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/9358/">publish-testray-report#9358</a><br/></div></div>

2023-08-25 14:57 UTC, JerryAdrianoo commented
cc @CarlosBrichete. These failures are not related!

2023-08-28 09:00 UTC, CarlosBrichete requested changes

2023-08-28 09:00 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetFragment.testcase
> +			Button.clickSave();
I would create a macro to add a View to the fragment, because we probably will use this in many tests, what do you think?

2023-08-28 16:04 UTC, JerryAdrianoo commented
ci:test:frontend-data-set

2023-08-28 17:26 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>frontend-data-set</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/7983/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7983/jenkins-report.html">here</a>.</b></p>

2023-08-28 19:39 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:frontend-data-set - 26 out of 33 jobs passed in 2 hours 13 minutes</h3><details><summary>Click here for more details.</summary><br/><p>This pull is eligible for <a href="https://grow.liferay.com/share/CI+liferay-continuous-integration+GitHub+Commands#General-Commands">reevaluation</a>. When this <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)/4776">upstream build</a> has completed, using the following CI command will compare this pull request result against a more recent upstream result:<pre>ci:reevaluate:1297401_7983</pre></p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fb97b570b46d3d16f3052c80515551d7f760257e">fb97b570b46d3d16f3052c80515551d7f760257e</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8ea4420ba5d3eb2ef5d084d24d53284d1a6795d3">8ea4420ba5d3eb2ef5d084d24d53284d1a6795d3</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2413431506">EE Development Acceptance (master) - 4775 - 2023-08-26[08:38:46]</a></p><details><summary><strong>ci:test:frontend-data-set - 26 out of 33 jobs PASSED</strong></summary><div><h4>7 Failed Jobs:</h4><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/7983/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/256416/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/659807/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/667011/"><strike>functional-tomcat90-mysql57-jdk8/0/2</strike></a></li><li><a href="https://test-1-18.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/258756/"><strike>functional-tomcat90-mysql57-jdk8/0/3</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/615967/">functional-tomcat90-mysql57-jdk8/0/4</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/811018/">functional-tomcat90-mysql57-jdk8/0/5</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/736267/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/783233/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/615968/">functional-tomcat90-mysql57-jdk8/0/8</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/252700/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/783231/"><strike>functional-tomcat90-mysql57-jdk8/0/10</strike></a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/274170/"><strike>functional-tomcat90-mysql57-jdk8/0/11</strike></a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/689090/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/736266/">functional-tomcat90-mysql57-jdk8/0/13</a></li><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/293358/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/309537/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/811017/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/257862/">functional-tomcat90-mysql57-jdk8/0/17</a></li><li><a href="https://test-1-5.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/224274/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/562698/"><strike>functional-tomcat90-mysql57-jdk8/0/19</strike></a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/258695/">functional-tomcat90-mysql57-jdk8/0/20</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/689094/">functional-tomcat90-mysql57-jdk8/0/21</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/811019/">functional-tomcat90-mysql57-jdk8/0/22</a></li><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/783234/">functional-tomcat90-mysql57-jdk8/0/23</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/281269/">functional-tomcat90-mysql57-jdk8/0/24</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/689091/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/261027/"><strike>functional-tomcat90-mysql57-jdk8/1/1</strike></a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/256490/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/643200/">functional-tomcat90-mysql57-jdk8/1/3</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/261028/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/704952/">functional-tomcat90-mysql57-jdk8/1/5</a></li></ul></li><li>js-unit-jdk8<ul><li><a href="https://test-1-34.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/643202/">js-unit-jdk8/0/0</a></li></ul></li></ul></div><details><summary><strong>26 Successful Jobs:</strong></summary><ul/></details></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7983/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/667011//consoleText">functional-tomcat90-mysql57-jdk8/0/2</a><ol><li><div><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/667011//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_DataSetViewFields_CanSelectDropdownOptions_">LocalFile.DataSetViewFields#CanSelectDropdownOptions</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-08/test-1-29/test-portal-acceptance-pullrequest(master)/7983/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.DataSetViewFields_CanSelectDropdownOptions/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-08/test-1-29/test-portal-acceptance-pullrequest(master)/7983/functional-tomcat90-mysql57-jdk8/0/2/LocalFile.DataSetViewFields_CanSelectDropdownOptions/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production [...]

2023-08-28 19:42 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/7983/">test-portal-acceptance-pullrequest(master)#7983</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7983/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>frontend-data-set<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/3617">liferay-frontend#3617</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2414163085">[master] ci:test:frontend-data-set - JerryAdrianoo &gt; liferay-frontend - PR#3617 - 2023-08-28[10:26:05]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/18005/">publish-testray-report#18005</a><br/></div></div>

2023-08-30 14:08 UTC, JerryAdrianoo commented
Failures are not related!!!

2023-08-30 20:00 UTC, JerryAdrianoo commented
ci:help

2023-08-31 11:58 UTC, CarlosBrichete approved these changes
LGTM :)

2023-08-31 13:33 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-08-31 13:41 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-15.liferay.com/job/test-portal-source-format/4768/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/4768/jenkins-report.html">here</a>.</b></p>

2023-08-31 13:44 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 9 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/4bb992c726705aff28dad2bc3d1c9888abbf9a37">4bb992c726705aff28dad2bc3d1c9888abbf9a37</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JerryAdrianoo/liferay-portal/tree/LPS-191371">LPS-191371</a><br/>Branch GIT ID: <a href="https://github.com/JerryAdrianoo/liferay-portal/commit/97ba0d0cf165641d475881cf9c5d698848d6f0f1">97ba0d0cf165641d475881cf9c5d698848d6f0f1</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-15.liferay.com/job/test-portal-source-format/4768/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/4768/jenkins-report.html">here</a>.</h5></details></html>

2023-08-31 13:45 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-15.liferay.com/job/test-portal-source-format/4768//consoleFull)

2023-08-31 13:45 UTC, closed without merging

2023-08-31 13:45 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/140036
[Console](https://test-1-15.liferay.com/job/test-portal-source-format/4768//consoleFull)

2023-08-31 13:48 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-15.liferay.com/job/test-portal-source-format/4768/">test-portal-source-format#4768</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-15.liferay.com/userContent/jobs/test-portal-source-format/builds/4768/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/3617">liferay-frontend#3617</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2416430038">[master] ci:test:sf - JerryAdrianoo &gt; liferay-frontend - PR#3617 - 2023-08-31[06:36:07]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-15.liferay.com/job/publish-testray-report/4068/">publish-testray-report#4068</a><br/></div></div>

2023-08-31 15:45 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/7675/">test-portal-acceptance-pullrequest(master)#7675</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7675/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/3617">liferay-frontend#3617</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2416469482">[master] ci:test:relevant - JerryAdrianoo &gt; liferay-frontend - PR#3617 - 2023-08-31[08:38:00]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/18654/">publish-testray-report#18654</a><br/></div></div>