LPS-195333
liferay-frontend/liferay-portal pull request #3748
Opened 2023-10-12 13:20 UTC by marcosvictor22

2023-10-12 13:20 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-10-12 13:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/4331/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/4331/jenkins-report.html">here</a>.</b></p>

2023-10-12 13:45 UTC, liferay-continuous-integration commented
<h1>Unable to generate test report.</h1><p>Jenkins encountered the following error while generating test report:</p><pre><code>Sourced file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : TargetError : at Line: 86 : in file: inline evaluation of: `` 						 							import com.liferay.jenkins.results.parser.Build; 							import co . . . '' : throw e ; 

Target exception: java.lang.RuntimeException: Unable to create build anchor element. The process timed out while waiting for a build result for https://test-1-39.liferay.com/job/test-portal-source-format/4331/.
</code></pre><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/"></a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/4331/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/4331/jenkins-report.html">here</a>.</b></p>

2023-10-12 13:49 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/4331/">test-portal-source-format#4331</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/4331/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/3748">liferay-frontend#3748</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2440509224">[master] ci:test:sf - marcosvictor22 &gt; liferay-frontend - PR#3748 - 2023-10-12[06:21:04]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/16094/">publish-testray-report#16094</a><br/></div></div>

2023-10-13 07:29 UTC, dsanz commented
Hey @marcosvictor22 welcome to the team!

FYI, here in the repo, we use to provide meaningful titles to the PRs, normally, we do so by including the full LPS title/summary in the PR title, or, if the LPS is a tech task, we might use the parent task LPS title instead.

This way, just by looking at the list of PR we know, whether it's related to testing, bugfixing, tech-debt or new features.

Would you mind changing the PR title to reflect its purpose?

Thanks a lot!

2023-10-13 09:46 UTC, CarlosBrichete requested changes
Please check all my requests. @deborasoliveira maybe you can help him to understand better this automation

2023-10-13 09:46 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSet.testcase
> +        }
this should be part of the previous task, as you are just finishing the filter creation

2023-10-13 09:46 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSet.testcase
> +        }
Here you are saying that you are checking the pagination but:
1. You don't have to check the pagination, you have to check that filter is working
2. In the task you are not checking anything, you are just going to the page

Please add the assert checking the filter is present and working (Include option is selected and the preselected values are present)

2023-10-13 09:46 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSet.testcase
> +		 }
This should be another task saying that you are creating an object

2023-10-13 09:46 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSet.testcase
> +        task ("Given that the user added a Pickilist") {
this should say Picklist

2023-10-13 09:46 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSet.testcase
> +        task ("When goes to Fields Tab.") {
This should say Filters tab and also you are doing more things than just going to the Filters tab, you are creating the filter itself

2023-10-13 09:46 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSet.testcase
> +    }
Here you are saying that you are checking the pagination but:

You don't have to check the pagination, you have to check that filter is working
In the task you are not checking anything, you are just going to the page
Please add the assert checking the filter is present and working (Exclude option is selected and the preselected values are present)

2023-10-13 09:46 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSet.testcase
> +        }
Here you have to select the Exclude option

2023-10-13 09:46 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSet.testcase
> +	@description = "LPS-195333. Allow users to not use any dynamic filters defined in the dataset view in the shard"
Same here, in the description we use the LPS parent story. So in this case, this should be LPS-185995. Please change it. Also, the description is not correct. In this test we are validating that, using pre-populated values, Single mode and the option Exclude, we can see the filter in the fragment.

2023-10-13 09:46 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSet.testcase
> +    test CanViewWithoutFilters {
In this test we are validating that, using pre-populated values and the option Exclude, we can see the filter in the fragment, so the name of this test cannot be something that generic. It should be something like "CheckDynamicFilterInFragmentWithSinglePrePopulatedValueAndExclude"

2023-10-13 09:46 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSet.testcase
> +		 }
This should be another task saying that you are creating an object

2023-10-13 09:46 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSet.testcase
> +        task ("Given that the user added a Pickilist") {
This should say Picklist

2023-10-13 09:46 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSet.testcase
> +        task ("When goes to Fields Tab.") {
This should say Filters tab and also you are doing more things than just going to the Filters tab, you are creating the filter itself

2023-10-13 09:46 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSet.testcase
> +                locator1 = "CommerceEntry#RADIO_BUTTON");
This should select the Single option and then select just one pre populated value from the picklist

2023-10-13 09:46 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSet.testcase
> +        };
This should be Exclude, not include

2023-10-13 09:46 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSet.testcase
> +        }
Here you are saying that you are checking the pagination but:

You don't have to check the pagination, you have to check that filter is working
In the task you are not checking anything, you are just going to the page
Please add the assert checking the filter is present and working (Exclude option is selected and the preselected values are present)

2023-10-13 09:46 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSet.testcase
> +                locator1 = "CommerceEntry#RADIO_BUTTON");
This Commerce path has nothing to do with our test. Please use a generic button path from the Button.path file

2023-10-13 09:46 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSet.testcase
> +                locator1 = "CommerceEntry#RADIO_BUTTON");
This Commerce path has nothing to do with our test. Please use a generic button path from the Button.path file

2023-10-13 09:46 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSet.testcase
> +                locator1 = "CommerceEntry#RADIO_BUTTON");
This Commerce path has nothing to do with our test. Please use a generic button path from the Button.path file

2023-10-13 09:47 UTC, CarlosBrichete commented
@marcosvictor22 Also please add a title and a description to this PR, so anyone can have a clear vision of the purpose of this PR, thanks :)

2023-10-26 15:09 UTC, mateusralv commented
After a fats analysis I add the modifications: 
- [ ] Add the Names of the tests and the name of the test file to the jira ticket 
- [ ] Add a Description to the PR

2023-10-27 10:03 UTC, marcosvictor22 commented
ci:test:sf

2023-10-27 10:06 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-12.liferay.com/job/test-portal-source-format/5562/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/5562/jenkins-report.html">here</a>.</b></p>

2023-10-27 10:10 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/259e93090188cbf1a0ddca3d8d63a4b2d116212e">259e93090188cbf1a0ddca3d8d63a4b2d116212e</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/marcosvictor22/liferay-portal/tree/LPS-195333">LPS-195333</a><br/>Branch GIT ID: <a href="https://github.com/marcosvictor22/liferay-portal/commit/56df5c13881705146f4b349e3f9ed5358045904a">56df5c13881705146f4b349e3f9ed5358045904a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-12.liferay.com/job/test-portal-source-format/5562/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/5562/jenkins-report.html">here</a>.</h5></details></html>

2023-10-27 10:13 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-12.liferay.com/job/test-portal-source-format/5562/">test-portal-source-format#5562</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-12.liferay.com/userContent/jobs/test-portal-source-format/builds/5562/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/3748">liferay-frontend#3748</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2447837280">[master] ci:test:sf - marcosvictor22 &gt; liferay-frontend - PR#3748 - 2023-10-27[03:04:26]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-12.liferay.com/job/publish-testray-report/4270/">publish-testray-report#4270</a><br/></div></div>

2023-10-30 11:03 UTC, CarlosBrichete requested changes
Please check my requested changes

2023-10-30 11:03 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetFragmentFilters.testcase
> +				locator1 = "CommerceEntry#RADIO_BUTTON");
You should not use a Commerce path. Use a generic radio button path please

2023-10-30 11:03 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetFragmentFilters.testcase
> +				locator1 = "FormViewBuilder#OBJECT_FIELD_BUTTON_DROPDOWN");
You should not use a Form path. Use a generic dropdown path please

2023-10-30 11:03 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetFragmentFilters.testcase
> +				locator1 = "CommerceEntry#RADIO_BUTTON");
You should not use a Commerce path. Use a generic radio button path please

2023-10-30 11:03 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetFragmentFilters.testcase
> +				locator1 = "CommerceEntry#RADIO_BUTTON");
You should not use a Commerce path. Use a generic radio button path please

2023-10-30 11:03 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetFragmentFilters.testcase
> +		task ("When the user creates a field guide and goes to it") {
What's a field guide? The user is creating a dynamic filter

2023-11-22 16:29 UTC, closed without merging