LPS-184328 - Add aria-label to checkbox
liferay-frontend/liferay-portal pull request #3809
Opened 2023-11-08 10:27 UTC by Ayoub3r

### References

- [LPS-184328 Form elements don't have labels on Fields tab](https://liferay.atlassian.net/browse/LPS-184328)

### What is the goal of this PR?

The goal of this PR is to add a missing aria-label to the dataset field addition checkbox.

### What does it look like?

#### Before PR
![image (46)](https://github.com/liferay-frontend/liferay-portal/assets/141816816/806ce7c3-f855-494e-83a8-4eee387a95e1)

#### After PR
![image (47)](https://github.com/liferay-frontend/liferay-portal/assets/141816816/5874f8cf-19bd-460c-bfe4-e97b9e79e69c)

2023-11-08 10:27 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-11-08 10:34 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fadfdca50209a2a2e10f1845e1da5ec772ee682c">fadfdca50209a2a2e10f1845e1da5ec772ee682c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Ayoub3r/liferay-portal/tree/LPS-184328">LPS-184328</a><br/>Branch GIT ID: <a href="https://github.com/Ayoub3r/liferay-portal/commit/41019fc402fa1b529e081808aaed3e588feedffa">41019fc402fa1b529e081808aaed3e588feedffa</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-13.liferay.com/job/test-portal-source-format/6050/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/6050/jenkins-report.html">here</a>.</h5><pre>     [exec] warning Resolution field "@types/html-minifier-terser@5.1.0" is incompatible with requested version "@types/html-minifier-terser@^6.0.0"
     [exec] warning Resolution field "@liferay/eslint-plugin@1.5.0" is incompatible with requested version "@liferay/eslint-plugin@1.4.0"
     [exec] warning Resolution field "webpack@5.70.0" is incompatible with requested version "webpack@5.76.0"
     [exec] success Already up-to-date.
     [exec] Done in 1.49s.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat
     [exec] yarn run v1.13.0
     [exec] \$ liferay-npm-scripts check
     [exec] Generating types for 49 projects:
     [exec] &gt; 1. '@liferay/frontend-data-set-views-web' (changes detected)
     [exec] &gt; Skipped types for 1 modules. (config.build.tsc=false)
     [exec] &gt; No changes were detected for 47 other modules or their dependencies.
     [exec] apps/frontend-data-set/frontend-data-set-views-web/src/main/resources/META-INF/resources/js/fds_view/Fields.tsx: BAD
     [exec] Prettier checked 1 file, 1 file has problems
     [exec] 
     [exec] 1 of 3 jobs failed
     [exec] error Command failed with exit code 1.
     [exec] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     [exec] 
     [exec] &gt; Task :packageRunCheckFormat FAILED
     [exec] Gradle build finished at 2023-11-08 10:33:58.234.
     [exec] 
     [exec] 
     [exec] FAILURE: Build failed with an exception.
     [exec] 
     [exec] * What went wrong:
     [exec] Execution failed for task ':packageRunCheckFormat'.
     [exec] &gt; Process 'command '/opt/dev/projects/github/liferay-portal/build/node/bin/node'' finished with non-zero exit value 1
     [exec] 
     [exec] * Try:
     [exec] &gt; Run with --info or --debug option to get more log output.
     [exec] &gt; Run with --scan to get full insights.
     [exec] 
     [exec] * Exception is:
     [exec] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':packageRunCheckFormat'.
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda\$executeIfValid\$1(ExecuteActionsTaskExecuter.java:145)
     [exec]   at org.gradle.internal.Try\$Failure.ifSuccessfulOrElse(Try.java:282)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:143)
     [exec]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:131)</pre></details></html>

2023-11-08 10:41 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-13.liferay.com/job/test-portal-source-format/6050/">test-portal-source-format#6050</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/6050/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/3809">liferay-frontend#3809</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2454765815">[master] ci:test:sf - Ayoub3r &gt; liferay-frontend - PR#3809 - 2023-11-08[02:29:40]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-13.liferay.com/job/publish-testray-report/4327/">publish-testray-report#4327</a><br/></div></div>

2023-11-08 10:47 UTC, Ayoub3r commented
ci:test:sf

2023-11-08 10:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-33.liferay.com/job/test-portal-source-format/2382/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2382/jenkins-report.html">here</a>.</b></p>

2023-11-08 10:53 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fadfdca50209a2a2e10f1845e1da5ec772ee682c">fadfdca50209a2a2e10f1845e1da5ec772ee682c</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Ayoub3r/liferay-portal/tree/LPS-184328">LPS-184328</a><br/>Branch GIT ID: <a href="https://github.com/Ayoub3r/liferay-portal/commit/04d0fe0496aa6f4900bcd7ed894b2ae52ec90f9c">04d0fe0496aa6f4900bcd7ed894b2ae52ec90f9c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-33.liferay.com/job/test-portal-source-format/2382/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2382/jenkins-report.html">here</a>.</h5></details></html>

2023-11-08 10:57 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-33.liferay.com/job/test-portal-source-format/2382/">test-portal-source-format#2382</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-33.liferay.com/userContent/jobs/test-portal-source-format/builds/2382/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/3809">liferay-frontend#3809</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2454770939">[master] ci:test:sf - Ayoub3r &gt; liferay-frontend - PR#3809 - 2023-11-08[02:47:57]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-33.liferay.com/job/publish-testray-report/10142/">publish-testray-report#10142</a><br/></div></div>

2023-11-08 13:30 UTC, markocikos requested changes
@Ayoub3r please see comment inline.

2023-11-08 13:30 UTC, markocikos commented on modules/apps/frontend-data-set/frontend-data-set-views-web/src/main/resources/META-INF/resources/js/fds_view/Fields.tsx
> +										}
Neither of these language keys exist in DXP. If you look in DOM, you'll see `aria-label` resolves to `select-all-fields`. How screen reader reads this, I have no idea :slightly_smiling_face:  

You can do one of two things:
1. Use existing language keys `select-all` and `deselect-all`.
2. Add two new keys `select-all-fields` and `unselect-all-fields` to [Language.properties](https://github.com/liferay/liferay-portal/blob/master/modules/apps/portal-language/portal-language-lang/src/main/resources/content/Language.properties)

2023-11-08 13:46 UTC, Ayoub3r commented
Hey @markocikos thanks for the input, I've made sure to change it to the recommended keys in option 1.

2023-11-08 13:47 UTC, Ayoub3r commented
ci:test:sf

2023-11-08 13:49 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-source-format/6009/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/6009/jenkins-report.html">here</a>.</b></p>

2023-11-08 13:52 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/11382f29cf3c5518ce610e190287e6186e1ad1bd">11382f29cf3c5518ce610e190287e6186e1ad1bd</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Ayoub3r/liferay-portal/tree/LPS-184328">LPS-184328</a><br/>Branch GIT ID: <a href="https://github.com/Ayoub3r/liferay-portal/commit/d85c4c1cce47032291b6b3e020fce77c45d1eb8a">d85c4c1cce47032291b6b3e020fce77c45d1eb8a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-source-format/6009/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/6009/jenkins-report.html">here</a>.</h5></details></html>

2023-11-08 14:00 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-27.liferay.com/job/test-portal-source-format/6009/">test-portal-source-format#6009</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-source-format/builds/6009/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/3809">liferay-frontend#3809</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2454868223">[master] ci:test:sf - Ayoub3r &gt; liferay-frontend - PR#3809 - 2023-11-08[05:47:26]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-27.liferay.com/job/publish-testray-report/23044/">publish-testray-report#23044</a><br/></div></div>

2023-11-08 14:17 UTC, markocikos reviewed
@Ayoub3r I think we can forward this, although the solution is not ideal. There are two things that are not great:
1. We are duplicating invocation of `isSelectAllChecked`.
2. `isSelectAllChecked` itself should be wrapped in `useMemo`, as it includes O(N) filtering of fields. That's my bad, it's my code from few months ago :disappointed: 

However, we are in the middle of of replacing this component with a new one, that replaces list of checkboxes with a tree view. See https://github.com/liferay-frontend/liferay-portal/pull/3770

So, there are three things we can do here, and I'm fine with either one of them. I'll leave the choice to you:
1. We can forward this PR as it is, just to close the bug and move forward.
2. You can make a proper solution, more for personal practice then for the code value.
3. We can close the PR and the bug with "won't fix", as the issue will no longer be reproducible after [LPS-186871 Manage complex fields in dataset views](https://liferay.atlassian.net/browse/LPS-186871).

2023-11-09 11:38 UTC, markocikos requested changes
@Ayoub3r Getting close! Please see some minor stuff inline.

2023-11-09 11:38 UTC, markocikos commented on modules/apps/frontend-data-set/frontend-data-set-views-web/src/main/resources/META-INF/resources/js/fds_view/Fields.tsx
> +    const isIndeterminate = useMemo(() => isSelectAllIndeterminate(), [fields]);
`isSelectAllIndeterminate` can also be moved inline, like you did with `isSelectAllChecked`.

2023-11-09 11:38 UTC, markocikos commented on modules/apps/frontend-data-set/frontend-data-set-views-web/src/main/resources/META-INF/resources/js/fds_view/Fields.tsx
> +	const isChecked = useMemo(() => {
This variable should be `isSelectAllChecked` , because there are other checkboxes in the scope. The same for `isIndeterminate`.

2023-11-09 11:38 UTC, markocikos commented on modules/apps/frontend-data-set/frontend-data-set-views-web/src/main/resources/META-INF/resources/js/fds_view/Fields.tsx
> +	}, [fields]);
This does not seem like the whole list of dependencies. Please run `gradle formatSource`. You should run this before pushing any code.

2023-11-09 14:12 UTC, Ayoub3r commented
ci:test:sf

2023-11-09 14:15 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-11.liferay.com/job/test-portal-source-format/7541/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/7541/jenkins-report.html">here</a>.</b></p>

2023-11-09 14:18 UTC, Ayoub3r commented
@markocikos could you please take a look and tell me if there are any changes that should be made?

2023-11-09 14:18 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/ee303dbf5d7a3c23dfc86c727bb4c78ed894e749">ee303dbf5d7a3c23dfc86c727bb4c78ed894e749</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/Ayoub3r/liferay-portal/tree/LPS-184328">LPS-184328</a><br/>Branch GIT ID: <a href="https://github.com/Ayoub3r/liferay-portal/commit/391d0d4ff7ea3d5fd7efb402963a9090b11fea22">391d0d4ff7ea3d5fd7efb402963a9090b11fea22</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-11.liferay.com/job/test-portal-source-format/7541/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/7541/jenkins-report.html">here</a>.</h5></details></html>

2023-11-09 14:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-11.liferay.com/job/test-portal-source-format/7541/">test-portal-source-format#7541</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-11.liferay.com/userContent/jobs/test-portal-source-format/builds/7541/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/3809">liferay-frontend#3809</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2455754338">[master] ci:test:sf - Ayoub3r &gt; liferay-frontend - PR#3809 - 2023-11-09[06:12:57]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-11.liferay.com/job/publish-testray-report/4775/">publish-testray-report#4775</a><br/></div></div>

2023-11-09 14:42 UTC, markocikos approved these changes
@Ayoub3r LGTM! :sparkles:

2023-11-09 14:48 UTC, Ayoub3r commented
ci:forward

2023-11-09 14:48 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

The pull request will automatically be forwarded to the user `brianchandotcom` If the following test suites pass:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**stable**

2023-11-09 14:48 UTC, liferay-continuous-integration commented
Skipping previously passed test suites:
- `ci:test:sf`

2023-11-09 14:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>relevant</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/2751/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2751/jenkins-report.html">here</a>.</b></p>

2023-11-09 17:02 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/2751/">test-portal-acceptance-pullrequest(master)#2751</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/2751/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/3809">liferay-frontend#3809</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2455796341">[master] ci:test:relevant - Ayoub3r &gt; liferay-frontend - PR#3809 - 2023-11-09[06:56:55]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/28718/">publish-testray-report#28718</a><br/></div></div>

2023-11-10 19:40 UTC, mateusralv commented
Hi @Ayoub3r The failures are not Related safe to forward 😄

2023-11-13 06:43 UTC, ethib137 commented
Hey Everyone… these tickets did not follow the proper [accessibility workflow](https://liferay.atlassian.net/wiki/spaces/PEDS/pages/2195390547/How+to+report+Accessibility+Issues), so please do not forward this until the Platform Experience Team can review it. I’ll review it shortly and comment on the PR. 

In the future, please help us make sure that this workflow is followed so that we can ensure consistent fixes are applied to accessibility issues.

2023-11-13 07:33 UTC, ethib137 commented
# Fix Recommendation:

When No Items Selected:
- "Select All {ItemType} on the Page.
    - Only include "on the Page" if the list of items can include pagination. Select all only selects items on the current page not all items when multiple pages of items exist.
When All or Some Items are Selected:
- "Clear selection. There are currently 6 of 7 {ItemType} selected." 

You can review [this issue](https://liferay.atlassian.net/browse/LPS-168272) to see how this problem should be properly fixed. You can also reference the select all check box in web-content or documents and media as an example.

Please reach out in our [slack channel](https://liferay.slack.com/archives/C049XG98GQL) if you have any additional questions.

2023-11-13 11:13 UTC, ethib137 commented
Hey @markocikos , we do have a fork but the workflow we want to follow doesn't require that. We want to review these issues before any work is done. Then on the ticket we provide a fix recommendation and let the teams handle the work and code review. If they run into any questions during development, they can reach out to us, but we don't plan to review all code since we don't have the bandwidth for that.

2023-11-15 11:22 UTC, markocikos commented
@Ayoub3r @ethib137 I'm closing this PR, please see [JIRA comment](https://liferay.atlassian.net/browse/LPS-184328?focusedCommentId=2510683).

2023-11-15 11:22 UTC, closed without merging