LPS-199103
liferay-frontend/liferay-portal pull request #3859
Opened 2023-11-28 23:02 UTC by JerryAdrianoo

2023-11-28 23:02 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2023-11-28 23:02 UTC, JerryAdrianoo commented
ci:test:frontend

2023-11-28 23:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-source-format/5251/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5251/jenkins-report.html">here</a>.</b></p>

2023-11-28 23:10 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-source-format/5251/">test-portal-source-format#5251</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-source-format/builds/5251/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/3859">liferay-frontend#3859</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2467078086">[master] ci:test:sf - JerryAdrianoo &gt; liferay-frontend - PR#3859 - 2023-11-28[15:02:35]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/20211/">publish-testray-report#20211</a><br/></div></div>

2023-11-28 23:13 UTC, JerryAdrianoo commented
ci:test:sf

2023-11-28 23:13 UTC, JerryAdrianoo commented
ci:test:frontend

2023-11-28 23:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-2.liferay.com/job/test-portal-source-format/1944/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/1944/jenkins-report.html">here</a>.</b></p>

2023-11-28 23:20 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 6 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c770a8c713f5c5803378eab19295dfcec99f1940">c770a8c713f5c5803378eab19295dfcec99f1940</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JerryAdrianoo/liferay-portal/tree/LPS-199103">LPS-199103</a><br/>Branch GIT ID: <a href="https://github.com/JerryAdrianoo/liferay-portal/commit/a34408979f4382d684ad7843535b03d2eb4db4f3">a34408979f4382d684ad7843535b03d2eb4db4f3</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-2.liferay.com/job/test-portal-source-format/1944/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/1944/jenkins-report.html">here</a>.</h5></details></html>

2023-11-28 23:24 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-2.liferay.com/job/test-portal-source-format/1944/">test-portal-source-format#1944</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-source-format/builds/1944/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/3859">liferay-frontend#3859</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2467078178">[master] ci:test:sf - JerryAdrianoo &gt; liferay-frontend - PR#3859 - 2023-11-28[15:14:11]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-2.liferay.com/job/publish-testray-report/4470/">publish-testray-report#4470</a><br/></div></div>

2023-11-29 00:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>frontend</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/10882/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10882/jenkins-report.html">here</a>.</b></p>

2023-11-29 00:09 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:frontend - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c770a8c713f5c5803378eab19295dfcec99f1940">c770a8c713f5c5803378eab19295dfcec99f1940</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f5f7c2d638708fe438ed85b7acaf3d419ac1e6bc">f5f7c2d638708fe438ed85b7acaf3d419ac1e6bc</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2467060415">EE Development Acceptance (master) - 203 - 2023-11-28[08:42:12]</a></p><details><summary><strong>ci:test:frontend - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/4362/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-25.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/4362/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-25.liferay.com/job/test-portal-acceptance-pullrequest(master)/4362/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><div><p>The sender branch SHA could not be found on <strong><a href="https://github.com/liferay-frontend/liferay-portal/pull/3859">JerryAdrianoo/LPS-199103</a></strong>. The sender branch may have been force pushed or deleted after the pull request test was initiated.</p><pre>fatal: Not a valid branch point: 'adfc4c43084a2ac634e19613e9dc10a42b4329f9'.</pre></div></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-25/jobs/test-portal-acceptance-pullrequest(master)/builds/4362/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-25/jobs/test-portal-acceptance-pullrequest(master)/builds/4362/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-25/jobs/test-portal-acceptance-pullrequest(master)/builds/4362/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2023-11-29 00:42 UTC, JerryAdrianoo commented
ci:stop

2023-11-29 00:42 UTC, JerryAdrianoo commented
ci:test:frontend

2023-11-29 00:42 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:frontend - 0 out of 1 jobs passed in 38 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c770a8c713f5c5803378eab19295dfcec99f1940">c770a8c713f5c5803378eab19295dfcec99f1940</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f5f7c2d638708fe438ed85b7acaf3d419ac1e6bc">f5f7c2d638708fe438ed85b7acaf3d419ac1e6bc</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2467060415">EE Development Acceptance (master) - 203 - 2023-11-28[08:42:12]</a></p><details><summary><strong>ci:test:frontend - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/10882/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-27.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/10882/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest(master)/10882/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre>Build was aborted</pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html><h5>Test bundle downloads:</h5><ul><li><a href="https://files.liferay.com/private/bundles/test-1-27/jobs/test-portal-acceptance-pullrequest(master)/builds/10882/liferay-portal-bundle-tomcat.tar.gz">liferay-portal-bundle-tomcat.tar.gz</a> (mirrors: <a href="http://mirrors.dlc.liferay.com/files.liferay.com/private/bundles/test-1-27/jobs/test-portal-acceptance-pullrequest(master)/builds/10882/liferay-portal-bundle-tomcat.tar.gz">dlc</a>, <a href="http://mirrors.lax.liferay.com/files.liferay.com/private/bundles/test-1-27/jobs/test-portal-acceptance-pullrequest(master)/builds/10882/liferay-portal-bundle-tomcat.tar.gz">lax</a>)</li></ul>

2023-11-29 01:20 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>frontend</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/7680/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7680/jenkins-report.html">here</a>.</b></p>

2023-11-29 04:06 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:frontend - 78 out of 98 jobs passed in 2 hours 46 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c770a8c713f5c5803378eab19295dfcec99f1940">c770a8c713f5c5803378eab19295dfcec99f1940</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c770a8c713f5c5803378eab19295dfcec99f1940">c770a8c713f5c5803378eab19295dfcec99f1940</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2467119859">EE Development Acceptance (master) - 204 - 2023-11-28[12:39:48]</a></p><details><summary><strong>ci:test:frontend - 78 out of 98 jobs PASSED</strong></summary><div><h4>20 Failed Jobs:</h4><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/7680/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/303943/">functional-tomcat90-mysql57-jdk8/0/0</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/772250/">functional-tomcat90-mysql57-jdk8/0/1</a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/738731/">functional-tomcat90-mysql57-jdk8/0/2</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/307102/">functional-tomcat90-mysql57-jdk8/0/3</a></li><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/847985/"><strike>functional-tomcat90-mysql57-jdk8/0/4</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/841537/"><strike>functional-tomcat90-mysql57-jdk8/0/5</strike></a></li><li><a href="https://test-1-35.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/738732/">functional-tomcat90-mysql57-jdk8/0/6</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/828501/">functional-tomcat90-mysql57-jdk8/0/7</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/772251/"><strike>functional-tomcat90-mysql57-jdk8/0/8</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/469688/">functional-tomcat90-mysql57-jdk8/0/9</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/307098/">functional-tomcat90-mysql57-jdk8/0/10</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/325352/">functional-tomcat90-mysql57-jdk8/0/11</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/325353/">functional-tomcat90-mysql57-jdk8/0/12</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/307099/"><strike>functional-tomcat90-mysql57-jdk8/0/13</strike></a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/325354/">functional-tomcat90-mysql57-jdk8/0/14</a></li><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/307100/">functional-tomcat90-mysql57-jdk8/0/15</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/873109/">functional-tomcat90-mysql57-jdk8/0/16</a></li><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/356412/">functional-tomcat90-mysql57-jdk8/0/17</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/319675/">functional-tomcat90-mysql57-jdk8/0/18</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/828504/">functional-tomcat90-mysql57-jdk8/0/19</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/310289/">functional-tomcat90-mysql57-jdk8/0/20</a></li><li><a href="https://test-1-31.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/873110/">functional-tomcat90-mysql57-jdk8/0/21</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/325359/">functional-tomcat90-mysql57-jdk8/0/22</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/715546/">functional-tomcat90-mysql57-jdk8/0/23</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/957323/">functional-tomcat90-mysql57-jdk8/0/24</a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/325356/">functional-tomcat90-mysql57-jdk8/1/0</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/828498/">functional-tomcat90-mysql57-jdk8/1/1</a></li><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/828499/">functional-tomcat90-mysql57-jdk8/1/2</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/683197/"><strike>functional-tomcat90-mysql57-jdk8/1/3</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/715540/">functional-tomcat90-mysql57-jdk8/1/4</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/841534/">functional-tomcat90-mysql57-jdk8/1/5</a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/683198/">functional-tomcat90-mysql57-jdk8/1/6</a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/715541/">functional-tomcat90-mysql57-jdk8/1/7</a></li><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/772249/"><strike>functional-tomcat90-mysql57-jdk8/1/8</strike></a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/841535/">functional-tomcat90-mysql57-jdk8/1/9</a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/957321/">functional-tomcat90-mysql57-jdk8/1/10</a></li><li><a href="https://test-1-17.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/303944/"><strike>functional-tomcat90-mysql57-jdk8/1/11</strike></a></li><li><a href="https://test-1-33.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/683201/"><strike>functional-tomcat90-mysql57-jdk8/1/12</strike></a></li><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/715544/">functional-tomcat90-mysql57-jdk8/1/13</a></li><li><a href="https://test-1-36.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/792040/"><strike>functional-tomcat90-mysql57-jdk8/1/14</strike></a></li><li><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/469690/">functional-tomcat90-mysql57-jdk8/1/15</a></li><li><a href="https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/841539/"><strike>functional-tomcat90-mysql57-jdk8/1/16</strike></a></li><li><a href="https://test-1-37.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/957320/"><strike>functional-tomcat90-mysql57-jdk8/1/17</strike></a></li><li><a href="htt [...]

2023-11-29 04:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-acceptance-pullrequest(master)/7680/">test-portal-acceptance-pullrequest(master)#7680</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7680/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>frontend<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/3859">liferay-frontend#3859</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2467239712">[master] ci:test:frontend - JerryAdrianoo &gt; liferay-frontend - PR#3859 - 2023-11-28[17:19:49]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/14813/">publish-testray-report#14813</a><br/></div></div>

2023-11-29 10:18 UTC, JerryAdrianoo commented
@CarlosBrichete failures are not related :)

2023-11-29 14:40 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +	@priority = 5
Low this to 3 (Update jira ticket too)

2023-11-29 14:43 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +	@priority = 5
Low this to 4 (Update jira ticket too)

2023-11-29 14:43 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +		property portal.acceptance = "true";
remove property

2023-11-29 14:44 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +	@priority = 5
Low this to 4 (Update jira ticket too)

2023-11-29 14:44 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +		property portal.acceptance = "true";
remove property

2023-11-29 14:44 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +	@priority = 4
Low this to 3 (Update jira ticket too)

2023-11-29 14:45 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +	@priority = 4
Low this to 3 (Update jira ticket too)

2023-11-29 14:46 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
>  	@priority = 5
Low this to 3 (Update jira ticket too)

2023-11-29 14:46 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +		property portal.acceptance = "true";
remove property

2023-11-29 14:46 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
>  	@description = "LPS-192149. Verify if the user can an Action"
Description is not correct

2023-11-29 14:47 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +	@priority = 5
Low this to 4 (Update jira ticket too)

2023-11-29 14:47 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +		property portal.acceptance = "true";
remove property

2023-11-29 14:47 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
>  	@priority = 5
Low this to 4 (Update jira ticket too)

2023-11-29 14:47 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
>  	@description = "LPS-191485. Verify if the use can create a Async item action"
it should say use**r**

2023-11-29 14:47 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +	@priority = 5
Low this to 4 (Update jira ticket too)

2023-11-29 14:48 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +		property portal.acceptance = "true";
remove property

2023-11-29 14:48 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +	@priority = 5
Low this to 4 (Update jira ticket too)

2023-11-29 14:48 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +		property portal.acceptance = "true";
remove property

2023-11-29 14:48 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +	@priority = 5
Low this to 4 (Update jira ticket too)

2023-11-29 14:48 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +		property portal.acceptance = "true";
remove property

2023-11-29 14:49 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +	@description = "LPS-192956 Confirm that when the user clicks on the Delete option of the Modal item action, the item action is deleted"
This test is not needed. Put this test scenario as Low in Jira ticket and remove it.

2023-11-29 14:50 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
>  	@description = "LPS-191485. Verify if is possible to delete a Async Item Action created"
This test is not needed. Put this test scenario as Low in Jira ticket and remove it.

2023-11-29 14:50 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +	@priority = 4
Low this to 3 (Update jira ticket too)

2023-11-29 14:50 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +	@priority = 5
Low this to 4 (Update jira ticket too)

2023-11-29 14:51 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +		property portal.acceptance = "true";
remove property

2023-11-29 14:51 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +	@priority = 5
Low this to 4 (Update jira ticket too)

2023-11-29 14:51 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
>  	@priority = 5
Low this to 4 (Update jira ticket too)

2023-11-29 14:51 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +		property portal.acceptance = "true";
remove property

2023-11-29 14:51 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +	@priority = 4
Low this to 3 (Update jira ticket too)

2023-11-29 14:52 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +	@priority = 4
Low this to 3 (Update jira ticket too)

2023-11-29 14:52 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
>  	@priority = 5
Low this to 4 (Update jira ticket too)

2023-11-29 14:52 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +		property portal.acceptance = "true";
remove property

2023-11-29 14:52 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
>  	@priority = 5
Low this to 3 (Update jira ticket too)

2023-11-29 14:52 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +		property portal.acceptance = "true";
remove property

2023-11-29 14:53 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
>  	@priority = 5
Low this to 3 (Update jira ticket too)

2023-11-29 14:53 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +		property portal.acceptance = "true";
remove property

2023-11-29 14:53 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +	@priority = 5
Low this to 3 (Update jira ticket too)

2023-11-29 14:53 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +		property portal.acceptance = "true";
remove property

2023-11-29 14:53 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +	@priority = 4
Low this to 3 (Update jira ticket too)

2023-11-30 19:47 UTC, JerryAdrianoo commented
ci:test:sf

2023-11-30 19:47 UTC, JerryAdrianoo commented
@CarlosBrichete done!

2023-11-30 19:52 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/fbe589eb729529318c9cc3232010549611fa1564">fbe589eb729529318c9cc3232010549611fa1564</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JerryAdrianoo/liferay-portal/tree/LPS-199103">LPS-199103</a><br/>Branch GIT ID: <a href="https://github.com/JerryAdrianoo/liferay-portal/commit/540c157edcb2e8856115681543927dbd8ca45ce7">540c157edcb2e8856115681543927dbd8ca45ce7</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/4775/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/4775/jenkins-report.html">here</a>.</h5></details></html>

2023-11-30 20:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/4775/">test-portal-source-format#4775</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/4775/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/3859">liferay-frontend#3859</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2468379263">[master] ci:test:sf - JerryAdrianoo &gt; liferay-frontend - PR#3859 - 2023-11-30[11:47:12]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/17664/">publish-testray-report#17664</a><br/></div></div>

2023-12-01 09:55 UTC, CarlosBrichete requested changes

2023-12-01 09:55 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +	@priority = 5
Still pending to modify

2023-12-01 09:55 UTC, CarlosBrichete commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/dataset/DataSetViewActions.testcase
> +		property portal.acceptance = "true";
Still pending to modify

2023-12-01 10:31 UTC, JerryAdrianoo commented
Okay, now I hope it's finished 🥲

2023-12-01 12:24 UTC, CarlosBrichete approved these changes
LGTM :) But probably you will have to wait for this PR to be merged https://github.com/brianchandotcom/liferay-portal/pull/144707

2023-12-04 10:13 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-4.liferay.com/job/test-portal-source-format/6422/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/6422/jenkins-report.html">here</a>.</b></p>

2023-12-04 10:16 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/a9ac4bcd5ec0216db4511ad240703d18b0b97eab">a9ac4bcd5ec0216db4511ad240703d18b0b97eab</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/JerryAdrianoo/liferay-portal/tree/LPS-199103">LPS-199103</a><br/>Branch GIT ID: <a href="https://github.com/JerryAdrianoo/liferay-portal/commit/860c000601543486a6fb638a51e63fbd486c556d">860c000601543486a6fb638a51e63fbd486c556d</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-4.liferay.com/job/test-portal-source-format/6422/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-4.liferay.com/userContent/jobs/test-portal-source-format/builds/6422/jenkins-report.html">here</a>.</h5></details></html>

2023-12-04 10:17 UTC, liferay-continuous-integration commented
All required test suite(s) passed.
Forwarding pull request to `brianchandotcom`.
[Console](https://test-1-4.liferay.com/job/test-portal-source-format/6422//consoleFull)

2023-12-04 10:17 UTC, closed without merging

2023-12-04 10:17 UTC, liferay-continuous-integration commented
Pull request has been successfully forwarded to  https://github.com/brianchandotcom/liferay-portal/pull/144796
[Console](https://test-1-4.liferay.com/job/test-portal-source-format/6422//consoleFull)

2023-12-04 10:20 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/3016/">test-portal-acceptance-pullrequest(master)#3016</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3016/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>relevant<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/3859">liferay-frontend#3859</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2470048892">[master] ci:test:relevant - JerryAdrianoo &gt; liferay-frontend - PR#3859 - 2023-12-04[02:11:36]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/29301/">publish-testray-report#29301</a><br/></div></div>