LPD-15145 Clear mapping of DSM fields in cards visualization mode
liferay-frontend/liferay-portal pull request #4042
Opened 2024-03-06 09:55 UTC by chestofwonders

Task: https://liferay.atlassian.net/browse/LPD-15145

**Scope:**

**Allow users to clear and change assigned fields to DSM views in Cards visualization mode**

LPD-10735 FF should be added to access Visualization modes

![image](https://github.com/liferay-frontend/liferay-portal/assets/20504176/35d82a10-396f-42bb-bf42-3a7ffe90b896)

When there is no a field mapped, the "Not Assigned" message should appear:

![image](https://github.com/liferay-frontend/liferay-portal/assets/20504176/96bf860c-94ba-4f83-a955-f5ac2ff48bf6)

Once a field is mapped, a three-dot button should appears instead of the '+' button:

![image](https://github.com/liferay-frontend/liferay-portal/assets/20504176/ee902f8a-5546-4476-a247-43e0eb3a30d1)

That button opens a dropdown menu that allows user to unmap the field (so the "Not Assigned" label should appear again, and the button should revert to the previous '+') or change the field. In that case, the selection fields modal is open, allowing the user to choose a new field.

![image](https://github.com/liferay-frontend/liferay-portal/assets/20504176/dfc125d4-9b4f-4aca-9f51-9771417a194c)

**Acceptance Criteria:**

- Users can clear the assignment of fields in cards individually.
- When a user clicks on the action, the field is unmapped immediately and persisted.

2024-03-06 09:55 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-03-06 09:57 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-19.liferay.com/job/test-portal-source-format/7512/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/7512/jenkins-report.html">here</a>.</b></p>

2024-03-06 10:00 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c2b0d81033ac7e2407aa8191e8323940706b7d1a">c2b0d81033ac7e2407aa8191e8323940706b7d1a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/chestofwonders/liferay-portal/tree/LPD-15145">LPD-15145</a><br/>Branch GIT ID: <a href="https://github.com/chestofwonders/liferay-portal/commit/90181b5ae7942174f519cc5c2fd0ee17735b8718">90181b5ae7942174f519cc5c2fd0ee17735b8718</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-19.liferay.com/job/test-portal-source-format/7512/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/7512/jenkins-report.html">here</a>.</h5></details></html>

2024-03-06 10:03 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-19.liferay.com/job/test-portal-source-format/7512/">test-portal-source-format#7512</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/7512/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/4042">liferay-frontend#4042</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2547002472">[master] ci:test:sf - chestofwonders &gt; liferay-frontend - PR#4042 - 2024-03-06[01:55:51]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>2547002472<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-19.liferay.com/job/publish-testray-report/4212/">publish-testray-report#4212</a><br/></div></div>

2024-03-06 10:46 UTC, juanjofgliferay commented on modules/apps/frontend-data-set/frontend-data-set-views-web/src/main/resources/META-INF/resources/js/fds_view/visualization_modes/cards/Cards.tsx
> +	const onClickAssign = () => {
I know it is a bit picky :smile:, but wouldn't be clear rename the handler using its purpose, like `handleAssign`, `assignField` as it is already the callback of an `onClick` prop?

2024-03-06 10:46 UTC, juanjofgliferay commented on modules/apps/frontend-data-set/frontend-data-set-views-web/src/main/resources/META-INF/resources/js/fds_view/visualization_modes/cards/Cards.tsx
> +		onClear(cardsSection);
:sweat_smile: same as above

2024-03-06 14:02 UTC, markocikos requested changes
@chestofwonders please see comments inline

2024-03-06 14:02 UTC, markocikos commented on modules/apps/frontend-data-set/frontend-data-set-views-web/src/main/resources/META-INF/resources/js/fds_view/visualization_modes/cards/Cards.tsx
> +						{field?.name ? (
Please see [solution from List](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-data-set/frontend-data-set-views-web/src/main/resources/META-INF/resources/js/fds_view/visualization_modes/list/List.tsx#L297-L329). The solution in Cards should be nearly the same, only with different labels and CSS classes. We may even consider extracting it to common component(s) in `visualization_modes` scope.

2024-03-07 14:25 UTC, chestofwonders commented
Continues in https://github.com/liferay-frontend/liferay-portal/pull/4051

2024-03-07 14:25 UTC, closed without merging