WIP LPD-37109
liferay-frontend/liferay-portal pull request #4626
Opened 2024-12-18 22:59 UTC by fortunatomaldonado

Hello @dsanz @markocikos 

Is the following WIP commit the correct way to go about making the chnages Brian Chan asked for here?
https://github.com/brianchandotcom/liferay-portal/pull/155292#issuecomment-2420138654

Also I see that the snippets are being commented out in the aui:script. Is this expected?
![Screenshot from 2024-12-18 15-52-00](https://github.com/user-attachments/assets/44047155-cec4-43b9-bdc7-abeb5ec505ac)

Thank you for the help!

2024-12-18 22:59 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2024-12-18 23:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-portal-source-format/7654/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/7654/jenkins-report.html">here</a>.</b></p>

2024-12-18 23:04 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1d1009bc5a1f8b027c53e140f147d9a272f71af8">1d1009bc5a1f8b027c53e140f147d9a272f71af8</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/fortunatomaldonado/liferay-portal/tree/LPD-37109-WIP">LPD-37109-WIP</a><br/>Branch GIT ID: <a href="https://github.com/fortunatomaldonado/liferay-portal/commit/bc32c9651a22d5dcf1b00f8c85dc83b490e7717c">bc32c9651a22d5dcf1b00f8c85dc83b490e7717c</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-source-format/7654/"><strike>test-portal-source-format</strike></a></li></ul></div><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/7654/jenkins-report.html">here</a>.</h5><pre>format-source-files:
     [java] java.lang.Exception: Found formatting issue in SHA 69bf6ccf9930d1e24653dabdf8c7ba3bb5626faf
     [java] The commit message is missing a reference to a required JIRA project: BLADE, CLDSVCS, COMMERCE, FACES, IDE, ISSD, ISSITES, LCD, LHC, LOOP, LPD, LPS, LRAC, LRCI, LRDOCS, LRIS, LRQA, LRSD, OAUTH2, POSHI, RELEASE, SYNC, TR. Please verify that the JIRA project keys are specifiedin source-formatter.properties in the liferay-portal repository.
     [java]   at com.liferay.source.formatter.util.JIRAUtil.validateJIRAProjectNames(JIRAUtil.java:62)
     [java]   at com.liferay.source.formatter.SourceFormatter._validateCommitMessages(SourceFormatter.java:1320)
     [java]   at com.liferay.source.formatter.SourceFormatter.format(SourceFormatter.java:337)
     [java]   at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:301)
[stopwatch] [run.batch.test.action: 2:17.667 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:497: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:650: Java returned: 1
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1699441262.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[beanshell] Truncating errors in /opt/dev/projects/github/liferay-portal/portal-impl/test-results/TEST-JenkinsLogAssertTest.xml
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null2090759801
[junitreport] Loading stylesheet ile:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 265ms
[junitreport] Deleting: /tmp/null2090759801
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 12-18-2024 15:04:21:932 PST
[stopwatch] [run.batch.test.tear.down: 0.001 sec]</pre></details></html>

2024-12-18 23:07 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-6.liferay.com/job/test-portal-source-format/7654/">test-portal-source-format#7654</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/7654/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/liferay-frontend/liferay-portal/pull/4626">liferay-frontend#4626</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/#/project/35392/routines/45357/build/95330276">[master] ci:test:sf - fortunatomaldonado &gt; liferay-frontend - PR#4626 - 2024-12-18[14:59:53]</a><br/></div><div><strong>Testray Build ID:</strong><span></span>95330276<br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-6.liferay.com/job/publish-testray-report/5399/">publish-testray-report#5399</a><br/></div></div>

2024-12-19 16:24 UTC, dsanz commented on portal-web/docroot/html/common/themes/bottom_js.jspf
> +	</liferay-util:include>
this shall be `masterLayoutTypeSettingsUnicodeProperties`

2024-12-30 16:20 UTC, dsanz commented
@fortunatomaldonado the approach is the one Brian aksed for.

Nevertheless, what the screenshot shows something odd. Apparently,  the browser is receiving JSP code directly, you can see some JSP tags in the HTML sduch as `<aui:script>` or `<c:if>`, however, the `snippet` variable is resolved. 

Most likely, this is a side effect of [this include](https://github.com/liferay-frontend/liferay-portal/pull/4626/commits/bc32c9651a22d5dcf1b00f8c85dc83b490e7717c#diff-2c8fc11a0378751b50bf450a574859082c00e9cd1e6fba4b7be10fa5324b2bc6R30). I think that is not needed because the `<liferay-util:include>` does the job

2024-12-30 16:22 UTC, dsanz commented on portal-web/docroot/html/common/themes/bottom_js_script.jsp
> +<%@ page import="com.liferay.portal.kernel.util.ParamUtil" %>
Please move this import to `init.jsp`

2024-12-30 16:23 UTC, dsanz requested changes
We're getting closer @fortunatomaldonado, please review inline comments. Thx

2024-12-30 16:23 UTC, dsanz commented on portal-web/docroot/html/common/themes/bottom.jsp
> +<%@ include file="/html/common/themes/bottom_js_script.jsp" %>
This shall not be needed here

2025-01-07 19:14 UTC, fortunatomaldonado commented
Hello @dsanz 

Thank you for the help!
I made the changes and looks to be working better.

Another issue is the javascript is commented out in the html as shown below as well as the if statement being added to the html. I'm not sure if this is what is expected or not.
![Screenshot from 2025-01-07 12-12-19](https://github.com/user-attachments/assets/d4eb9a7f-e725-4909-a775-b773312f90f6)

If I remove the <![CDATA[ then it is displayed as text on the page.

2025-01-08 19:32 UTC, dsanz commented
Hey @fortunatomaldonado that CDATA shall not be an issue, we use it in other places. Real thing here is that markup is being sent vertabitm instead of being executed by the JSP engine. Served page should never contain JSP code, and your screenshot seems to show evidence of that.

About that last thing, I'd like to check if we can get rid of `servletContext="<%= application %>"` attribute when calling `liferay-util:include` tag. I did not found evidence of this being needed when the page belongs to `portal-web`. Could you please try?

2025-01-08 22:03 UTC, fortunatomaldonado commented
Hello @dsanz
Yeah I see that it is printing verbatim.
I removed the servletContext="<%= application %>" and was not able to see a change.

2025-01-09 20:06 UTC, fortunatomaldonado commented
FWD: https://github.com/liferay-frontend/liferay-portal/pull/4649
@dsanz I added the init.jsp wrong.
This was the correct way `<%@ include file="/html/common/init.jsp" %>`

2025-01-09 20:06 UTC, closed without merging