[LRQA-63100, LRQA-63099]- Fix assertion value  outside none none  to  none outside none
liferay-frontend/liferay-portal pull request #500
Opened 2020-11-16 04:01 UTC by PablitoBonito

JIRA Ticket: https://issues.liferay.com/browse/LRQA-63100 https://issues.liferay.com/browse/LRQA-63099

2020-11-16 04:01 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2020-11-16 09:59 UTC, manoelcyreno commented
ci:test:sf

2020-11-16 10:00 UTC, manoelcyreno commented
ci:test:relevant

2020-11-16 10:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-6.liferay.com/job/test-portal-source-format/4460/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-6.liferay.com//userContent/jobs/test-portal-source-format/builds/4460/jenkins-report.html">here</a>.</b></p>

2020-11-16 10:00 UTC, manoelcyreno commented
ci:test:frontend

2020-11-16 10:00 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/7532/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-2.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7532/jenkins-report.html">here</a>.</b></p>

2020-11-16 10:01 UTC, manoelcyreno commented
@PablitoBonito , remember to edit your description to tell how to run (how to test) it...

2020-11-16 10:01 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/7533/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-2.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7533/jenkins-report.html">here</a>.</b></p>

2020-11-16 10:01 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 0 ms</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/58c93cc3229fee3b08c1076d1096f5ed567f5ea5">58c93cc3229fee3b08c1076d1096f5ed567f5ea5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/PablitoBonito/liferay-portal/tree/LRQA-63100">LRQA-63100</a><br/>Branch GIT ID: <a href="https://github.com/PablitoBonito/liferay-portal/commit/e3d07004bb11d75ce3e44d09c73e15df821170e6">e3d07004bb11d75ce3e44d09c73e15df821170e6</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-source-format/4460/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/4460/jenkins-report.html">here</a>.</h5><pre><code>  &lt;arg value="-PdependencyNotation=com.liferay.portal:com.liferay.portal.plugins.sdk:1.0.42" /&gt;
  &lt;arg value="--max-workers=4" /&gt;
  &lt;arg value="--no-daemon" /&gt;
  &lt;arg value="--profile" /&gt;
  &lt;arg value="--project-cache-dir=/opt/dev/projects/github/liferay-portal/.gradle" /&gt;
  &lt;arg value="--stacktrace" /&gt;
  &lt;arg value="-Dapp.server.parent.dir=/opt/dev/projects/github/liferay-portal/bundles" /&gt;
  &lt;arg value="-Dforced.cache.enabled=true" /&gt;
  &lt;arg value="-Dliferay.home=/opt/dev/projects/github/liferay-portal/bundles" /&gt;
  &lt;arg value="-Dorg.gradle.internal.http.connectionTimeout=120000" /&gt;
  &lt;arg value="-Dorg.gradle.internal.http.socketTimeout=120000" /&gt;
  &lt;arg value="-Dorg.gradle.jvmargs=-Dhttp.nonProxyHosts=&amp;quot;cloud*|files.liferay.org.es|it.liferay.com|localhost|mirrors-no-cache.lax.liferay.com|release*|test*&amp;quot; -server -verbose:gc -Xloggc:/tmp/ant-gc.log -Xms1024m -Xmx4096m -Xss2m -Xverify:none -XX:+DisableExplicitGC -XX:+HeapDumpOnOutOfMemoryError -XX:+PrintGCCause -XX:+PrintGCDetails -XX:+UseParallelOldGC -XX:HeapDumpPath=/tmp/ant-oom-heap-dump.bin -XX:MaxNewSize=512m -XX:MaxMetaspaceSize=512m -XX:MaxTenuringThreshold=0 -XX:NewSize=256m -XX:MetaspaceSize=100m -XX:SurvivorRatio=65536 -XX:TargetSurvivorRatio=0" /&gt;
  &lt;arg line="printDependencyPath" /&gt;
  &lt;redirector errorproperty="error.property" outputproperty="output.property" /&gt;
&lt;/exec&gt;
     [echo] 
[stopwatch] [run.batch.test.action: 6.938 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build.xml:1123: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-common.xml:1771: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/build-common.xml:1004: Unable to execute Gradle task: printDependencyPath.
      [get] Getting: http://test-1-6/job/test-portal-source-format/4460//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20201116013205611.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20201116013205611.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null290686668.properties</code></pre></details></html>

2020-11-16 10:02 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:relevant - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c74cbb3487428c54ae2122c205af3c954e0e01a3">c74cbb3487428c54ae2122c205af3c954e0e01a3</a></p><details><summary><strong>ci:test:relevant - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/7532/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7532/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/7532/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre><code>     [echo] * What went wrong:
     [echo] Could not resolve all artifacts for configuration 'classpath'.
     [echo] &gt; Could not find com.github.jk1:gradle-license-report:1.8.
     [echo]   Searched in the following locations:
     [echo]     - file:/root/.m2/repository/com/github/jk1/gradle-license-report/1.8/gradle-license-report-1.8.pom
     [echo]     - https://repository-cdn.liferay.com/nexus/content/groups/public/com/github/jk1/gradle-license-report/1.8/gradle-license-report-1.8.pom
     [echo]   Required by:
     [echo]       unspecified:unspecified:unspecified &gt; com.liferay:com.liferay.gradle.plugins.defaults:6.1.404
     [echo] &gt; Could not find com.gradle.publish:plugin-publish-plugin:0.11.0.
     [echo]   Searched in the following locations:
     [echo]     - file:/root/.m2/repository/com/gradle/publish/plugin-publish-plugin/0.11.0/plugin-publish-plugin-0.11.0.pom
     [echo]     - https://repository-cdn.liferay.com/nexus/content/groups/public/com/gradle/publish/plugin-publish-plugin/0.11.0/plugin-publish-plugin-0.11.0.pom
     [echo]   Required by:
     [echo]       unspecified:unspecified:unspecified &gt; com.liferay:com.liferay.gradle.plugins.defaults:6.1.404
     [echo] &gt; Could not find gradle.plugin.com.github.spotbugs.snom:spotbugs-gradle-plugin:4.0.0.
     [echo]   Searched in the following locations:
     [echo]     - file:/root/.m2/repository/gradle/plugin/com/github/spotbugs/snom/spotbugs-gradle-plugin/4.0.0/spotbugs-gradle-plugin-4.0.0.pom
     [echo]     - https://repository-cdn.liferay.com/nexus/content/groups/public/gradle/plugin/com/github/spotbugs/snom/spotbugs-gradle-plugin/4.0.0/spotbugs-gradle-plugin-4.0.0.pom
     [echo]   Required by:
     [echo]       unspecified:unspecified:unspecified &gt; com.liferay:com.liferay.gradle.plugins.defaults:6.1.404
     [echo] &gt; Could not resolve org.springframework.boot:spring-boot-gradle-plugin:1.5.7.RELEASE.
     [echo]   Required by:
     [echo]       unspecified:unspecified:unspecified &gt; com.liferay:com.liferay.gradle.plugins.defaults:6.1.404
     [echo]    &gt; Could not resolve org.springframework.boot:spring-boot-gradle-plugin:1.5.7.RELEASE.
     [echo]       &gt; Could not parse POM https://repository-cdn.liferay.com/nexus/content/groups/public/org/springframework/boot/spring-boot-gradle-plugin/1.5.7.RELEASE/spring-boot-gradle-plugin-1.5.7.RELEASE.pom
     [echo]          &gt; Could not resolve org.springframework.boot:spring-boot-tools:1.5.7.RELEASE.</code></pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2020-11-16 10:02 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:frontend - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c74cbb3487428c54ae2122c205af3c954e0e01a3">c74cbb3487428c54ae2122c205af3c954e0e01a3</a></p><details><summary><strong>ci:test:frontend - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/7533/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-2.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7533/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest(master)/7533/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><pre><code>     [echo] * What went wrong:
     [echo] Could not resolve all artifacts for configuration 'classpath'.
     [echo] &gt; Could not find com.github.jk1:gradle-license-report:1.8.
     [echo]   Searched in the following locations:
     [echo]     - file:/root/.m2/repository/com/github/jk1/gradle-license-report/1.8/gradle-license-report-1.8.pom
     [echo]     - https://repository-cdn.liferay.com/nexus/content/groups/public/com/github/jk1/gradle-license-report/1.8/gradle-license-report-1.8.pom
     [echo]   Required by:
     [echo]       unspecified:unspecified:unspecified &gt; com.liferay:com.liferay.gradle.plugins.defaults:6.1.404
     [echo] &gt; Could not find com.gradle.publish:plugin-publish-plugin:0.11.0.
     [echo]   Searched in the following locations:
     [echo]     - file:/root/.m2/repository/com/gradle/publish/plugin-publish-plugin/0.11.0/plugin-publish-plugin-0.11.0.pom
     [echo]     - https://repository-cdn.liferay.com/nexus/content/groups/public/com/gradle/publish/plugin-publish-plugin/0.11.0/plugin-publish-plugin-0.11.0.pom
     [echo]   Required by:
     [echo]       unspecified:unspecified:unspecified &gt; com.liferay:com.liferay.gradle.plugins.defaults:6.1.404
     [echo] &gt; Could not find gradle.plugin.com.github.spotbugs.snom:spotbugs-gradle-plugin:4.0.0.
     [echo]   Searched in the following locations:
     [echo]     - file:/root/.m2/repository/gradle/plugin/com/github/spotbugs/snom/spotbugs-gradle-plugin/4.0.0/spotbugs-gradle-plugin-4.0.0.pom
     [echo]     - https://repository-cdn.liferay.com/nexus/content/groups/public/gradle/plugin/com/github/spotbugs/snom/spotbugs-gradle-plugin/4.0.0/spotbugs-gradle-plugin-4.0.0.pom
     [echo]   Required by:
     [echo]       unspecified:unspecified:unspecified &gt; com.liferay:com.liferay.gradle.plugins.defaults:6.1.404
     [echo] &gt; Could not resolve org.springframework.boot:spring-boot-gradle-plugin:1.5.7.RELEASE.
     [echo]   Required by:
     [echo]       unspecified:unspecified:unspecified &gt; com.liferay:com.liferay.gradle.plugins.defaults:6.1.404
     [echo]    &gt; Could not resolve org.springframework.boot:spring-boot-gradle-plugin:1.5.7.RELEASE.
     [echo]       &gt; Could not parse POM https://repository-cdn.liferay.com/nexus/content/groups/public/org/springframework/boot/spring-boot-gradle-plugin/1.5.7.RELEASE/spring-boot-gradle-plugin-1.5.7.RELEASE.pom
     [echo]          &gt; Could not resolve org.springframework.boot:spring-boot-tools:1.5.7.RELEASE.</code></pre></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2020-11-16 10:03 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-6.liferay.com/job/test-portal-source-format/4460/">test-portal-source-format#4460</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-6.liferay.com/userContent/jobs/test-portal-source-format/builds/4460/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-frontend/liferay-portal/pull/500">liferay-frontend#500</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/1302.aspx">/Liferay DXP 7.3/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/61202.aspx">master - PablitoBonito > liferay-frontend - PR#500 - 2020-11-16[02:00:28]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-1.liferay.com/job/publish-spira-report/13787/">publish-spira-report#13787</a><br />

2020-11-16 17:51 UTC, john-co requested changes
@PablitoBonito ,
You should split up into two commits. We don't put two tickets in the same message.

Also your title and commit messages are completely opposite of the fix. I think you meant, "none outside none" to "outside none none". 

Your JIRA comment on the tickets also look like a typo: `Changing value in the assertions from  "outside none none" to "outside none none" fix the issue.`

2020-11-16 17:53 UTC, john-co commented
ci:test:sf

2020-11-16 17:54 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-13.liferay.com/job/test-portal-source-format/3346/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-13.liferay.com//userContent/jobs/test-portal-source-format/builds/3346/jenkins-report.html">here</a>.</b></p>

2020-11-16 17:54 UTC, john-co commented
ci:test:relevant

2020-11-16 17:57 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/58c93cc3229fee3b08c1076d1096f5ed567f5ea5">58c93cc3229fee3b08c1076d1096f5ed567f5ea5</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/PablitoBonito/liferay-portal/tree/LRQA-63100">LRQA-63100</a><br/>Branch GIT ID: <a href="https://github.com/PablitoBonito/liferay-portal/commit/e3d07004bb11d75ce3e44d09c73e15df821170e6">e3d07004bb11d75ce3e44d09c73e15df821170e6</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-13.liferay.com/job/test-portal-source-format/3346/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/3346/jenkins-report.html">here</a>.</h5><pre><code>     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:276)
[stopwatch] [run.batch.test.action: 1:56.654 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:572: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:706: Java returned: 1
      [get] Getting: http://test-1-13/job/test-portal-source-format/3346//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20201116095713246.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20201116095713246.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null665267756.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null1380099933
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 229ms
[junitreport] Deleting: /tmp/null1380099933
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 11-16-2020 09:57:18:767 PST
[stopwatch] [run.batch.test.tear.down: 0.000 sec]
     [echo] 
     [echo] Ant GC log:
     [echo] 
     [echo] Java HotSpot(TM) 64-Bit Server VM (25.121-b13) for linux-amd64 JRE (1.8.0_121-b13), built on Dec 12 2016 16:36:53 by "java_re" with gcc 4.3.0 20080428 (Red Hat 4.3.0-8)
     [echo] Memory: 4k page, physical 32902016k(1962008k free), swap 0k(0k free)</code></pre></details></html>

2020-11-16 18:03 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-13.liferay.com/job/test-portal-source-format/3346/">test-portal-source-format#3346</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-13.liferay.com/userContent/jobs/test-portal-source-format/builds/3346/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-frontend/liferay-portal/pull/500">liferay-frontend#500</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/1302.aspx">/Liferay DXP 7.3/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/61349.aspx">master - PablitoBonito > liferay-frontend - PR#500 - 2020-11-16[09:53:45]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-8.liferay.com/job/publish-spira-report/8330/">publish-spira-report#8330</a><br />

2020-11-16 18:06 UTC, john-co commented
The SF test is failing due to the git commit message not starting with LRQA-xxx or other project...did you try running SF and checking the results?...

2020-11-16 18:27 UTC, john-co commented
Test is expected to fail on CI since it still uses Chrome65. Please attach poshi report to tickets showing they locally pass on Chrome 86.

This is a temp fix, we'll need to find a longer term test fix since the difference between `none outside none` and `outside none none` isn't a true test requirement we necessarily care about.

2020-11-16 18:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest(master)/6340/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-7.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6340/jenkins-report.html">here</a>.</b></p>

2020-11-16 20:29 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 2 out of 2 jobs passed</h3><h3>:x: ci:test:relevant - 4 out of 6 jobs passed in 1 hour 57 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/c74cbb3487428c54ae2122c205af3c954e0e01a3">c74cbb3487428c54ae2122c205af3c954e0e01a3</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/8d22a791300569a6c92e7b9152e6ae1c6bdc863a">8d22a791300569a6c92e7b9152e6ae1c6bdc863a</a></p><details><summary><strong>ci:test:stable - 2 out of 2 jobs PASSED</strong></summary><details><summary><strong>2 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/396825/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/417128/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 4 out of 6 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest(master)/6340/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/396827/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>4 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/396826/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/396825/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/417127/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/417128/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6340/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/396827/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>38 Tests Passed.<br/>2 Tests Failed.</p></div><ol><li><div><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=9,label_exp=!master/396827//consoleText">AXIS_VARIABLE=9,label_exp=!master #396827</a><ol><li><div><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=9,label_exp=!master/396827//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_UIInfrastructureUsecase_RefreshHomePage_">LocalFile.UIInfrastructureUsecase#RefreshHomePage</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-7/1605551479154/test-portal-acceptance-pullrequest(master)/6340/functional-tomcat90-mysql57-jdk8/0/9/LocalFile.UIInfrastructureUsecase_RefreshHomePage/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-7/1605551479154/test-portal-acceptance-pullrequest(master)/6340/functional-tomcat90-mysql57-jdk8/0/9/LocalFile.UIInfrastructureUsecase_RefreshHomePage/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-7/1605551479154/test-portal-acceptance-pullrequest(master)/6340/functional-tomcat90-mysql57-jdk8/0/9/jenkins-console.txt.gz">Console Output</a></div></li><li><div><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=9,label_exp=!master/396827//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_UIInfrastructureUsecase_RefreshWebContent_">LocalFile.UIInfrastructureUsecase#RefreshWebContent</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-7/1605551479154/test-portal-acceptance-pullrequest(master)/6340/functional-tomcat90-mysql57-jdk8/0/9/LocalFile.UIInfrastructureUsecase_RefreshWebContent/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-7/1605551479154/test-portal-acceptance-pullrequest(master)/6340/functional-tomcat90-mysql57-jdk8/0/9/LocalFile.UIInfrastructureUsecase_RefreshWebContent/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-7/1605551479154/test-portal-acceptance-pullrequest(master)/6340/functional-tomcat90-mysql57-jdk8/0/9/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2020-11-16 20:32 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest(master)/6340/">test-portal-acceptance-pullrequest(master)#6340</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-7.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6340/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> relevant<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-frontend/liferay-portal/pull/500">liferay-frontend#500</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/1312.aspx">/Liferay DXP 7.3/Pull Request/ci:test:relevant</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/61418.aspx">master - PablitoBonito > liferay-frontend - PR#500 - 2020-11-16[10:31:19]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-8.liferay.com/job/publish-spira-report/8355/">publish-spira-report#8355</a><br />

2020-11-17 13:54 UTC, PablitoBonito commented
@john-co  Should I split then? I put two tickets in one message because the fix was the same for both of them and in the same file. Also I saw PR where are fixed several tickets by one time. Like here: [pr#489](https://github.com/liferay-frontend/liferay-portal/pull/489)

Yes, I did the typos, thanks for pointing that. Already updated the description and will correct the tickets with putting there the Poshi report as well.

2020-11-17 16:31 UTC, john-co commented
@PablitoBonito , I'm talking about the git commits, not the title of the PR. In the PR you linked they split the commits by their respective tickets, see https://github.com/liferay-frontend/liferay-portal/pull/489/commits

2020-11-18 03:54 UTC, PablitoBonito commented
Got it, thank you @john-co 
So what I should do now?

2020-11-18 08:40 UTC, manoelcyreno commented
@PablitoBonito , as far I understood, you need:

1. create one LSP ticket (testing type) to tell fix the two tickets mentioned in this PR ... and use this ticket in the title of your PR and commits. (not use the LRQA to it)

2. to split your commit in two ... 
the first commit to `LPS-?????? Fix assertion value outside none none to none outside none from the LRQA-63100`
the second commit to `LPS-?????? Fix assertion value outside none none to none outside none from the LRQA-63099`

I think is that.

2020-11-18 17:49 UTC, john-co commented
I think what Manoel proposed is fine. Keep in mind the typos for the PR Title and git commit messages: `none outside none to outside none none`

2020-11-19 07:30 UTC, manoelcyreno commented
ci:test:sf

2020-11-19 07:31 UTC, manoelcyreno commented
ci:test:relevant

2020-11-19 07:31 UTC, manoelcyreno commented
ci:test:frontend

2020-11-19 07:31 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-10.liferay.com/job/test-portal-source-format/2051/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-10.liferay.com//userContent/jobs/test-portal-source-format/builds/2051/jenkins-report.html">here</a>.</b></p>

2020-11-19 07:35 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 26 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/52ea603f0a177cdc60870987ff13356cd25824fd">52ea603f0a177cdc60870987ff13356cd25824fd</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/PablitoBonito/liferay-portal/tree/LRQA-63100">LRQA-63100</a><br/>Branch GIT ID: <a href="https://github.com/PablitoBonito/liferay-portal/commit/91302d8b91a5d89889f55937bf205923b7a19b5a">91302d8b91a5d89889f55937bf205923b7a19b5a</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-source-format/2051/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/2051/jenkins-report.html">here</a>.</h5></details></html>

2020-11-19 07:37 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-10.liferay.com/job/test-portal-source-format/2051/">test-portal-source-format#2051</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-10.liferay.com/userContent/jobs/test-portal-source-format/builds/2051/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-frontend/liferay-portal/pull/500">liferay-frontend#500</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/1302.aspx">/Liferay DXP 7.3/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/62639.aspx">master - PablitoBonito > liferay-frontend - PR#500 - 2020-11-18[23:31:33]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-20.liferay.com/job/publish-spira-report/7481/">publish-spira-report#7481</a><br />

2020-11-19 10:09 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest(master)/6968/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-23.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6968/jenkins-report.html">here</a>.</b></p>

2020-11-19 11:23 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest(master)/3956/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-9.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3956/jenkins-report.html">here</a>.</b></p>

2020-11-19 13:30 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 2 out of 2 jobs passed</h3><h3>:x: ci:test:relevant - 4 out of 6 jobs passed in 3 hours 20 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1e59f5d5135630ff3ceeddaee94ba44f2c5b88d3">1e59f5d5135630ff3ceeddaee94ba44f2c5b88d3</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/8d22a791300569a6c92e7b9152e6ae1c6bdc863a">8d22a791300569a6c92e7b9152e6ae1c6bdc863a</a></p><details><summary><strong>ci:test:stable - 2 out of 2 jobs PASSED</strong></summary><details><summary><strong>2 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/458134/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451450/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 4 out of 6 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest(master)/6968/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/469786/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>4 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451449/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/458134/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/458135/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451450/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-23.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6968/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/469786/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>39 Tests Passed.<br/>1 Test Failed.</p></div><ol><li><div><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=9,label_exp=!master/469786//consoleText">AXIS_VARIABLE=9,label_exp=!master #469786</a><ol><li><div><a href="https://test-1-2.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=9,label_exp=!master/469786//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_UIInfrastructureUsecase_RefreshHomePage_">LocalFile.UIInfrastructureUsecase#RefreshHomePage</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-23/1605780513910/test-portal-acceptance-pullrequest(master)/6968/functional-tomcat90-mysql57-jdk8/0/9/LocalFile.UIInfrastructureUsecase_RefreshHomePage/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-23/1605780513910/test-portal-acceptance-pullrequest(master)/6968/functional-tomcat90-mysql57-jdk8/0/9/LocalFile.UIInfrastructureUsecase_RefreshHomePage/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-23/1605780513910/test-portal-acceptance-pullrequest(master)/6968/functional-tomcat90-mysql57-jdk8/0/9/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2020-11-19 13:37 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-23.liferay.com/job/test-portal-acceptance-pullrequest(master)/6968/">test-portal-acceptance-pullrequest(master)#6968</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-23.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6968/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> relevant<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-frontend/liferay-portal/pull/500">liferay-frontend#500</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/1312.aspx">/Liferay DXP 7.3/Pull Request/ci:test:relevant</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/62753.aspx">master - PablitoBonito > liferay-frontend - PR#500 - 2020-11-19[02:08:33]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-12.liferay.com/job/publish-spira-report/8124/">publish-spira-report#8124</a><br />

2020-11-19 14:17 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:frontend - 6 out of 9 jobs passed in 2 hours 54 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/1e59f5d5135630ff3ceeddaee94ba44f2c5b88d3">1e59f5d5135630ff3ceeddaee94ba44f2c5b88d3</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/8d22a791300569a6c92e7b9152e6ae1c6bdc863a">8d22a791300569a6c92e7b9152e6ae1c6bdc863a</a></p><details><summary><strong>ci:test:frontend - 6 out of 9 jobs PASSED</strong></summary><div><h4>3 Failed Jobs:</h4><ul><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest(master)/3956/"><strike><strong>test-portal-acceptance-pullrequest(master)</strong></strike></a></li><li><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/369109/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</strong></strike></a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451458/"><strike><strong>test-portal-acceptance-pullrequest-batch(master)/modules-semantic-versioning-jdk8/0</strong></strike></a></li></ul></div><details><summary><strong>6 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/451457/">test-portal-acceptance-pullrequest-batch(master)/central-requirements-jdk8/0</a></li><li><a href="https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/456413/">test-portal-acceptance-pullrequest-batch(master)/js-unit-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/456478/">test-portal-acceptance-pullrequest-batch(master)/modules-integration-mysql57-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/456479/">test-portal-acceptance-pullrequest-batch(master)/modules-unit-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/456481/">test-portal-acceptance-pullrequest-batch(master)/semantic-versioning-jdk8/0</a></li><li><a href="https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/456480/">test-portal-acceptance-pullrequest-batch(master)/unit-jdk8/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3956/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/369109/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></h5><div><h6>Job Results:</h6><p>73 Tests Passed.<br/>5 Tests Failed.</p></div><ol><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=11,label_exp=!master/369109//consoleText">AXIS_VARIABLE=11,label_exp=!master #369109</a><ol><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=11,label_exp=!master/369109//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ClayAlert_ToastMessageAutoClose_">LocalFile.ClayAlert#ToastMessageAutoClose</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-9/1605784987887/test-portal-acceptance-pullrequest(master)/3956/functional-tomcat90-mysql57-jdk8/0/11/LocalFile.ClayAlert_ToastMessageAutoClose/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-9/1605784987887/test-portal-acceptance-pullrequest(master)/3956/functional-tomcat90-mysql57-jdk8/0/11/LocalFile.ClayAlert_ToastMessageAutoClose/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-9/1605784987887/test-portal-acceptance-pullrequest(master)/3956/functional-tomcat90-mysql57-jdk8/0/11/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=12,label_exp=!master/369109//consoleText">AXIS_VARIABLE=12,label_exp=!master #369109</a><ol><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=12,label_exp=!master/369109//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ClayAlert_ToastMessageManualClose_">LocalFile.ClayAlert#ToastMessageManualClose</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-9/1605784987887/test-portal-acceptance-pullrequest(master)/3956/functional-tomcat90-mysql57-jdk8/0/12/LocalFile.ClayAlert_ToastMessageManualClose/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-9/1605784987887/test-portal-acceptance-pullrequest(master)/3956/functional-tomcat90-mysql57-jdk8/0/12/LocalFile.ClayAlert_ToastMessageManualClose/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-9/1605784987887/test-portal-acceptance-pullrequest(master)/3956/functional-tomcat90-mysql57-jdk8/0/12/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=19,label_exp=!master/369109//consoleText">AXIS_VARIABLE=19,label_exp=!master #369109</a><ol><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=19,label_exp=!master/369109//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_Theme_PublishThemeFromStagedToLive_">LocalFile.Theme#PublishThemeFromStagedToLive</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-9/1605784987887/test-portal-acceptance-pullrequest(master)/3956/functional-tomcat90-mysql57-jdk8/0/19/LocalFile.Theme_PublishThemeFromStagedToLive/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-9/1605784987887/test-portal-acceptance-pullrequest(master)/3956/functional-tomcat90-mysql57-jdk8/0/19/LocalFile.Theme_PublishThemeFromStagedToLive/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-9/1605784987887/test-portal-acceptance-pullrequest(master)/3956/functional-tomcat90-mysql57-jdk8/0/19/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=21,label_exp=!master/369109//consoleText">AXIS_VARIABLE=21,label_exp=!master #369109</a><ol><li><div><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=21,label_exp=!master/369109//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_UIInfrastructureUsecase_RefreshHomePage_">LocalFile.UIInfrastructureUsecase#RefreshHomePage</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-9/1605784987887/test-portal-acceptance-pullrequest(master)/3956/functional-tomcat90-mysql57-jdk8/0/21/LocalFile.UIInfrastructureUsecase_RefreshHomePage/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/test-1-9/1605784987887/test-portal-acceptance-pullrequest(master)/3956/functional-tomcat90-mysql57-jdk8/0/21/LocalFile.UIInfrastructureUsecase_RefreshHomePage/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/tes [...]

2020-11-19 14:26 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-9.liferay.com/job/test-portal-acceptance-pullrequest(master)/3956/">test-portal-acceptance-pullrequest(master)#3956</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-9.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/3956/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> frontend<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-frontend/liferay-portal/pull/500">liferay-frontend#500</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/1746.aspx">/Liferay DXP 7.3/Pull Request/ci:test:frontend</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/62765.aspx">master - PablitoBonito > liferay-frontend - PR#500 - 2020-11-19[03:23:07]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-16.liferay.com/job/publish-spira-report/11536/">publish-spira-report#11536</a><br />

2020-11-30 20:51 UTC, john-co commented
Please also unquarantine the two tests now that these tests have been quarantined.

2020-11-30 20:51 UTC, john-co requested changes

2020-11-30 20:51 UTC, john-co commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/usecase/UIInfrastructureUsecase.testcase
> +			value1 = "none outside none");
@PablitoBonito , you're reverting the fix on this test...

2020-11-30 20:51 UTC, john-co commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/usecase/UIInfrastructureUsecase.testcase
LPS-63100 is only for RefreshWebContent test, you're making changes to RefreshHomePage in this commit... you need to split the changes off to a different commit.

2020-11-30 20:54 UTC, john-co commented on portal-web/test/functional/com/liferay/portalweb/tests/enduser/frontendinfrastructure/uiinfrastructure/usecase/UIInfrastructureUsecase.testcase
Please ask @manoelcyreno  or @zhangyan0701 if need clarification on how to do this.

2020-12-02 12:03 UTC, PablitoBonito commented
@manoelcyreno would like to ask you for clarification.
1. I understood that:
commit LRQA-63100 should have only fix for assertion for RefreshWebContent , notheng else.
LRQA-63099 should have only fix forfor assertion for RefreshHomePage , nothing else.

2. Question during chat with Summer: 
Why I was  asked to create a LPS ticket?
Was not enough use commit message that start with LRQA-xxx ?
Because now two commit messages start with the same LPS id but actually they are fixing two different LRQA tickets.

2020-12-02 15:16 UTC, manoelcyreno commented
1. I understood that:
exactly.
IMHO, on it should be...
Fix the LRQA-63100, send a PR with the solution.
Fix the LRQA-63099, send other different PR with the solution.

2. Question during chat with Summer:
2.1 -> When I try to commit some LRQA I have some problems in the PR, for this reason, I told to create the LPS.
2.2 -> You are solving two problems (two different tickets), so the best practice recommends you create one commit per solution.
2.3 -> so, you need to change your commit message to reflect the reality ...

2020-12-02 18:58 UTC, john-co commented
I discussed with Pawel and clarified the two commit expectation. We will use LPS-123675 for now since it's already created, but in the future I don't think it's necessary to create a LPS for two tickets. We can sync about this in a meeting together if needed @manoelcyreno.

2020-12-04 17:28 UTC, PablitoBonito commented
ci:test:sf

2020-12-04 17:29 UTC, PablitoBonito commented
ci:test:relevant

2020-12-04 17:29 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-1.liferay.com/job/test-portal-source-format/2543/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-1.liferay.com//userContent/jobs/test-portal-source-format/builds/2543/jenkins-report.html">here</a>.</b></p>

2020-12-04 17:30 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest(master)/8606/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-3.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8606/jenkins-report.html">here</a>.</b></p>

2020-12-04 17:34 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:sf - 0 out of 1 jobs passed in 2 hours 30 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f0a34b86bb40d2321310cbd6c6d539b6ce01dc20">f0a34b86bb40d2321310cbd6c6d539b6ce01dc20</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/PablitoBonito/liferay-portal/tree/LRQA-63100">LRQA-63100</a><br/>Branch GIT ID: <a href="https://github.com/PablitoBonito/liferay-portal/commit/9718eeb46d42312617cb139c019e5d711d533a53">9718eeb46d42312617cb139c019e5d711d533a53</a></p>0 out of 1jobs PASSED<div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-1.liferay.com/job/test-portal-source-format/2543/"><strike><strong>test-portal-source-format</strong></strike></a></li></ul></div><h5>For more details click <a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/2543/jenkins-report.html">here</a>.</h5><pre><code>     [java] 	at com.liferay.source.formatter.SourceFormatter.main(SourceFormatter.java:276)
[stopwatch] [run.batch.test.action: 3:59.293 sec]
     [echo] The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:572: The following error occurred while executing this line:
     [echo] /opt/dev/projects/github/liferay-portal/portal-impl/build.xml:715: Java returned: 1
      [get] Getting: http://test-1-1/job/test-portal-source-format/2543//consoleText
      [get] To: /opt/dev/projects/github/liferay-portal/20201204115826468.txt
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/20201204115826468.txt
  [typedef] Could not load definitions from resource org/apache/maven/artifact/ant/antlib.xml. It could not be found.
  [taskdef] Could not load definitions from resource org/jacoco/ant/antlib.xml. It could not be found.
   [delete] Deleting: /opt/dev/projects/github/liferay-portal/null1022138246.properties

merge-test-results:
    [mkdir] Created dir: /opt/dev/projects/github/liferay-portal/test-results
[junitreport] Processing /opt/dev/projects/github/liferay-portal/test-results/TESTS-TestSuites.xml to /tmp/null2099242471
[junitreport] Loading stylesheet jar:file:/opt/java/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 188ms
[junitreport] Deleting: /tmp/null2099242471
     [echo] A report with all the test results can be found at test-results/html/index.html.
    [mkdir] Created dir: /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [copy] Copying 1 file to /opt/dev/projects/github/liferay-jenkins-ee/test-results
     [echo] run.batch.test.tear.down.start.timestamp: 12-04-2020 11:58:31:489 PST
[stopwatch] [run.batch.test.tear.down: 0.000 sec]
     [echo] 
     [echo] Ant GC log:
     [echo] 
     [echo] Java HotSpot(TM) 64-Bit Server VM (25.121-b13) for linux-amd64 JRE (1.8.0_121-b13), built on Dec 12 2016 16:36:53 by "java_re" with gcc 4.3.0 20080428 (Red Hat 4.3.0-8)
     [echo] Memory: 4k page, physical 32902036k(6897076k free), swap 0k(0k free)</code></pre></details></html>

2020-12-04 17:36 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-1.liferay.com/job/test-portal-source-format/2543/">test-portal-source-format#2543</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-1.liferay.com/userContent/jobs/test-portal-source-format/builds/2543/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-frontend/liferay-portal/pull/500">liferay-frontend#500</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2002.aspx">/Liferay DXP 7.4/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/68370.aspx">master - PablitoBonito > liferay-frontend - PR#500 - 2020-12-04[09:29:01]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-8.liferay.com/job/publish-spira-report/9642/">publish-spira-report#9642</a><br />

2020-12-04 18:03 UTC, john-co commented
Please remove `https://...` from your commit messages to start with valid project name.

2020-12-04 19:30 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 2 out of 2 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 6 out of 6 jobs passed in 1 hour 59 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f0a34b86bb40d2321310cbd6c6d539b6ce01dc20">f0a34b86bb40d2321310cbd6c6d539b6ce01dc20</a></p><h4>Copied in Private Modules Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal-ee/tree/master-private">master-private</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal-ee/commit/22478fba589bf9dfa1ff6225fb25ee8fcbb03693">22478fba589bf9dfa1ff6225fb25ee8fcbb03693</a></p><details><summary><strong>ci:test:stable - 2 out of 2 jobs PASSED</strong></summary><details><summary><strong>2 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/372721/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/398386/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 6 out of 6 jobs PASSED</strong></summary><details><summary><strong>6 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest(master)/8606/">test-portal-acceptance-pullrequest(master)</a></li><li><a href="https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/456392/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/372721/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/446340/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/453497/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/398386/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8606/jenkins-report.html">here</a>.</h5></details></html>

2020-12-04 19:33 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-3.liferay.com/job/test-portal-acceptance-pullrequest(master)/8606/">test-portal-acceptance-pullrequest(master)#8606</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-3.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/8606/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> relevant<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-frontend/liferay-portal/pull/500">liferay-frontend#500</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2004.aspx">/Liferay DXP 7.4/Pull Request/ci:test:relevant</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/68412.aspx">master - PablitoBonito > liferay-frontend - PR#500 - 2020-12-04[09:29:58]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-12.liferay.com/job/publish-spira-report/9065/">publish-spira-report#9065</a><br />

2020-12-04 20:05 UTC, john-co commented
The commits need to be rebased, sent to a new PR, and unquarantine the two tests. I'll do this since Pawel will be out on vacation.

2020-12-04 20:06 UTC, closed without merging

2020-12-04 20:51 UTC, john-co commented
pushed to https://github.com/liferay-frontend/liferay-portal/pull/592