LPS-127013 Required date should be populated with current date as in 4bf07cc60479
liferay-frontend/liferay-portal pull request #743
Opened 2021-01-29 07:23 UTC by marianoalvarosaiz

2021-01-29 07:23 UTC, liferay-continuous-integration commented
CI is automatically triggering the following test suites:
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**relevant**
- &nbsp;&nbsp;&nbsp;&nbsp;ci:test:**sf**

2021-01-29 07:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-19.liferay.com/job/test-portal-source-format/5077/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-19.liferay.com//userContent/jobs/test-portal-source-format/builds/5077/jenkins-report.html">here</a>.</b></p>

2021-01-29 07:25 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest(master)/7601/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-19.liferay.com//userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7601/jenkins-report.html">here</a>.</b></p>

2021-01-29 07:33 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 8 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8c437d084cef9ec3e4e1a3382be525bf6875254a">8c437d084cef9ec3e4e1a3382be525bf6875254a</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/marianoalvarosaiz/liferay-portal/tree/LPS-127013">LPS-127013</a><br/>Branch GIT ID: <a href="https://github.com/marianoalvarosaiz/liferay-portal/commit/f79df9bba05c2010e6f4b2b5d6e70cfcb7e62683">f79df9bba05c2010e6f4b2b5d6e70cfcb7e62683</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-19.liferay.com/job/test-portal-source-format/5077/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/5077/jenkins-report.html">here</a>.</h5></details></html>

2021-01-29 07:39 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-19.liferay.com/job/test-portal-source-format/5077/">test-portal-source-format#5077</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-source-format/builds/5077/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> sf<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-frontend/liferay-portal/pull/743">liferay-frontend#743</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2002.aspx">/Liferay DXP 7.4/Pull Request/ci:test:sf</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/84882.aspx">master - marianoalvarosaiz > liferay-frontend - PR#743 - 2021-01-28[23:25:01]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-1.liferay.com/job/publish-spira-report/18431/">publish-spira-report#18431</a><br />

2021-01-29 08:50 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:stable - 2 out of 2 jobs passed</h3><h3>:heavy_check_mark: ci:test:relevant - 6 out of 6 jobs passed in 1 hour 24 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8c437d084cef9ec3e4e1a3382be525bf6875254a">8c437d084cef9ec3e4e1a3382be525bf6875254a</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8c437d084cef9ec3e4e1a3382be525bf6875254a">8c437d084cef9ec3e4e1a3382be525bf6875254a</a><br/>Jenkins Build URL: <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)//1501">Acceptance Upstream DXP (master) #1501</a></p><details><summary><strong>ci:test:stable - 2 out of 2 jobs PASSED</strong></summary><details><summary><strong>2 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/377247/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/347556/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li></ul></details></details><details><summary><strong>ci:test:relevant - 6 out of 6 jobs PASSED</strong></summary><details><summary><strong>6 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest(master)/7601/">test-portal-acceptance-pullrequest(master)</a></li><li><a href="https://test-1-13.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/423740/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk11_open/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/377247/">test-portal-acceptance-pullrequest-batch(master)/functional-smoke-tomcat90-mysql57-jdk8_stable/0</a></li><li><a href="https://test-1-10.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/377246/">test-portal-acceptance-pullrequest-batch(master)/functional-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/320891/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8/0</a></li><li><a href="https://test-1-12.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/347556/">test-portal-acceptance-pullrequest-batch(master)/functional-upgrade-tomcat90-mysql57-jdk8_stable/0</a></li></ul></details></details><h5>For more details click <a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7601/jenkins-report.html">here</a>.</h5></details></html>

2021-01-29 09:03 UTC, liferay-continuous-integration commented
<strong>Jenkins Build:</strong><a href="https://test-1-19.liferay.com/job/test-portal-acceptance-pullrequest(master)/7601/">test-portal-acceptance-pullrequest(master)#7601</a><br /><strong>Jenkins Report:</strong><a href="https://test-1-19.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7601/jenkins-report.html">jenkins-report.html</a><br /><strong>Jenkins Suite:</strong> relevant<br /><strong>Pull Request:</strong><a href="https://github.com/liferay-frontend/liferay-portal/pull/743">liferay-frontend#743</a><br /><strong>Spira Release:</strong><a href="https://liferay.spiraservice.net/16/Release/2004.aspx">/Liferay DXP 7.4/Pull Request/ci:test:relevant</a><br /><strong>Spira Release Build:</strong><a href="https://liferay.spiraservice.net/16/Build/84910.aspx">master - marianoalvarosaiz > liferay-frontend - PR#743 - 2021-01-28[23:25:01]</a><br /><strong>Spira Jenkins Build:</strong><a href="https://test-1-1.liferay.com/job/publish-spira-report/18438/">publish-spira-report#18438</a><br />

2021-01-29 15:07 UTC, markocikos requested changes

2021-01-29 15:07 UTC, markocikos commented on portal-web/docroot/html/taglib/ui/input_date/page.jsp
> +}
This does not look right. If `*Value` attributes are set, but also `required` is true, `*Value` params will be ignored and we will take current value.

2021-01-29 15:12 UTC, markocikos commented
> No description provided.

@marianoalvarosaiz Please provide a description and steps to test :pray:   See [Pull Request Etiquette](https://github.com/liferay/liferay-frontend-projects/blob/master/guidelines/general/pull_requests.md)

2021-02-01 07:47 UTC, closed without merging

2021-02-01 07:52 UTC, marianoalvarosaiz commented
See https://github.com/liferay-frontend/liferay-portal/pull/745